(function(b,a){a("kendo.calendar",["kendo.core"],b);
}(function(){var a={id:"calendar",name:"Calendar",category:"web",description:"The Calendar widget renders a graphical calendar that supports navigation and selection.",depends:["core"]};
(function(b,ax){var M=window.kendo,ap=M.support,aw=M.ui,aD=aw.Widget,O=M.keys,ah=M.parseDate,d=M.date.adjustDST,aB=M.date.weekInYear,w=M._extractFormat,aq=M.template,B=M.getCulture,av=M.support.transitions,au=av?av.css+"transform-origin":"",l=aq('<td#=data.cssClass# role="gridcell"><a tabindex="-1" class="k-link" href="\\#" data-#=data.ns#value="#=data.dateString#">#=data.value#</a></td>',{useWithBlock:false}),u=aq('<td role="gridcell">&nbsp;</td>',{useWithBlock:false}),aC=aq('<td class="k-alt">#= data.weekNumber #</td>',{useWithBlock:false}),h=M.support.browser,K=h.msie&&h.version<9,af=M._outerHeight,ag=M._outerWidth,ac=".kendoCalendar",o="click"+ac,N="keydown"+ac,F="id",R="min",P="left",ao="slideIn",S="month",m="century",n="change",Z="navigate",ay="value",E="k-state-hover",t="k-state-disabled",z="k-state-focused",ad="k-other-month",ae=' class="'+ad+'"',at="k-nav-today",k="td:has(.k-link)",g="blur"+ac,x="focus",y=x+ac,T=ap.touch?"touchstart":"mouseenter",U=ap.touch?"touchstart"+ac:"mouseenter"+ac,V=ap.touch?"touchend"+ac+" touchmove"+ac:"mouseleave"+ac,Y=60000,X=86400000,ai="_prevArrow",aa="_nextArrow",e="aria-disabled",f="aria-selected",ak=b.proxy,v=b.extend,s=Date,aA={month:0,year:1,decade:2,century:3};
var j=aD.extend({init:function(aE,aG){var aH=this,aI,aF;
aD.fn.init.call(aH,aE,aG);
aE=aH.wrapper=aH.element;
aG=aH.options;
aG.url=window.unescape(aG.url);
aH.options.disableDates=C(aH.options.disableDates);
aH._templates();
aH._header();
aH._footer(aH.footer);
aF=aE.addClass("k-widget k-calendar "+(aG.weekNumber?" k-week-number":"")).on(U+" "+V,k,W).on(N,"table.k-content",ak(aH._move,aH)).on(o,k,function(aJ){var aK=aJ.currentTarget.firstChild,aL=aH._toDateObject(aK);
if(aK.href.indexOf("#")!=-1){aJ.preventDefault();
}if(aH._view.name=="month"&&aH.options.disableDates(aL)){return;
}aH._click(b(aK));
}).on("mouseup"+ac,"table.k-content, .k-footer",function(){aH._focusView(aH.options.focusOnNav!==false);
}).attr(F);
if(aF){aH._cellID=aF+"_cell_selected";
}ab(aG);
aI=ah(aG.value,aG.format,aG.culture);
aH._index=aA[aG.start];
aH._current=new s(+al(aI,aG.min,aG.max));
aH._addClassProxy=function(){aH._active=true;
if(aH._cell.hasClass(t)){var aJ=aH._view.toDateString(D());
aH._cell=aH._cellByDate(aJ);
}aH._cell.addClass(z);
};
aH._removeClassProxy=function(){aH._active=false;
aH._cell.removeClass(z);
};
aH.value(aI);
M.notify(aH);
},options:{name:"Calendar",value:null,min:new s(1900,0,1),max:new s(2099,11,31),dates:[],url:"",culture:"",footer:"",format:"",month:{},weekNumber:false,start:S,depth:S,animation:{horizontal:{effects:ao,reverse:true,duration:500,divisor:2},vertical:{effects:"zoomIn",duration:400}}},events:[n,Z],setOptions:function(aE){var aF=this;
ab(aE);
aE.disableDates=C(aE.disableDates);
aD.fn.setOptions.call(aF,aE);
aF._templates();
aF._footer(aF.footer);
aF._index=aA[aF.options.start];
aF.navigate();
},destroy:function(){var aE=this,aF=aE._today;
aE.element.off(ac);
aE._title.off(ac);
aE[ai].off(ac);
aE[aa].off(ac);
M.destroy(aE._table);
if(aF){M.destroy(aF.off(ac));
}aD.fn.destroy.call(aE);
},current:function(){return this._current;
},view:function(){return this._view;
},focus:function(aE){aE=aE||this._table;
this._bindTable(aE);
aE.focus();
},min:function(aE){return this._option(R,aE);
},max:function(aE){return this._option("max",aE);
},navigateToPast:function(){this._navigate(ai,-1);
},navigateToFuture:function(){this._navigate(aa,1);
},navigateUp:function(){var aF=this,aE=aF._index;
if(aF._title.hasClass(t)){return;
}aF.navigate(aF._current,++aE);
},navigateDown:function(aH){var aG=this,aF=aG._index,aE=aG.options.depth;
if(!aH){return;
}if(aF===aA[aE]){if(!H(aG._value,aG._current)||!H(aG._value,aH)){aG.value(aH);
aG.trigger(n);
}return;
}aG.navigate(aH,--aF);
},navigate:function(aU,aW){aW=isNaN(aW)?aA[aW]:aW;
var aR=this,aO=aR.options,aF=aO.culture,aM=aO.min,aL=aO.max,aS=aR._title,aJ=aR._table,aN=aR._oldTable,aQ=aR._value,aG=aR._current,aK=aU&&+aU>+aG,aV=aW!==ax&&aW!==aR._index,aT,aH,aE,aI;
if(!aU){aU=aG;
}aR._current=aU=new s(+al(aU,aM,aL));
if(aW===ax){aW=aR._index;
}else{aR._index=aW;
}aR._view=aH=i.views[aW];
aE=aH.compare;
aI=aW===aA[m];
aS.toggleClass(t,aI).attr(e,aI);
aI=aE(aU,aM)<1;
aR[ai].toggleClass(t,aI).attr(e,aI);
aI=aE(aU,aL)>-1;
aR[aa].toggleClass(t,aI).attr(e,aI);
if(aJ&&aN&&aN.data("animating")){aN.kendoStop(true,true);
aJ.kendoStop(true,true);
}aR._oldTable=aJ;
if(!aJ||aR._changeView){aS.html(aH.title(aU,aM,aL,aF));
aR._table=aT=b(aH.content(v({min:aM,max:aL,date:aU,url:aO.url,dates:aO.dates,format:aO.format,culture:aF,disableDates:aO.disableDates,isWeekColumnVisible:aO.weekNumber},aR[aH.name])));
c(aT,aH.name);
Q(aT);
var aP=aJ&&aJ.data("start")===aT.data("start");
aR._animate({from:aJ,to:aT,vertical:aV,future:aK,replace:aP});
aR.trigger(Z);
aR._focus(aU);
}if(aW===aA[aO.depth]&&aQ&&!aR.options.disableDates(aQ)){aR._class("k-state-selected",aQ);
}aR._class(z,aU);
if(!aJ&&aR._cell){aR._cell.removeClass(z);
}aR._changeView=true;
},value:function(aJ){var aI=this,aK=aI._view,aH=aI.options,aG=aI._view,aF=aH.min,aE=aH.max;
if(aJ===ax){return aI._value;
}if(aJ===null){aI._current=new Date(aI._current.getFullYear(),aI._current.getMonth(),aI._current.getDate());
}aJ=ah(aJ,aH.format,aH.culture);
if(aJ!==null){aJ=new s(+aJ);
if(!L(aJ,aF,aE)){aJ=null;
}}if(aJ===null||!aI.options.disableDates(aJ)){aI._value=aJ;
}else{if(aI._value===ax){aI._value=null;
}}if(aG&&aJ===null&&aI._cell){aI._cell.removeClass("k-state-selected");
}else{aI._changeView=!aJ||aK&&aK.compare(aJ,aI._current)!==0;
aI.navigate(aJ);
}},_move:function(aF){var aQ=this,aN=aQ.options,aJ=aF.keyCode,aS=aQ._view,aG=aQ._index,aM=aQ.options.min,aK=aQ.options.max,aE=new s(+aQ._current),aI=M.support.isRtl(aQ.wrapper),aH=aQ.options.disableDates,aR,aO,aL,aP;
if(aF.target===aQ._table[0]){aQ._active=true;
}if(aF.ctrlKey){if(aJ==O.RIGHT&&!aI||aJ==O.LEFT&&aI){aQ.navigateToFuture();
aO=true;
}else{if(aJ==O.LEFT&&!aI||aJ==O.RIGHT&&aI){aQ.navigateToPast();
aO=true;
}else{if(aJ==O.UP){aQ.navigateUp();
aO=true;
}else{if(aJ==O.DOWN){aQ._click(b(aQ._cell[0].firstChild));
aO=true;
}}}}}else{if(aJ==O.RIGHT&&!aI||aJ==O.LEFT&&aI){aR=1;
aO=true;
}else{if(aJ==O.LEFT&&!aI||aJ==O.RIGHT&&aI){aR=-1;
aO=true;
}else{if(aJ==O.UP){aR=aG===0?-7:-4;
aO=true;
}else{if(aJ==O.DOWN){aR=aG===0?7:4;
aO=true;
}else{if(aJ==O.ENTER){aQ._click(b(aQ._cell[0].firstChild));
aO=true;
}else{if(aJ==O.HOME||aJ==O.END){aL=aJ==O.HOME?"first":"last";
aP=aS[aL](aE);
aE=new s(aP.getFullYear(),aP.getMonth(),aP.getDate(),aE.getHours(),aE.getMinutes(),aE.getSeconds(),aE.getMilliseconds());
aO=true;
}else{if(aJ==O.PAGEUP){aO=true;
aQ.navigateToPast();
}else{if(aJ==O.PAGEDOWN){aO=true;
aQ.navigateToFuture();
}}}}}}}}if(aR||aL){if(!aL){aS.setDate(aE,aR);
}if(aH(aE)){aE=aQ._nextNavigatable(aE,aR);
}if(L(aE,aM,aK)){aQ._focus(al(aE,aN.min,aN.max));
}}}if(aO){aF.preventDefault();
}return aQ._current;
},_nextNavigatable:function(aE,aL){var aK=this,aF=true,aM=aK._view,aI=aK.options.min,aH=aK.options.max,aG=aK.options.disableDates,aJ=new Date(aE.getTime());
aM.setDate(aJ,-aL);
while(aF){aM.setDate(aE,aL);
if(!L(aE,aI,aH)){aE=aJ;
break;
}aF=aG(aE);
}return aE;
},_animate:function(aG){var aH=this,aF=aG.from,aI=aG.to,aE=aH._active;
if(!aF){aI.insertAfter(aH.element[0].firstChild);
aH._bindTable(aI);
}else{if(aF.parent().data("animating")){aF.off(ac);
aF.parent().kendoStop(true,true).remove();
aF.remove();
aI.insertAfter(aH.element[0].firstChild);
aH._focusView(aE);
}else{if(!aF.is(":visible")||aH.options.animation===false||aG.replace){aI.insertAfter(aF);
aF.off(ac).remove();
aH._focusView(aE);
}else{aH[aG.vertical?"_vertical":"_horizontal"](aF,aI,aG.future);
}}}},_horizontal:function(aG,aK,aH){var aJ=this,aE=aJ._active,aI=aJ.options.animation.horizontal,aF=aI.effects,aL=ag(aG);
if(aF&&aF.indexOf(ao)!=-1){aG.add(aK).css({width:aL});
aG.wrap("<div/>");
aJ._focusView(aE,aG);
aG.parent().css({position:"relative",width:aL*2,"float":P,"margin-left":aH?0:-aL});
aK[aH?"insertAfter":"insertBefore"](aG);
v(aI,{effects:ao+":"+(aH?"right":P),complete:function(){aG.off(ac).remove();
aJ._oldTable=null;
aK.unwrap();
aJ._focusView(aE);
}});
aG.parent().kendoStop(true,true).kendoAnimate(aI);
}},_vertical:function(aH,aK){var aJ=this,aL=aJ.options.animation.vertical,aG=aL.effects,aE=aJ._active,aF,aI;
if(aG&&aG.indexOf("zoom")!=-1){aK.css({position:"absolute",top:af(aH.prev()),left:0}).insertBefore(aH);
if(au){aF=aJ._cellByDate(aJ._view.toDateString(aJ._current));
aI=aF.position();
aI=aI.left+parseInt(aF.width()/2,10)+"px "+(aI.top+parseInt(aF.height()/2,10)+"px");
aK.css(au,aI);
}aH.kendoStop(true,true).kendoAnimate({effects:"fadeOut",duration:600,complete:function(){aH.off(ac).remove();
aJ._oldTable=null;
aK.css({position:"static",top:0,left:0});
aJ._focusView(aE);
}});
aK.kendoStop(true,true).kendoAnimate(aL);
}},_cellByDate:function(aE){return this._table.find("td:not(."+ad+")").filter(function(){return b(this.firstChild).attr(M.attr(ay))===aE;
});
},_class:function(aF,aG){var aJ=this,aI=aJ._cellID,aE=aJ._cell,aK=aJ._view.toDateString(aG),aH;
if(aE){aE.removeAttr(f).removeAttr("aria-label").removeAttr(F);
}if(aG&&aJ._view.name=="month"){aH=aJ.options.disableDates(aG);
}aE=aJ._table.find("td:not(."+ad+")").removeClass(aF).filter(function(){return b(this.firstChild).attr(M.attr(ay))===aK;
}).attr(f,true);
if(aF===z&&!aJ._active&&aJ.options.focusOnNav!==false||aH){aF="";
}aE.addClass(aF);
if(aE[0]){aJ._cell=aE;
}if(aI){aE.attr(F,aI);
aJ._table.removeAttr("aria-activedescendant").attr("aria-activedescendant",aI);
}},_bindTable:function(aE){aE.on(y,this._addClassProxy).on(g,this._removeClassProxy);
},_click:function(aF){var aH=this,aG=aH.options,aE=new Date(+aH._current),aI=aH._toDateObject(aF);
d(aI,0);
if(aH._view.name=="month"&&aH.options.disableDates(aI)){aI=aH._value;
}aH._view.setDate(aE,aI);
aH.navigateDown(al(aE,aG.min,aG.max));
},_focus:function(aF){var aE=this,aG=aE._view;
if(aG.compare(aF,aE._current)!==0){aE.navigate(aF);
}else{aE._current=aF;
aE._class(z,aF);
}},_focusView:function(aE,aF){if(aE){this.focus(aF);
}},_footer:function(aG){var aH=this,aI=D(),aE=aH.element,aF=aE.find(".k-footer");
if(!aG){aH._toggle(false);
aF.hide();
return;
}if(!aF[0]){aF=b('<div class="k-footer"><a href="#" class="k-link k-nav-today"></a></div>').appendTo(aE);
}aH._today=aF.show().find(".k-link").html(aG(aI)).attr("title",M.toString(aI,"D",aH.options.culture));
aH._toggle();
},_header:function(){var aG=this,aE=aG.element,aF;
if(!aE.find(".k-header")[0]){aE.html('<div class="k-header"><a href="#" role="button" class="k-link k-nav-prev"><span class="k-icon k-i-arrow-60-left"></span></a><a href="#" role="button" aria-live="assertive" aria-atomic="true" class="k-link k-nav-fast"></a><a href="#" role="button" class="k-link k-nav-next"><span class="k-icon k-i-arrow-60-right"></span></a></div>');
}aF=aE.find(".k-link").on(U+" "+V+" "+y+" "+g,W).click(false);
aG._title=aF.eq(1).on(o,function(){aG._active=aG.options.focusOnNav!==false;
aG.navigateUp();
});
aG[ai]=aF.eq(0).on(o,function(){aG._active=aG.options.focusOnNav!==false;
aG.navigateToPast();
});
aG[aa]=aF.eq(2).on(o,function(){aG._active=aG.options.focusOnNav!==false;
aG.navigateToFuture();
});
},_navigate:function(aE,aH){var aI=this,aG=aI._index+1,aF=new s(+aI._current);
aE=aI[aE];
if(!aE.hasClass(t)){if(aG>3){aF.setFullYear(aF.getFullYear()+100*aH);
}else{i.views[aG].setDate(aF,aH);
}aI.navigate(aF);
}},_option:function(aG,aJ){var aI=this,aH=aI.options,aE=aI._value||aI._current,aF;
if(aJ===ax){return aH[aG];
}aJ=ah(aJ,aH.format,aH.culture);
if(!aJ){return;
}aH[aG]=new s(+aJ);
if(aG===R){aF=aJ>aE;
}else{aF=aE>aJ;
}if(aF||J(aE,aJ)){if(aF){aI._value=null;
}aI._changeView=true;
}if(!aI._changeView){aI._changeView=!!(aH.month.content||aH.month.empty);
}aI.navigate(aI._value);
aI._toggle();
},_toggle:function(aI){var aH=this,aG=aH.options,aE=aH.options.disableDates(D()),aF=aH._today;
if(aI===ax){aI=L(D(),aG.min,aG.max);
}if(aF){aF.off(o);
if(aI&&!aE){aF.addClass(at).removeClass(t).on(o,ak(aH._todayClick,aH));
}else{aF.removeClass(at).addClass(t).on(o,aj);
}}},_todayClick:function(aG){var aH=this,aE=aA[aH.options.depth],aF=aH.options.disableDates,aI=D();
aG.preventDefault();
if(aF(aI)){return;
}if(aH._view.compare(aH._current,aI)===0&&aH._index==aE){aH._changeView=false;
}aH._value=aI;
aH.navigate(aI,aE);
aH.trigger(n);
},_toDateObject:function(aE){var aF=b(aE).attr(M.attr(ay)).split("/");
aF=new s(aF[0],aF[1],aF[2]);
return aF;
},_templates:function(){var aJ=this,aI=aJ.options,aG=aI.footer,aH=aI.month,aE=aH.content,aK=aH.weekNumber,aF=aH.empty;
aJ.month={content:aq('<td#=data.cssClass# role="gridcell"><a tabindex="-1" class="k-link#=data.linkClass#" href="#=data.url#" '+M.attr("value")+'="#=data.dateString#" title="#=data.title#">'+(aE||"#=data.value#")+"</a></td>",{useWithBlock:!!aE}),empty:aq('<td role="gridcell">'+(aF||"&nbsp;")+"</td>",{useWithBlock:!!aF}),weekNumber:aq('<td class="k-alt">'+(aK||"#= data.weekNumber #")+"</td>",{useWithBlock:!!aK})};
aJ.footer=aG!==false?aq(aG||'#= kendo.toString(data,"D","'+aI.culture+'") #',{useWithBlock:false}):null;
}});
aw.plugin(j);
var i={firstDayOfMonth:function(aE){return new s(aE.getFullYear(),aE.getMonth(),1);
},firstVisibleDay:function(aF,aE){aE=aE||M.culture().calendar;
var aG=aE.firstDay,aH=new s(aF.getFullYear(),aF.getMonth(),0,aF.getHours(),aF.getMinutes(),aF.getSeconds(),aF.getMilliseconds());
while(aH.getDay()!=aG){i.setTime(aH,-1*X);
}return aH;
},setTime:function(aE,aG){var aH=aE.getTimezoneOffset(),aF=new s(aE.getTime()+aG),aI=aF.getTimezoneOffset()-aH;
aE.setTime(aF.getTime()+aI*Y);
},views:[{name:S,title:function(aF,aH,aG,aE){return A(aE).months.names[aF.getMonth()]+" "+aF.getFullYear();
},content:function(aV){var aY=this,aO=0,aS=aV.min,aR=aV.max,aG=aV.date,aH=aV.dates,aL=aV.format,aE=aV.culture,aU=aV.url,aP=aV.isWeekColumnVisible,aM=aU&&aH[0],aF=A(aE),aJ=aF.firstDay,aI=aF.days,aT=an(aI.names,aJ),aW=an(aI.namesShort,aJ),aX=i.firstVisibleDay(aG,aF),aK=aY.first(aG),aQ=aY.last(aG),aZ=aY.toDateString,a0=new s(),aN='<table tabindex="0" role="grid" class="k-content" cellspacing="0" data-start="'+aZ(aX)+'"><thead><tr role="row">';
if(aP){aN+='<th scope="col" class="k-alt"></th>';
}for(;
aO<7;
aO++){aN+='<th scope="col" title="'+aT[aO]+'">'+aW[aO]+"</th>";
}a0=new s(a0.getFullYear(),a0.getMonth(),a0.getDate());
d(a0,0);
a0=+a0;
return az({cells:42,perRow:7,html:aN+='</tr></thead><tbody><tr role="row">',start:aX,isWeekColumnVisible:aP,weekNumber:aV.weekNumber,min:new s(aS.getFullYear(),aS.getMonth(),aS.getDate()),max:new s(aR.getFullYear(),aR.getMonth(),aR.getDate()),content:aV.content,empty:aV.empty,setter:aY.setDate,disableDates:aV.disableDates,build:function(a2,a5,a4){var a1=[],a3=a2.getDay(),a6="",a7="#";
if(a2<aK||a2>aQ){a1.push(ad);
}if(a4(a2)){a1.push(t);
}if(+a2===a0){a1.push("k-today");
}if(a3===0||a3===6){a1.push("k-weekend");
}if(aM&&G(+a2,aH)){a7=aU.replace("{0}",M.toString(a2,aL,aE));
a6=" k-action-link";
}return{date:a2,dates:aH,ns:M.ns,title:M.toString(a2,"D",aE),value:a2.getDate(),dateString:aZ(a2),cssClass:a1[0]?' class="'+a1.join(" ")+'"':"",linkClass:a6,url:a7};
},weekNumberBuild:function(a1){return{weekNumber:aB(a1,a1),currentDate:a1};
}});
},first:function(aE){return i.firstDayOfMonth(aE);
},last:function(aE){var aG=new s(aE.getFullYear(),aE.getMonth()+1,0),aF=i.firstDayOfMonth(aE),aH=Math.abs(aG.getTimezoneOffset()-aF.getTimezoneOffset());
if(aH){aG.setHours(aF.getHours()+aH/60);
}return aG;
},compare:function(aE,aF){var aI,aG=aE.getMonth(),aJ=aE.getFullYear(),aH=aF.getMonth(),aK=aF.getFullYear();
if(aJ>aK){aI=1;
}else{if(aJ<aK){aI=-1;
}else{aI=aG==aH?0:aG>aH?1:-1;
}}return aI;
},setDate:function(aE,aG){var aF=aE.getHours();
if(aG instanceof s){aE.setFullYear(aG.getFullYear(),aG.getMonth(),aG.getDate());
}else{i.setTime(aE,aG*X);
}d(aE,aF);
},toDateString:function(aE){return aE.getFullYear()+"/"+aE.getMonth()+"/"+aE.getDate();
}},{name:"year",title:function(aE){return aE.getFullYear();
},content:function(aH){var aG=A(aH.culture).months.namesAbbr,aI=this.toDateString,aF=aH.min,aE=aH.max;
return az({min:new s(aF.getFullYear(),aF.getMonth(),1),max:new s(aE.getFullYear(),aE.getMonth(),1),start:new s(aH.date.getFullYear(),0,1),setter:this.setDate,build:function(aJ){return{value:aG[aJ.getMonth()],ns:M.ns,dateString:aI(aJ),cssClass:""};
}});
},first:function(aE){return new s(aE.getFullYear(),0,aE.getDate());
},last:function(aE){return new s(aE.getFullYear(),11,aE.getDate());
},compare:function(aE,aF){return p(aE,aF);
},setDate:function(aE,aH){var aG,aF=aE.getHours();
if(aH instanceof s){aG=aH.getMonth();
aE.setFullYear(aH.getFullYear(),aG,aE.getDate());
if(aG!==aE.getMonth()){aE.setDate(0);
}}else{aG=aE.getMonth()+aH;
aE.setMonth(aG);
if(aG>11){aG-=12;
}if(aG>0&&aE.getMonth()!=aG){aE.setDate(0);
}}d(aE,aF);
},toDateString:function(aE){return aE.getFullYear()+"/"+aE.getMonth()+"/1";
}},{name:"decade",title:function(aE,aG,aF){return ar(aE,aG,aF,10);
},content:function(aE){var aG=aE.date.getFullYear(),aF=this.toDateString;
return az({start:new s(aG-aG%10-1,0,1),min:new s(aE.min.getFullYear(),0,1),max:new s(aE.max.getFullYear(),0,1),setter:this.setDate,build:function(aH,aI){return{value:aH.getFullYear(),ns:M.ns,dateString:aF(aH),cssClass:aI===0||aI==11?ae:""};
}});
},first:function(aE){var aF=aE.getFullYear();
return new s(aF-aF%10,aE.getMonth(),aE.getDate());
},last:function(aE){var aF=aE.getFullYear();
return new s(aF-aF%10+9,aE.getMonth(),aE.getDate());
},compare:function(aE,aF){return p(aE,aF,10);
},setDate:function(aE,aF){am(aE,aF,1);
},toDateString:function(aE){return aE.getFullYear()+"/0/1";
}},{name:m,title:function(aE,aG,aF){return ar(aE,aG,aF,100);
},content:function(aI){var aK=aI.date.getFullYear(),aG=aI.min.getFullYear(),aE=aI.max.getFullYear(),aJ=this.toDateString,aH=aG,aF=aE;
aH=aH-aH%10;
aF=aF-aF%10;
if(aF-aH<10){aF=aH+9;
}return az({start:new s(aK-aK%100-10,0,1),min:new s(aH,0,1),max:new s(aF,0,1),setter:this.setDate,build:function(aL,aN){var aO=aL.getFullYear(),aM=aO+9;
if(aO<aG){aO=aG;
}if(aM>aE){aM=aE;
}return{ns:M.ns,value:aO+" - "+aM,dateString:aJ(aL),cssClass:aN===0||aN==11?ae:""};
}});
},first:function(aE){var aF=aE.getFullYear();
return new s(aF-aF%100,aE.getMonth(),aE.getDate());
},last:function(aE){var aF=aE.getFullYear();
return new s(aF-aF%100+99,aE.getMonth(),aE.getDate());
},compare:function(aE,aF){return p(aE,aF,100);
},setDate:function(aE,aF){am(aE,aF,10);
},toDateString:function(aE){var aF=aE.getFullYear();
return aF-aF%10+"/0/1";
}}]};
function ar(aE,aI,aG,aK){var aL=aE.getFullYear(),aJ=aI.getFullYear(),aH=aG.getFullYear(),aF;
aL=aL-aL%aK;
aF=aL+(aK-1);
if(aL<aJ){aL=aJ;
}if(aF>aH){aF=aH;
}return aL+"-"+aF;
}function az(aP){var aK=0,aH,aO=aP.min,aN=aP.max,aR=aP.start,aQ=aP.setter,aE=aP.build,aT=aP.weekNumberBuild,aM=aP.cells||12,aL=aP.isWeekColumnVisible,aF=aP.perRow||4,aS=aP.weekNumber||aC,aG=aP.content||l,aI=aP.empty||u,aJ=aP.html||'<table tabindex="0" role="grid" class="k-content k-meta-view" cellspacing="0"><tbody><tr role="row">';
if(aL){aJ+=aS(aT(aR));
}for(;
aK<aM;
aK++){if(aK>0&&aK%aF===0){aJ+='</tr><tr role="row">';
if(aL){aJ+=aS(aT(aR));
}}aR=new s(aR.getFullYear(),aR.getMonth(),aR.getDate(),0,0,0);
d(aR,0);
aH=aE(aR,aK,aP.disableDates);
aJ+=L(aR,aO,aN)?aG(aH):aI(aH);
aQ(aR,1);
}return aJ+"</tr></tbody></table>";
}function p(aE,aF,aH){var aK=aE.getFullYear(),aJ=aF.getFullYear(),aG=aJ,aI=0;
if(aH){aJ=aJ-aJ%aH;
aG=aJ-aJ%aH+aH-1;
}if(aK>aG){aI=1;
}else{if(aK<aJ){aI=-1;
}}return aI;
}function D(){var aE=new s();
return new s(aE.getFullYear(),aE.getMonth(),aE.getDate());
}function al(aH,aF,aE){var aG=D();
if(aH){aG=new s(+aH);
}if(aF>aG){aG=new s(+aF);
}else{if(aE<aG){aG=new s(+aE);
}}return aG;
}function L(aE,aG,aF){return +aE>=+aG&&+aE<=+aF;
}function an(aE,aF){return aE.slice(aF).concat(aE.slice(0,aF));
}function am(aE,aG,aF){aG=aG instanceof s?aG.getFullYear():aE.getFullYear()+aF*aG;
aE.setFullYear(aG);
}function W(aF){var aE=b(this).hasClass("k-state-disabled");
if(!aE){b(this).toggleClass(E,T.indexOf(aF.type)>-1||aF.type==x);
}}function aj(aE){aE.preventDefault();
}function A(aE){return B(aE).calendars.standard;
}function ab(aG){var aH=aA[aG.start],aF=aA[aG.depth],aE=B(aG.culture);
aG.format=w(aG.format||aE.calendars.standard.patterns.d);
if(isNaN(aH)){aH=0;
aG.start=S;
}if(aF===ax||aF>aH){aG.depth=S;
}if(aG.dates===null){aG.dates=[];
}}function Q(aE){if(K){aE.find("*").attr("unselectable","on");
}}function c(aF,aE){aF.addClass("k-"+aE);
}function G(aE,aF){for(var aG=0,aH=aF.length;
aG<aH;
aG++){if(aE===+aF[aG]){return true;
}}return false;
}function I(aE,aF){if(aE){return aE.getFullYear()===aF.getFullYear()&&aE.getMonth()===aF.getMonth()&&aE.getDate()===aF.getDate();
}return false;
}function J(aE,aF){if(aE){return aE.getFullYear()===aF.getFullYear()&&aE.getMonth()===aF.getMonth();
}return false;
}function C(aE){if(M.isFunction(aE)){return aE;
}if(b.isArray(aE)){return r(aE);
}return b.noop;
}function q(aE){var aG=[];
for(var aF=0;
aF<aE.length;
aF++){aG.push(aE[aF].setHours(0,0,0,0));
}return aG;
}function r(aG){var aE,aF,aJ=[],aI=["su","mo","tu","we","th","fr","sa"],aM="if (found) { return true } else {return false}";
if(aG[0] instanceof s){aJ=q(aG);
aE="var found = date && $.inArray(date.setHours(0, 0, 0, 0),["+aJ+"]) > -1;"+aM;
}else{for(var aK=0;
aK<aG.length;
aK++){var aH=aG[aK].slice(0,2).toLowerCase();
var aL=b.inArray(aH,aI);
if(aL>-1){aJ.push(aL);
}}aE="var found = date && $.inArray(date.getDay(),["+aJ+"]) > -1;"+aM;
}aF=new Function("date",aE);
return aF;
}function H(aF,aE){if(aF instanceof Date&&aE instanceof Date){aF=aF.getTime();
aE=aE.getTime();
}return aF===aE;
}i.isEqualDatePart=I;
i.isEqualDate=H;
i.makeUnselectable=Q;
i.restrictValue=al;
i.isInRange=L;
i.addClassToViewContainer=c;
i.normalize=ab;
i.viewsEnum=aA;
i.disabled=C;
M.calendar=i;
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
