(function(b,a){a("kendo.color",["kendo.core"],b);
}(function(){var a={id:"color",name:"Color utils",category:"framework",advanced:true,description:"Color utilities used across components",depends:["core"]};
window.kendo=window.kendo||{};
var e=kendo.Class;
var q=kendo.support;
var n={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"00ffff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000000",blanchedalmond:"ffebcd",blue:"0000ff",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",cornsilk:"fff8dc",crimson:"dc143c",cyan:"00ffff",darkblue:"00008b",darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgrey:"a9a9a9",darkgreen:"006400",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",darkslategray:"2f4f4f",darkslategrey:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dimgrey:"696969",dodgerblue:"1e90ff",firebrick:"b22222",floralwhite:"fffaf0",forestgreen:"228b22",fuchsia:"ff00ff",gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",grey:"808080",green:"008000",greenyellow:"adff2f",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgray:"d3d3d3",lightgrey:"d3d3d3",lightgreen:"90ee90",lightpink:"ffb6c1",lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",lightslategray:"778899",lightslategrey:"778899",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"00ff00",limegreen:"32cd32",linen:"faf0e6",magenta:"ff00ff",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370d8",mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"d87093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",powderblue:"b0e0e6",purple:"800080",red:"ff0000",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",slategray:"708090",slategrey:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",wheat:"f5deb3",white:"ffffff",whitesmoke:"f5f5f5",yellow:"ffff00",yellowgreen:"9acd32"};
var c=q.browser;
var m=["transparent"];
for(var l in n){if(n.hasOwnProperty(l)){m.push(l);
}}m=new RegExp("^("+m.join("|")+")(\\W|$)","i");
var b=e.extend({init:function(){},toHSV:function(){return this;
},toRGB:function(){return this;
},toHex:function(){return this.toBytes().toHex();
},toBytes:function(){return this;
},toCss:function(){return"#"+this.toHex();
},toCssRgba:function(){var i=this.toBytes();
return"rgba("+i.r+", "+i.g+", "+i.b+", "+parseFloat(Number(this.a).toFixed(3))+")";
},toDisplay:function(){if(c.msie&&c.version<9){return this.toCss();
}return this.toCssRgba();
},equals:function(i){return i===this||i!==null&&this.toCssRgba()===o(i).toCssRgba();
},diff:function(s){if(s===null){return NaN;
}var i=this.toBytes();
var r=s.toBytes();
return Math.sqrt(Math.pow((i.r-r.r)*0.3,2)+Math.pow((i.g-r.g)*0.59,2)+Math.pow((i.b-r.b)*0.11,2));
},clone:function(){var i=this.toBytes();
if(i===this){i=new d(i.r,i.g,i.b,i.a);
}return i;
}});
var p=b.extend({init:function(u,t,s,i){b.fn.init.call(this);
this.r=u;
this.g=t;
this.b=s;
this.a=i;
},toHSV:function(){var A=this;
var z=A.r;
var u=A.g;
var i=A.b;
var y=Math.min(z,u,i);
var x=Math.max(z,u,i);
var t=x-y;
var C=x;
var w,B;
if(t===0){return new j(0,0,C,this.a);
}if(x!==0){B=t/x;
if(z===x){w=(u-i)/t;
}else{if(u===x){w=2+(i-z)/t;
}else{w=4+(z-u)/t;
}}w*=60;
if(w<0){w+=360;
}}else{B=0;
w=-1;
}return new j(w,B,C,this.a);
},toHSL:function(){var A=this;
var z=A.r;
var u=A.g;
var i=A.b;
var x=Math.max(z,u,i);
var y=Math.min(z,u,i);
var v,B,w=(x+y)/2;
if(x===y){v=B=0;
}else{var t=x-y;
B=w>0.5?t/(2-x-y):t/(x+y);
switch(x){case z:v=(u-i)/t+(u<i?6:0);
break;
case u:v=(i-z)/t+2;
break;
case i:v=(z-u)/t+4;
break;
default:break;
}v*=60;
B*=100;
w*=100;
}return new h(v,B,w,this.a);
},toBytes:function(){return new d(this.r*255,this.g*255,this.b*255,this.a);
}});
var d=p.extend({init:function(u,t,s,i){p.fn.init.call(this,Math.round(u),Math.round(t),Math.round(s),i);
},toRGB:function(){return new p(this.r/255,this.g/255,this.b/255,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toHSL:function(){return this.toRGB().toHSL();
},toHex:function(){return g(this.r,2)+g(this.g,2)+g(this.b,2);
},toBytes:function(){return this;
}});
function g(i,t,r){if(r===void 0){r="0";
}var s=i.toString(16);
while(t>s.length){s=r+s;
}return s;
}var j=b.extend({init:function(r,t,u,i){b.fn.init.call(this);
this.h=r;
this.s=t;
this.v=u;
this.a=i;
},toRGB:function(){var D=this;
var y=D.h;
var E=D.s;
var G=D.v;
var C,x,u;
if(E===0){C=x=u=G;
}else{y/=60;
var z=Math.floor(y);
var w=y-z;
var A=G*(1-E);
var B=G*(1-E*w);
var F=G*(1-E*(1-w));
switch(z){case 0:C=G;
x=F;
u=A;
break;
case 1:C=B;
x=G;
u=A;
break;
case 2:C=A;
x=G;
u=F;
break;
case 3:C=A;
x=B;
u=G;
break;
case 4:C=F;
x=A;
u=G;
break;
default:C=G;
x=A;
u=B;
break;
}}return new p(C,x,u,this.a);
},toHSL:function(){return this.toRGB().toHSL();
},toBytes:function(){return this.toRGB().toBytes();
}});
var h=b.extend({init:function(r,u,t,i){b.fn.init.call(this);
this.h=r;
this.s=u;
this.l=t;
this.a=i;
},toRGB:function(){var z=this;
var u=z.h;
var A=z.s;
var v=z.l;
var y,t,i;
if(A===0){y=t=i=v;
}else{u/=360;
A/=100;
v/=100;
var x=v<0.5?v*(1+A):v+A-v*A;
var w=2*v-x;
y=k(w,x,u+1/3);
t=k(w,x,u);
i=k(w,x,u-1/3);
}return new p(y,t,i,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toBytes:function(){return this.toRGB().toBytes();
}});
function k(i,r,u){var v=u;
if(v<0){v+=1;
}if(v>1){v-=1;
}if(v<1/6){return i+(r-i)*6*v;
}if(v<1/2){return r;
}if(v<2/3){return i+(r-i)*(2/3-v)*6;
}return i;
}function o(u,t){var r,s;
if(u==null||u==="none"){return null;
}if(u instanceof b){return u;
}var i=u.toLowerCase();
if(r=m.exec(i)){if(r[1]==="transparent"){i=new p(1,1,1,0);
}else{i=o(n[r[1]],t);
}i.match=[r[1]];
return i;
}if(r=/^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})\b/i.exec(i)){s=new d(parseInt(r[1],16),parseInt(r[2],16),parseInt(r[3],16),1);
}else{if(r=/^#?([0-9a-f])([0-9a-f])([0-9a-f])\b/i.exec(i)){s=new d(parseInt(r[1]+r[1],16),parseInt(r[2]+r[2],16),parseInt(r[3]+r[3],16),1);
}else{if(r=/^rgb\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)/.exec(i)){s=new d(parseInt(r[1],10),parseInt(r[2],10),parseInt(r[3],10),1);
}else{if(r=/^rgba\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9.]+)\s*\)/.exec(i)){s=new d(parseInt(r[1],10),parseInt(r[2],10),parseInt(r[3],10),parseFloat(r[4]));
}else{if(r=/^rgb\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*\)/.exec(i)){s=new p(parseFloat(r[1])/100,parseFloat(r[2])/100,parseFloat(r[3])/100,1);
}else{if(r=/^rgba\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9.]+)\s*\)/.exec(i)){s=new p(parseFloat(r[1])/100,parseFloat(r[2])/100,parseFloat(r[3])/100,parseFloat(r[4]));
}}}}}}if(s){s.match=r;
}else{if(!t){throw new Error("Cannot parse color: "+i);
}}return s;
}var f=e.extend({init:function(y){var x=this;
if(arguments.length===1){var s=f.formats;
var w=this.resolveColor(y);
for(var t=0;
t<s.length;
t++){var r=s[t].re;
var v=s[t].process;
var u=r.exec(w);
if(u){var i=v(u);
x.r=i[0];
x.g=i[1];
x.b=i[2];
}}}else{this.r=arguments[0];
this.g=arguments[1];
this.b=arguments[2];
}this.r=this.normalizeByte(this.r);
this.g=this.normalizeByte(this.g);
this.b=this.normalizeByte(this.b);
},toHex:function(){var t=this.padDigit;
var u=this.r.toString(16);
var s=this.g.toString(16);
var i=this.b.toString(16);
return"#"+t(u)+t(s)+t(i);
},resolveColor:function(r){var i=r||"black";
if(i.charAt(0)==="#"){i=i.substr(1,6);
}i=i.replace(/ /g,"");
i=i.toLowerCase();
i=f.namedColors[i]||i;
return i;
},normalizeByte:function(i){if(i<0||isNaN(i)){return 0;
}return i>255?255:i;
},padDigit:function(i){return i.length===1?"0"+i:i;
},brightness:function(r){var i=Math.round;
this.r=i(this.normalizeByte(this.r*r));
this.g=i(this.normalizeByte(this.g*r));
this.b=i(this.normalizeByte(this.b*r));
return this;
},percBrightness:function(){return Math.sqrt(0.241*this.r*this.r+0.691*this.g*this.g+0.06800000000000001*this.b*this.b);
}});
f.fromBytes=function(u,t,s,i){return new d(u,t,s,i!=null?i:1);
};
f.fromRGB=function(u,t,s,i){return new p(u,t,s,i!=null?i:1);
};
f.fromHSV=function(r,t,u,i){return new j(r,t,u,i!=null?i:1);
};
f.fromHSL=function(r,u,t,i){return new h(r,u,t,i!=null?i:1);
};
f.formats=[{re:/^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,process:function(i){return[parseInt(i[1],10),parseInt(i[2],10),parseInt(i[3],10)];
}},{re:/^(\w{2})(\w{2})(\w{2})$/,process:function(i){return[parseInt(i[1],16),parseInt(i[2],16),parseInt(i[3],16)];
}},{re:/^(\w{1})(\w{1})(\w{1})$/,process:function(i){return[parseInt(i[1]+i[1],16),parseInt(i[2]+i[2],16),parseInt(i[3]+i[3],16)];
}}];
f.namedColors=n;
kendo.deepExtend(kendo,{parseColor:o,Color:f});
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
