(function(b,a){a("kendo.list",["kendo.data","kendo.popup"],b);
}(function(){var a={id:"list",name:"List",category:"framework",depends:["data","popup"],hidden:true};
(function(b,O){var t=window.kendo,N=t.ui,C=t._outerWidth,B=t._outerHeight,Q=N.Widget,u=t.keys,M=t.support,n=t.htmlEncode,c=t._activeElement,z=t.data.ObservableArray,o="id",g="change",j="k-state-focused",m="k-state-hover",x="k-i-loading",l="k-loading-hidden",A="open",h="close",f="cascade",I="select",J="selected",H="requestStart",G="requestEnd",R="width",i=b.extend,D=b.proxy,p=b.isArray,e=M.browser,q=e.msie,r=q&&e.version<9,E=/"/g,d={ComboBox:"DropDownList",DropDownList:"ComboBox"};
var w=t.ui.DataBoundWidget.extend({init:function(S,V){var W=this,U=W.ns,T;
Q.fn.init.call(W,S,V);
S=W.element;
V=W.options;
W._isSelect=S.is(I);
if(W._isSelect&&W.element[0].length){if(!V.dataSource){V.dataTextField=V.dataTextField||"text";
V.dataValueField=V.dataValueField||"value";
}}W.ul=b('<ul unselectable="on" class="k-list k-reset"/>').attr({tabIndex:-1,"aria-hidden":true});
W.list=b("<div class='k-list-container'/>").append(W.ul).on("mousedown"+U,D(W._listMousedown,W));
T=S.attr(o);
if(T){W.list.attr(o,T+"-list");
W.ul.attr(o,T+"_listbox");
}W._header();
W._noData();
W._footer();
W._accessors();
W._initValue();
},options:{valuePrimitive:false,footerTemplate:"",headerTemplate:"",noDataTemplate:"No data found."},setOptions:function(S){Q.fn.setOptions.call(this,S);
if(S&&S.enable!==O){S.enabled=S.enable;
}this._header();
this._noData();
this._footer();
this._renderFooter();
this._renderNoData();
},focus:function(){this._focused.focus();
},readonly:function(S){this._editable({readonly:S===O?true:S,disable:false});
},enable:function(S){this._editable({readonly:false,disable:!(S=S===O?true:S)});
},_listOptions:function(U){var V=this;
var S=V.options;
var W=S.virtual;
var T=D(V._listBound,V);
W=typeof W==="object"?W:{};
U=b.extend({autoBind:false,selectable:true,dataSource:V.dataSource,click:D(V._click,V),change:D(V._listChange,V),activate:D(V._activateItem,V),deactivate:D(V._deactivateItem,V),dataBinding:function(){V.trigger("dataBinding");
},dataBound:T,height:S.height,dataValueField:S.dataValueField,dataTextField:S.dataTextField,groupTemplate:S.groupTemplate,fixedGroupTemplate:S.fixedGroupTemplate,template:S.template},U,W);
if(!U.template){U.template="#:"+t.expr(U.dataTextField,"data")+"#";
}if(S.$angular){U.$angular=S.$angular;
}return U;
},_initList:function(){var T=this;
var S=T._listOptions({selectedItemChange:D(T._listChange,T)});
if(!T.options.virtual){T.listView=new t.ui.StaticList(T.ul,S);
}else{T.listView=new t.ui.VirtualList(T.ul,S);
}T.listView.bind("listBound",D(T._listBound,T));
T._setListValue();
},_setListValue:function(S){S=S||this.options.value;
if(S!==O){this.listView.value(S).done(D(this._updateSelectionState,this));
}},_updateSelectionState:b.noop,_listMousedown:function(S){if(!this.filterInput||this.filterInput[0]!==S.target){S.preventDefault();
}},_isFilterEnabled:function(){var S=this.options.filter;
return S&&S!=="none";
},_hideClear:function(){var S=this;
if(S._clear){this._clear.addClass(l);
}},_showClear:function(){var S=this;
if(S._clear){this._clear.removeClass(l);
}},_clearValue:function(){this.listView.value([]);
this._clearText();
this._accessor("");
if(this._isFilterEnabled()){this._filter({word:"",open:false});
}this._change();
},_clearText:function(){this.text("");
},_clearFilter:function(){if(!this.options.virtual){this.listView.bound(false);
}this._filterSource();
},_filterSource:function(V,W){var ab=this;
var Y=ab.options;
var S=ab.dataSource;
var U=i({},S.filter()||{});
var aa=V||U.filters&&U.filters.length&&!V;
var Z=F(U,Y.dataTextField);
if((V||Z)&&ab.trigger("filtering",{filter:V})){return;
}var X={filters:[],logic:"and"};
if(s(V)){X.filters.push(V);
}if(s(U)){X.filters.push(U);
}if(ab._cascading){this.listView.setDSFilter(X);
}var T=i({},{page:aa?1:S.page(),pageSize:aa?S.options.pageSize:S.pageSize(),sort:S.sort(),filter:S.filter(),group:S.group(),aggregate:S.aggregate()},{filter:X});
S[W?"read":"query"](S._mergeState(T));
},_angularElement:function(T,S){if(!T){return;
}this.angular(S,function(){return{elements:T};
});
},_noData:function(){var S=b(this.noData);
var T=this.options.noDataTemplate;
this.angular("cleanup",function(){return{elements:S};
});
t.destroy(S);
S.remove();
if(!T){this.noData=null;
return;
}this.noData=b('<div class="k-nodata" style="display:none"><div></div></div>').appendTo(this.list);
this.noDataTemplate=typeof T!=="function"?t.template(T):T;
},_renderNoData:function(){var S=this.noData;
if(!S){return;
}this._angularElement(S,"cleanup");
S.children(":first").html(this.noDataTemplate({instance:this}));
this._angularElement(S,"compile");
},_toggleNoData:function(S){b(this.noData).toggle(S);
},_footer:function(){var S=b(this.footer);
var T=this.options.footerTemplate;
this._angularElement(S,"cleanup");
t.destroy(S);
S.remove();
if(!T){this.footer=null;
return;
}this.footer=b('<div class="k-footer"></div>').appendTo(this.list);
this.footerTemplate=typeof T!=="function"?t.template(T):T;
},_renderFooter:function(){var S=this.footer;
if(!S){return;
}this._angularElement(S,"cleanup");
S.html(this.footerTemplate({instance:this}));
this._angularElement(S,"compile");
},_header:function(){var S=b(this.header);
var U=this.options.headerTemplate;
this._angularElement(S,"cleanup");
t.destroy(S);
S.remove();
if(!U){this.header=null;
return;
}var T=typeof U!=="function"?t.template(U):U;
S=b(T({}));
this.header=S[0]?S:null;
this.list.prepend(S);
this._angularElement(this.header,"compile");
},_allowOpening:function(){return this.options.noDataTemplate||this.dataSource.flatView().length;
},_initValue:function(){var S=this,T=S.options.value;
if(T!==null){S.element.val(T);
}else{T=S._accessor();
S.options.value=T;
}S._old=T;
},_ignoreCase:function(){var U=this,T=U.dataSource.reader.model,S;
if(T&&T.fields){S=T.fields[U.options.dataTextField];
if(S&&S.type&&S.type!=="string"){U.options.ignoreCase=false;
}}},_focus:function(S){return this.listView.focus(S);
},_filter:function(V){var W=this;
var X=W.options;
var U=X.ignoreCase;
var T=X.dataTextField;
var S={value:U?V.word.toLowerCase():V.word,field:T,operator:X.filter,ignoreCase:U};
W._open=V.open;
W._filterSource(S);
},search:function(T){var S=this.options;
T=typeof T==="string"?T:this._inputValue();
clearTimeout(this._typingTimeout);
if(!S.enforceMinLength&&!T.length||T.length>=S.minLength){this._state="filter";
if(!this._isFilterEnabled()){this._searchByWord(T);
}else{this._filter({word:T,open:true});
}}},current:function(S){return this._focus(S);
},items:function(){return this.ul[0].children;
},destroy:function(){var T=this;
var S=T.ns;
Q.fn.destroy.call(T);
T._unbindDataSource();
T.listView.destroy();
T.list.off(S);
T.popup.destroy();
if(T._form){T._form.off("reset",T._resetHandler);
}},dataItem:function(S){var T=this;
if(S===O){return T.listView.selectedDataItems()[0];
}if(typeof S!=="number"){if(T.options.virtual){return T.dataSource.getByUid(b(S).data("uid"));
}S=b(T.items()).index(S);
}return T.dataSource.flatView()[S];
},_activateItem:function(){var S=this.listView.focus();
if(S){this._focused.add(this.filterInput).attr("aria-activedescendant",S.attr("id"));
}},_deactivateItem:function(){this._focused.add(this.filterInput).removeAttr("aria-activedescendant");
},_accessors:function(){var W=this;
var S=W.element;
var U=W.options;
var T=t.getter;
var V=S.attr(t.attr("text-field"));
var X=S.attr(t.attr("value-field"));
if(!U.dataTextField&&V){U.dataTextField=V;
}if(!U.dataValueField&&X){U.dataValueField=X;
}W._text=T(U.dataTextField);
W._value=T(U.dataValueField);
},_aria:function(T){var V=this,U=V.options,S=V._focused.add(V.filterInput);
if(U.suggest!==O){S.attr("aria-autocomplete",U.suggest?"both":"list");
}T=T?T+" "+V.ul[0].id:V.ul[0].id;
S.attr("aria-owns",T);
V.ul.attr("aria-live",!V._isFilterEnabled()?"off":"polite");
},_blur:function(){var S=this;
S._change();
S.close();
},_change:function(){var U=this;
var S=U.selectedIndex;
var T=U.options.value;
var W=U.value();
var V;
if(U._isSelect&&!U.listView.bound()&&T){W=T;
}if(W!==P(U._old,typeof W)){V=true;
}else{if(S!==O&&S!==U._oldIndex){V=true;
}}if(V){U._old=W;
U._oldIndex=S;
if(!U._typing){U.element.trigger(g);
}U.trigger(g);
}U.typing=false;
},_data:function(){return this.dataSource.view();
},_enable:function(){var U=this,T=U.options,S=U.element.is("[disabled]");
if(T.enable!==O){T.enabled=T.enable;
}if(!T.enabled||S){U.enable(false);
}else{U.readonly(U.element.is("[readonly]"));
}},_dataValue:function(S){var T=this._value(S);
if(T===O){T=this._text(S);
}return T;
},_offsetHeight:function(){var S=0;
var T=this.listView.content.prevAll(":visible");
T.each(function(){var U=b(this);
if(U.hasClass("k-list-filter")){S+=B(U.children());
}else{S+=B(U);
}});
return S;
},_height:function(U){var Y=this;
var V=Y.list;
var T=Y.options.height;
var Z=Y.popup.visible();
var W;
var X;
var S;
if(U||Y.options.noDataTemplate){X=V.add(V.parent(".k-animation-container")).show();
if(!V.is(":visible")){X.hide();
return;
}T=Y.listView.content[0].scrollHeight>T?T:"auto";
X.height(T);
if(T!=="auto"){W=Y._offsetHeight();
S=B(b(Y.footer))||0;
T=T-W-S;
}Y.listView.content.height(T);
if(!Z){X.hide();
}}return T;
},_adjustListWidth:function(){var U=this.list,V=U[0].style.width,W=this.wrapper,S,T;
if(!U.data(R)&&V){return;
}S=window.getComputedStyle?window.getComputedStyle(W[0],null):0;
T=parseFloat(S&&S.width)||C(W);
if(S&&e.msie){T+=parseFloat(S.paddingLeft)+parseFloat(S.paddingRight)+parseFloat(S.borderLeftWidth)+parseFloat(S.borderRightWidth);
}if(U.css("box-sizing")!=="border-box"){V=T-(C(U)-U.width());
}else{V=T;
}U.css({fontFamily:W.css("font-family"),width:this.options.autoWidth?"auto":V,minWidth:V}).data(R,V);
return true;
},_openHandler:function(S){this._adjustListWidth();
if(this.trigger(A)){S.preventDefault();
}else{this._focused.attr("aria-expanded",true);
this.ul.attr("aria-hidden",false);
}},_closeHandler:function(S){if(this.trigger(h)){S.preventDefault();
}else{this._focused.attr("aria-expanded",false);
this.ul.attr("aria-hidden",true);
}},_focusItem:function(){var T=this.listView;
var U=!T.focus();
var S=v(T.select());
if(S===O&&this.options.highlightFirst&&U){S=0;
}if(S!==O){T.focus(S);
}else{if(U){T.scrollToIndex(0);
}}},_calculateGroupPadding:function(T){var U=this.ul.children(".k-first:first");
var S=this.listView.content.prev(".k-group-header");
var V=0;
if(S[0]&&S[0].style.display!=="none"){if(T!=="auto"){V=t.support.scrollbar();
}V+=parseFloat(U.css("border-right-width"),10)+parseFloat(U.children(".k-group").css("padding-right"),10);
S.css("padding-right",V);
}},_calculatePopupHeight:function(S){var T=this._height(this.dataSource.flatView().length||S);
this._calculateGroupPadding(T);
},_resizePopup:function(S){if(this.options.virtual){return;
}if(!this.popup.element.is(":visible")){this.popup.one("open",function(T){return D(function(){this._calculatePopupHeight(T);
},this);
}.call(this,S));
}else{this._calculatePopupHeight(S);
}},_popup:function(){var S=this;
S.popup=new N.Popup(S.list,i({},S.options.popup,{anchor:S.wrapper,open:D(S._openHandler,S),close:D(S._closeHandler,S),animation:S.options.animation,isRtl:M.isRtl(S.wrapper)}));
},_makeUnselectable:function(){if(r){this.list.find("*").not(".k-textbox").attr("unselectable","on");
}},_toggleHover:function(S){b(S.currentTarget).toggleClass(m,S.type==="mouseenter");
},_toggle:function(S,T){var U=this;
var V=M.mobileOS&&(M.touch||M.MSPointers||M.pointers);
S=S!==O?S:!U.popup.visible();
if(!T&&!V&&U._focused[0]!==c()){U._prevent=true;
U._focused.focus();
U._prevent=false;
}U[S?A:h]();
},_triggerCascade:function(){var S=this;
if(!S._cascadeTriggered||S._old!==S.value()||S._oldIndex!==S.selectedIndex){S._cascadeTriggered=true;
S.trigger(f,{userTriggered:S._userTriggered});
}},_triggerChange:function(){if(this._valueBeforeCascade!==this.value()){this.trigger(g);
}},_unbindDataSource:function(){var S=this;
S.dataSource.unbind(H,S._requestStartHandler).unbind(G,S._requestEndHandler).unbind("error",S._errorHandler);
},requireValueMapper:function(T,U){var S=(T.value instanceof Array?T.value.length:T.value)||(U instanceof Array?U.length:U);
if(S&&T.virtual&&typeof T.virtual.valueMapper!=="function"){throw new Error("ValueMapper is not provided while the value is being set. See http://docs.telerik.com/kendo-ui/controls/editors/combobox/virtualization#the-valuemapper-function");
}}});
function P(T,S){if(T!==O&&T!==""&&T!==null){if(S==="boolean"){T=Boolean(T);
}else{if(S==="number"){T=Number(T);
}else{if(S==="string"){T=T.toString();
}}}}return T;
}i(w,{inArray:function(U,V){var S,T,W=V.children;
if(!U||U.parentNode!==V){return -1;
}for(S=0,T=W.length;
S<T;
S++){if(U===W[S]){return S;
}}return -1;
},unifyType:P});
t.ui.List=w;
N.Select=w.extend({init:function(S,T){w.fn.init.call(this,S,T);
this._initial=this.element.val();
},setDataSource:function(S){var U=this;
var T;
U.options.dataSource=S;
U._dataSource();
if(U.listView.bound()){U._initialIndex=null;
}U.listView.setDataSource(U.dataSource);
if(U.options.autoBind){U.dataSource.fetch();
}T=U._parentWidget();
if(T){U._cascadeSelect(T);
}},close:function(){this.popup.close();
},select:function(S){var T=this;
if(S===O){return T.selectedIndex;
}else{return T._select(S).done(function(){T._old=T._accessor();
T._oldIndex=T.selectedIndex;
});
}},_accessor:function(T,S){return this[this._isSelect?"_accessorSelect":"_accessorInput"](T,S);
},_accessorInput:function(T){var S=this.element[0];
if(T===O){return S.value;
}else{if(T===null){T="";
}S.value=T;
}},_accessorSelect:function(V,U){var S=this.element[0];
var T;
if(V===O){return k(S).value||"";
}k(S).selected=false;
if(U===O){U=-1;
}T=V!==null&&V!=="";
if(T&&U==-1){this._custom(V);
}else{if(V){S.value=V;
}else{S.selectedIndex=U;
}}},_custom:function(V){var U=this;
var T=U.element;
var S=U._customOption;
if(!S){S=b("<option/>");
U._customOption=S;
T.append(S);
}S.text(V);
S[0].selected=true;
},_hideBusy:function(){var S=this;
clearTimeout(S._busy);
S._arrow.removeClass(x);
S._focused.attr("aria-busy",false);
S._busy=null;
S._showClear();
},_showBusy:function(){var S=this;
S._request=true;
if(S._busy){return;
}S._busy=setTimeout(function(){if(S._arrow){S._focused.attr("aria-busy",true);
S._arrow.addClass(x);
S._hideClear();
}},100);
},_requestEnd:function(){this._request=false;
this._hideBusy();
},_dataSource:function(){var W=this,T=W.element,V=W.options,S=V.dataSource||{},U;
S=b.isArray(S)?{data:S}:S;
if(W._isSelect){U=T[0].selectedIndex;
if(U>-1){V.index=U;
}S.select=T;
S.fields=[{field:V.dataTextField},{field:V.dataValueField}];
}if(W.dataSource){W._unbindDataSource();
}else{W._requestStartHandler=D(W._showBusy,W);
W._requestEndHandler=D(W._requestEnd,W);
W._errorHandler=D(W._hideBusy,W);
}W.dataSource=t.data.DataSource.create(S).bind(H,W._requestStartHandler).bind(G,W._requestEndHandler).bind("error",W._errorHandler);
},_firstItem:function(){this.listView.focusFirst();
},_lastItem:function(){this.listView.focusLast();
},_nextItem:function(){this.listView.focusNext();
},_prevItem:function(){this.listView.focusPrev();
},_move:function(X){var ab=this;
var Z=ab.listView;
var Y=X.keyCode;
var W=Y===u.DOWN;
var U;
var aa;
var T;
if(Y===u.UP||W){if(X.altKey){ab.toggle(W);
}else{if(!Z.bound()){if(!ab._fetch){ab.dataSource.one(g,function(){ab._fetch=false;
ab._move(X);
});
ab._fetch=true;
ab._filterSource();
}X.preventDefault();
return true;
}T=ab._focus();
if(!ab._fetch&&(!T||T.hasClass("k-state-selected"))){if(W){ab._nextItem();
if(!ab._focus()){ab._lastItem();
}}else{ab._prevItem();
if(!ab._focus()){ab._firstItem();
}}}U=Z.dataItemByIndex(Z.getElementIndex(ab._focus()));
if(ab.trigger(I,{dataItem:U,item:ab._focus()})){ab._focus(T);
return;
}ab._select(ab._focus(),true).done(function(){if(!ab.popup.visible()){ab._blur();
}});
}X.preventDefault();
aa=true;
}else{if(Y===u.ENTER||Y===u.TAB){if(ab.popup.visible()){X.preventDefault();
}T=ab._focus();
U=ab.dataItem();
if(!ab.popup.visible()&&(!U||ab.text()!==ab._text(U))){T=null;
}var S=ab.filterInput&&ab.filterInput[0]===c();
if(T){U=Z.dataItemByIndex(Z.getElementIndex(T));
if(ab.trigger(I,{dataItem:U,item:T})){return;
}ab._select(T);
}else{if(ab.input){ab._accessor(ab.input.val());
ab.listView.value(ab.input.val());
}}if(ab._focusElement){ab._focusElement(ab.wrapper);
}if(S&&Y===u.TAB){ab.wrapper.focusout();
}else{ab._blur();
}ab.close();
aa=true;
}else{if(Y===u.ESC){if(ab.popup.visible()){X.preventDefault();
}ab.close();
aa=true;
}else{if(ab.popup.visible()&&(Y===u.PAGEDOWN||Y===u.PAGEUP)){X.preventDefault();
var V=Y===u.PAGEDOWN?1:-1;
Z.scrollWith(V*Z.screenHeight());
aa=true;
}}}}return aa;
},_fetchData:function(){var T=this;
var S=!!T.dataSource.view().length;
if(T._request||T.options.cascadeFrom){return;
}if(!T.listView.bound()&&!T._fetch&&!S){T._fetch=true;
T.dataSource.fetch().done(function(){T._fetch=false;
});
}},_options:function(S,ab,ae){var ad=this,W=ad.element,X=W[0],Z=S.length,ac="",aa,T,U,V,Y=0;
if(ab){ac=ab;
}for(;
Y<Z;
Y++){aa="<option";
T=S[Y];
U=ad._text(T);
V=ad._value(T);
if(V!==O){V+="";
if(V.indexOf('"')!==-1){V=V.replace(E,"&quot;");
}aa+=' value="'+V+'"';
}aa+=">";
if(U!==O){aa+=n(U);
}aa+="</option>";
ac+=aa;
}W.html(ac);
if(ae!==O){X.value=ae;
if(X.value&&!ae){X.selectedIndex=-1;
}}if(X.selectedIndex!==-1){aa=k(X);
if(aa){aa.setAttribute(J,J);
}}},_reset:function(){var V=this,S=V.element,U=S.attr("form"),T=U?b("#"+U):S.closest("form");
if(T[0]){V._resetHandler=function(){setTimeout(function(){V.value(V._initial);
});
};
V._form=T.on("reset",V._resetHandler);
}},_parentWidget:function(){var S=this.options.name;
if(!this.options.cascadeFrom){return;
}var U=b("#"+this.options.cascadeFrom);
var T=U.data("kendo"+S);
if(!T){T=U.data("kendo"+d[S]);
}return T;
},_cascade:function(){var V=this;
var T=V.options;
var S=T.cascadeFrom;
var U;
if(S){U=V._parentWidget();
if(!U){return;
}V._cascadeHandlerProxy=D(V._cascadeHandler,V);
V._cascadeFilterRequests=[];
T.autoBind=false;
U.bind("set",function(){V.one("set",function(W){V._selectedValue=W.value;
});
});
U.first(f,V._cascadeHandlerProxy);
if(U.listView.bound()){V._toggleCascadeOnFocus();
V._cascadeSelect(U);
}else{U.one("dataBound",function(){V._toggleCascadeOnFocus();
});
if(!U.value()){V.enable(false);
}}}},_toggleCascadeOnFocus:function(){var U=this;
var T=U._parentWidget();
var S=q?"blur":"focusout";
T._focused.add(T.filterInput).bind("focus",function(){T.unbind(f,U._cascadeHandlerProxy);
T.first(g,U._cascadeHandlerProxy);
});
T._focused.add(T.filterInput).bind(S,function(){T.unbind(g,U._cascadeHandlerProxy);
T.first(f,U._cascadeHandlerProxy);
});
},_cascadeHandler:function(S){var T=this._parentWidget();
var U=this.value();
this._userTriggered=S.userTriggered;
if(this.listView.bound()){this._clearSelection(T,true);
}this._cascadeSelect(T,U);
},_cascadeChange:function(S){var T=this;
var U=T._accessor()||T._selectedValue;
if(!T._cascadeFilterRequests.length){T._selectedValue=null;
}if(T._userTriggered){T._clearSelection(S,true);
}else{if(U){if(U!==T.listView.value()[0]){T.value(U);
}if(!T.dataSource.view()[0]||T.selectedIndex===-1){T._clearSelection(S,true);
}}else{if(T.dataSource.flatView().length){T.select(T.options.index);
}}}T.enable();
T._triggerCascade();
T._triggerChange();
T._userTriggered=false;
},_cascadeSelect:function(W,Y){var X=this;
var S=W.dataItem();
var U=S?W._value(S):null;
var Z=X.options.cascadeFromField||W.options.dataValueField;
var T;
X._valueBeforeCascade=Y!==O?Y:X.value();
if(U||U===0){T=X.dataSource.filter()||{};
F(T,Z);
var V=function(){var aa=X._cascadeFilterRequests.shift();
if(aa){X.unbind("dataBound",aa);
}aa=X._cascadeFilterRequests[0];
if(aa){X.first("dataBound",aa);
}X._cascadeChange(W);
};
X._cascadeFilterRequests.push(V);
if(X._cascadeFilterRequests.length===1){X.first("dataBound",V);
}X._cascading=true;
X._filterSource({field:Z,operator:"eq",value:U});
X._cascading=false;
}else{X.enable(false);
X._clearSelection(W);
X._triggerCascade();
X._triggerChange();
X._userTriggered=false;
}}});
var K=".StaticList";
var L=t.ui.DataBoundWidget.extend({init:function(S,T){Q.fn.init.call(this,S,T);
this.element.attr("role","listbox").on("click"+K,"li",D(this._click,this)).on("mouseenter"+K,"li",function(){b(this).addClass(m);
}).on("mouseleave"+K,"li",function(){b(this).removeClass(m);
});
this.content=this.element.wrap("<div class='k-list-scroller' unselectable='on'></div>").parent();
this.header=this.content.before('<div class="k-group-header" style="display:none"></div>').prev();
this.bound(false);
this._optionID=t.guid();
this._selectedIndices=[];
this._view=[];
this._dataItems=[];
this._values=[];
var U=this.options.value;
if(U){this._values=b.isArray(U)?U.slice(0):[U];
}this._getter();
this._templates();
this.setDataSource(this.options.dataSource);
this._onScroll=D(function(){var V=this;
clearTimeout(V._scrollId);
V._scrollId=setTimeout(function(){V._renderHeader();
},50);
},this);
},options:{name:"StaticList",dataValueField:null,valuePrimitive:false,selectable:true,template:null,groupTemplate:null,fixedGroupTemplate:null},events:["click",g,"activate","deactivate","dataBinding","dataBound","selectedItemChange"],setDataSource:function(T){var U=this;
var S=T||{};
var V;
S=b.isArray(S)?{data:S}:S;
S=t.data.DataSource.create(S);
if(U.dataSource){U.dataSource.unbind(g,U._refreshHandler);
V=U.value();
U.value([]);
U.bound(false);
U.value(V);
}else{U._refreshHandler=D(U.refresh,U);
}U.setDSFilter(S.filter());
U.dataSource=S.bind(g,U._refreshHandler);
U._fixedHeader();
},skip:function(){return this.dataSource.skip();
},setOptions:function(S){Q.fn.setOptions.call(this,S);
this._getter();
this._templates();
this._render();
},destroy:function(){this.element.off(K);
if(this._refreshHandler){this.dataSource.unbind(g,this._refreshHandler);
}clearTimeout(this._scrollId);
Q.fn.destroy.call(this);
},dataItemByIndex:function(S){return this.dataSource.flatView()[S];
},screenHeight:function(){return this.content[0].clientHeight;
},scrollToIndex:function(S){var T=this.element[0].children[S];
if(T){this.scroll(T);
}},scrollWith:function(S){this.content.scrollTop(this.content.scrollTop()+S);
},scroll:function(W){if(!W){return;
}if(W[0]){W=W[0];
}var T=this.content[0],Y=W.offsetTop,X=W.offsetHeight,V=T.scrollTop,U=T.clientHeight,S=Y+X;
if(V>Y){V=Y;
}else{if(S>V+U){V=S-U;
}}T.scrollTop=V;
},selectedDataItems:function(S){if(S===O){return this._dataItems.slice();
}this._dataItems=S;
this._values=this._getValues(S);
},_getValues:function(S){var T=this._valueGetter;
return b.map(S,function(U){return T(U);
});
},focusNext:function(){var S=this.focus();
if(!S){S=0;
}else{S=S.next();
}this.focus(S);
},focusPrev:function(){var S=this.focus();
if(!S){S=this.element[0].children.length-1;
}else{S=S.prev();
}this.focus(S);
},focusFirst:function(){this.focus(this.element[0].children[0]);
},focusLast:function(){this.focus(v(this.element[0].children));
},focus:function(S){var V=this;
var U=V._optionID;
var T;
if(S===O){return V._current;
}S=v(V._get(S));
S=b(this.element[0].children[S]);
if(V._current){V._current.removeClass(j).removeAttr("aria-selected").removeAttr(o);
V.trigger("deactivate");
}T=!!S[0];
if(T){S.addClass(j);
V.scroll(S);
S.attr("id",U);
}V._current=T?S:null;
V.trigger("activate");
},focusIndex:function(){return this.focus()?this.focus().index():O;
},skipUpdate:function(S){this._skipUpdate=S;
},select:function(V){var ab=this;
var Y=ab.options.selectable;
var aa=Y!=="multiple"&&Y!==false;
var Z=ab._selectedIndices;
var S=[];
var W=[];
var X;
if(V===O){return Z.slice();
}V=ab._get(V);
if(V.length===1&&V[0]===-1){V=[];
}var T=b.Deferred().resolve();
var U=ab.isFiltered();
if(U&&!aa&&ab._deselectFiltered(V)){return T;
}if(aa&&!U&&b.inArray(v(V),Z)!==-1){if(ab._dataItems.length&&ab._view.length){ab._dataItems=[ab._view[Z[0]].item];
}return T;
}X=ab._deselect(V);
W=X.removed;
V=X.indices;
if(V.length){if(aa){V=[v(V)];
}S=ab._select(V);
}if(S.length||W.length){ab._valueComparer=null;
ab.trigger(g,{added:S,removed:W});
}return T;
},removeAt:function(S){this._selectedIndices.splice(S,1);
this._values.splice(S,1);
this._valueComparer=null;
return{position:S,dataItem:this._dataItems.splice(S,1)[0]};
},setValue:function(S){S=b.isArray(S)||S instanceof z?S.slice(0):[S];
this._values=S;
this._valueComparer=null;
},value:function(V){var U=this;
var S=U._valueDeferred;
var T;
if(V===O){return U._values.slice();
}U.setValue(V);
if(!S||S.state()==="resolved"){U._valueDeferred=S=b.Deferred();
}if(U.bound()){T=U._valueIndices(U._values);
if(U.options.selectable==="multiple"){U.select(-1);
}U.select(T);
S.resolve();
}U._skipUpdate=false;
return S;
},items:function(){return this.element.children(".k-item");
},_click:function(S){if(!S.isDefaultPrevented()){if(!this.trigger("click",{item:b(S.currentTarget)})){this.select(S.currentTarget);
}}},_valueExpr:function(X,Y){var W=this;
var U=0;
var S;
var T;
var V=[];
if(!W._valueComparer||W._valueType!==X){W._valueType=X;
for(;
U<Y.length;
U++){V.push(P(Y[U],X));
}S="for (var idx = 0; idx < "+V.length+"; idx++) { if (current === values[idx]) {   return idx; }} return -1;";
T=new Function("current","values",S);
W._valueComparer=function(Z){return T(Z,V);
};
}return W._valueComparer;
},_dataItemPosition:function(S,V){var T=this._valueGetter(S);
var U=this._valueExpr(typeof T,V);
return U(T);
},_getter:function(){this._valueGetter=t.getter(this.options.dataValueField);
},_deselect:function(W){var ad=this;
var S=ad.element[0].children;
var aa=ad.options.selectable;
var ac=ad._selectedIndices;
var T=ad._dataItems;
var ae=ad._values;
var Y=[];
var U=0;
var X;
var V,ab;
var Z=0;
W=W.slice();
if(aa===true||!W.length){for(;
U<ac.length;
U++){b(S[ac[U]]).removeClass("k-state-selected");
Y.push({position:U,dataItem:T[U]});
}ad._values=[];
ad._dataItems=[];
ad._selectedIndices=[];
}else{if(aa==="multiple"){for(;
U<W.length;
U++){V=W[U];
if(!b(S[V]).hasClass("k-state-selected")){continue;
}for(X=0;
X<ac.length;
X++){ab=ac[X];
if(ab===V){b(S[ab]).removeClass("k-state-selected");
Y.push({position:X+Z,dataItem:T.splice(X,1)[0]});
ac.splice(X,1);
W.splice(U,1);
ae.splice(X,1);
Z+=1;
U-=1;
X-=1;
break;
}}}}}return{indices:W,removed:Y};
},_deselectFiltered:function(W){var S=this.element[0].children;
var T,V,X;
var Y=[];
var U=0;
for(;
U<W.length;
U++){V=W[U];
T=this._view[V].item;
X=this._dataItemPosition(T,this._values);
if(X>-1){Y.push(this.removeAt(X));
b(S[V]).removeClass("k-state-selected");
}}if(Y.length){this.trigger(g,{added:[],removed:Y});
return true;
}return false;
},_select:function(Y){var Z=this;
var T=Z.element[0].children;
var U=Z._view;
var V,X;
var S=[];
var W=0;
if(v(Y)!==-1){Z.focus(Y);
}for(;
W<Y.length;
W++){X=Y[W];
V=U[X];
if(X===-1||!V){continue;
}V=V.item;
Z._selectedIndices.push(X);
Z._dataItems.push(V);
Z._values.push(Z._valueGetter(V));
b(T[X]).addClass("k-state-selected").attr("aria-selected",true);
S.push({dataItem:V});
}return S;
},getElementIndex:function(S){return b(S).data("offset-index");
},_get:function(S){if(typeof S==="number"){S=[S];
}else{if(!p(S)){S=this.getElementIndex(S);
S=[S!==O?S:-1];
}}return S;
},_template:function(){var U=this;
var S=U.options;
var T=S.template;
if(!T){T=t.template('<li tabindex="-1" role="option" unselectable="on" class="k-item">${'+t.expr(S.dataTextField,"data")+"}</li>",{useWithBlock:false});
}else{T=t.template(T);
T=function(V){return'<li tabindex="-1" role="option" unselectable="on" class="k-item">'+T(V)+"</li>";
};
}return T;
},_templates:function(){var U;
var T=this.options;
var V={template:T.template,groupTemplate:T.groupTemplate,fixedGroupTemplate:T.fixedGroupTemplate};
for(var S in V){U=V[S];
if(U&&typeof U!=="function"){V[S]=t.template(U);
}}this.templates=V;
},_normalizeIndices:function(T){var U=[];
var S=0;
for(;
S<T.length;
S++){if(T[S]!==O){U.push(T[S]);
}}return U;
},_valueIndices:function(W,V){var S=this._view;
var T=0;
var U;
V=V?V.slice():[];
if(!W.length){return[];
}for(;
T<S.length;
T++){U=this._dataItemPosition(S[T].item,W);
if(U!==-1){V[U]=T;
}}return this._normalizeIndices(V);
},_firstVisibleItem:function(){var T=this.element[0];
var S=this.content[0];
var Y=S.scrollTop;
var W=b(T.children[0]).height();
var X=Math.floor(Y/W)||0;
var V=T.children[X]||T.lastChild;
var U=V.offsetTop<Y;
while(V){if(U){if(V.offsetTop+W>Y||!V.nextSibling){break;
}V=V.nextSibling;
}else{if(V.offsetTop<=Y||!V.previousSibling){break;
}V=V.previousSibling;
}}return this._view[b(V).data("offset-index")];
},_fixedHeader:function(){if(this.isGrouped()&&this.templates.fixedGroupTemplate){this.header.show();
this.content.scroll(this._onScroll);
}else{this.header.hide();
this.content.off("scroll",this._onScroll);
}},_renderHeader:function(){var S=this.templates.fixedGroupTemplate;
if(!S){return;
}var T=this._firstVisibleItem();
if(T){this.header.html(S(T.group));
}},_renderItem:function(S){var U='<li tabindex="-1" role="option" unselectable="on" class="k-item';
var T=S.item;
var V=S.index!==0;
var W=S.selected;
if(V&&S.newGroup){U+=" k-first";
}if(W){U+=" k-state-selected";
}U+='"'+(W?' aria-selected="true"':"")+' data-offset-index="'+S.index+'">';
U+=this.templates.template(T);
if(V&&S.newGroup){U+='<div class="k-group">'+this.templates.groupTemplate(S.group)+"</div>";
}return U+"</li>";
},_render:function(){var V="";
var W=0;
var X=0;
var S;
var T=[];
var ac=this.dataSource.view();
var ab=this.value();
var U,aa,Z;
var Y=this.isGrouped();
if(Y){for(W=0;
W<ac.length;
W++){U=ac[W];
aa=true;
for(Z=0;
Z<U.items.length;
Z++){S={selected:this._selected(U.items[Z],ab),item:U.items[Z],group:U.value,newGroup:aa,index:X};
T[X]=S;
X+=1;
V+=this._renderItem(S);
aa=false;
}}}else{for(W=0;
W<ac.length;
W++){S={selected:this._selected(ac[W],ab),item:ac[W],index:W};
T[W]=S;
V+=this._renderItem(S);
}}this._view=T;
this.element[0].innerHTML=V;
if(Y&&T.length){this._renderHeader();
}},_selected:function(S,U){var T=!this.isFiltered()||this.options.selectable==="multiple";
return T&&this._dataItemPosition(S,U)!==-1;
},setDSFilter:function(S){this._lastDSFilter=i({},S);
},isFiltered:function(){if(!this._lastDSFilter){this.setDSFilter(this.dataSource.filter());
}return !t.data.Query.compareFilters(this.dataSource.filter(),this._lastDSFilter);
},refresh:function(T){var X=this;
var S=T&&T.action;
var W=X.options.skipUpdateOnBind;
var U=S==="itemchange";
var V;
X.trigger("dataBinding");
X._angularItems("cleanup");
X._fixedHeader();
X._render();
X.bound(true);
if(U||S==="remove"){V=y(X._dataItems,T.items);
if(V.changed.length){if(U){X.trigger("selectedItemChange",{items:V.changed});
}else{X.value(X._getValues(V.unchanged));
}}}else{if(X.isFiltered()||X._skipUpdate){X.focus(0);
if(X._skipUpdate){X._skipUpdate=false;
X._selectedIndices=X._valueIndices(X._values,X._selectedIndices);
}}else{if(!W&&(!S||S==="add")){X.value(X._values);
}}}if(X._valueDeferred){X._valueDeferred.resolve();
}X._angularItems("compile");
X.trigger("dataBound");
},bound:function(S){if(S===O){return this._bound;
}this._bound=S;
},isGrouped:function(){return(this.dataSource.group()||[]).length;
}});
N.plugin(L);
function v(S){return S[S.length-1];
}function k(T){var S=T.selectedIndex;
return S>-1?T.options[S]:{};
}function y(Z,X){var W=X.length;
var aa=Z.length;
var T;
var U;
var V,Y;
var S=[];
var ab=[];
if(aa){for(V=0;
V<aa;
V++){T=Z[V];
U=false;
for(Y=0;
Y<W;
Y++){if(T===X[Y]){U=true;
S.push({index:V,item:T});
break;
}}if(!U){ab.push(T);
}}}return{changed:S,unchanged:ab};
}function s(S){if(!S||b.isEmptyObject(S)){return false;
}if(S.filters&&!S.filters.length){return false;
}return true;
}function F(S,T){var U;
var V=false;
if(S.filters){U=b.grep(S.filters,function(W){V=F(W,T);
if(W.filters){return W.filters.length;
}else{return W.field!=T;
}});
if(!V&&S.filters.length!==U.length){V=true;
}S.filters=U;
}return V;
}}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
