(function(b,a){a("kendo.ooxml",["kendo.core"],b);
}(function(){var a={id:"ooxml",name:"XLSX generation",category:"framework",advanced:true,depends:["core"]};
(function(b,u){var z='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';
var k=u.template('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:creator>${creator}</dc:creator><cp:lastModifiedBy>${lastModifiedBy}</cp:lastModifiedBy><dcterms:created xsi:type="dcterms:W3CDTF">${created}</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">${modified}</dcterms:modified></cp:coreProperties>');
var d=u.template('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>Microsoft Excel</Application><DocSecurity>0</DocSecurity><ScaleCrop>false</ScaleCrop><HeadingPairs><vt:vector size="2" baseType="variant"><vt:variant><vt:lpstr>Worksheets</vt:lpstr></vt:variant><vt:variant><vt:i4>${sheets.length}</vt:i4></vt:variant></vt:vector></HeadingPairs><TitlesOfParts><vt:vector size="${sheets.length}" baseType="lpstr"># for (var idx = 0; idx < sheets.length; idx++) { ## if (sheets[idx].options.title) { #<vt:lpstr>${sheets[idx].options.title}</vt:lpstr># } else { #<vt:lpstr>Sheet${idx+1}</vt:lpstr># } ## } #</vt:vector></TitlesOfParts><LinksUpToDate>false</LinksUpToDate><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged><AppVersion>14.0300</AppVersion></Properties>');
var i=u.template('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" /><Default Extension="xml" ContentType="application/xml" /><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml" /><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/># for (var idx = 1; idx <= count; idx++) { #<Override PartName="/xl/worksheets/sheet${idx}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml" /># } #<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml" /><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml" /></Types>');
var O=u.template('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><fileVersion appName="xl" lastEdited="5" lowestEdited="5" rupBuild="9303" /><workbookPr defaultThemeVersion="124226" /><bookViews><workbookView xWindow="240" yWindow="45" windowWidth="18195" windowHeight="7995" /></bookViews><sheets># for (var idx = 0; idx < sheets.length; idx++) { ## var options = sheets[idx].options; ## var name = options.name || options.title ## if (name) { #<sheet name="${name}" sheetId="${idx+1}" r:id="rId${idx+1}" /># } else { #<sheet name="Sheet${idx+1}" sheetId="${idx+1}" r:id="rId${idx+1}" /># } ## } #</sheets># if (filterNames.length || userNames.length) { #<definedNames> # for (var di = 0; di < filterNames.length; di++) { #<definedName name="_xlnm._FilterDatabase" hidden="1" localSheetId="${filterNames[di].localSheetId}">${filterNames[di].name}!$${filterNames[di].from}:$${filterNames[di].to}</definedName> # } # # for (var i = 0; i < userNames.length; ++i) { #<definedName name="${userNames[i].name}" hidden="${userNames[i].hidden ? 1 : 0}" # if (userNames[i].localSheetId != null) { # localSheetId="${userNames[i].localSheetId}" # } #>${userNames[i].value}</definedName> # } #</definedNames># } #<calcPr fullCalcOnLoad="1" calcId="145621" /></workbook>');
var R=u.template('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" mc:Ignorable="x14ac"><dimension ref="A1" /><sheetViews><sheetView #if(index==0) {# tabSelected="1" #}# workbookViewId="0" #if (showGridLines === false) {# showGridLines="0" #}#># if (frozenRows || frozenColumns) { #<pane state="frozen"# if (frozenColumns) { # xSplit="${frozenColumns}"# } ## if (frozenRows) { # ySplit="${frozenRows}"# } # topLeftCell="${String.fromCharCode(65 + (frozenColumns || 0))}${(frozenRows || 0)+1}"/># } #</sheetView></sheetViews><sheetFormatPr x14ac:dyDescent="0.25" defaultRowHeight="#= defaults.rowHeight ? defaults.rowHeight * 0.75 : 15 #" # if (defaults.columnWidth) { # defaultColWidth="#= kendo.ooxml.toWidth(defaults.columnWidth) #" # } # /># if (defaultCellStyleId != null || (columns && columns.length > 0)) { #<cols># if (!columns || !columns.length) { #<col min="1" max="16384" style="${defaultCellStyleId}" # if (defaults.columnWidth) { # width="#= kendo.ooxml.toWidth(defaults.columnWidth) #" # } # /># } ## for (var ci = 0; ci < columns.length; ci++) { ## var column = columns[ci]; ## var columnIndex = typeof column.index === "number" ? column.index + 1 : (ci + 1); ## if (column.width === 0) { #<col #if(defaultCellStyleId!=null){# style="${defaultCellStyleId}" #}#min="${columnIndex}" max="${columnIndex}" hidden="1" customWidth="1" /># } else if (column.width) { #<col #if(defaultCellStyleId!=null){# style="${defaultCellStyleId}" #}#min="${columnIndex}" max="${columnIndex}" customWidth="1"# if (column.autoWidth) { # width="${((column.width*7+5)/7*256)/256}" bestFit="1"# } else { # width="#= kendo.ooxml.toWidth(column.width) #" # } #/># } ## } #</cols># } #<sheetData># for (var ri = 0; ri < data.length; ri++) { ## var row = data[ri]; ## var rowIndex = typeof row.index === "number" ? row.index + 1 : (ri + 1); #<row r="${rowIndex}" x14ac:dyDescent="0.25" # if (row.height === 0) { # hidden="1" # }   else if (row.height) { # ht="#= kendo.ooxml.toHeight(row.height) #" customHeight="1" # } # ># for (var ci = 0; ci < row.data.length; ci++) { ## var cell = row.data[ci];#<c r="#=cell.ref#"# if (cell.style) { # s="#=cell.style#" # } ## if (cell.type) { # t="#=cell.type#"# } #># if (cell.formula != null) { #<f>${cell.formula}</f># } ## if (cell.value != null) { #<v>${cell.value}</v># } #</c># } #</row># } #</sheetData># if (autoFilter) { #<autoFilter ref="${autoFilter.from}:${autoFilter.to}"/># } else if (filter) { ##= kendo.ooxml.spreadsheetFilters(filter) ## } ## if (mergeCells.length) { #<mergeCells count="${mergeCells.length}"># for (var ci = 0; ci < mergeCells.length; ci++) { #<mergeCell ref="${mergeCells[ci]}"/># } #</mergeCells># } ## if (validations.length) { #<dataValidations># for (var vi = 0; vi < validations.length; vi++) { ## var val = validations[vi]; #<dataValidation sqref="#= val.sqref.join(" ") #" showErrorMessage="#= val.showErrorMessage #" type="#= val.type #"# if (val.type != "list") {# operator="#= val.operator #" # } # allowBlank="#= val.allowBlank #" showDropDown="#= val.showDropDown #"# if (val.error) {# error="#= val.error #" # } ## if (val.errorTitle) {# errorTitle="#= val.errorTitle #" # } #># if (val.formula1) { #<formula1>#= val.formula1 #</formula1># } ## if (val.formula2) { #<formula2>#= val.formula2 #</formula2># } #</dataValidation># } #</dataValidations># } ## if (hyperlinks.length) { #<hyperlinks># for (var hi = 0; hi < hyperlinks.length; hi++) { #<hyperlink ref="${hyperlinks[hi].ref}" r:id="rId${hi}"/># } #</hyperlinks># } #<pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3" /></worksheet>');
var P=u.template('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"># for (var idx = 1; idx <= count; idx++) { #<Relationship Id="rId${idx}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${idx}.xml" /># } #<Relationship Id="rId${count+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml" /><Relationship Id="rId${count+2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml" /></Relationships>');
var S=u.template('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"># for (var i = 0; i < hyperlinks.length; i++) { #<Relationship Id="rId${i}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="${hyperlinks[i].target}" TargetMode="External" /># } #</Relationships>');
var A=u.template('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${count}" uniqueCount="${uniqueCount}"># for (var index in indexes) { #<si><t>${index.substring(1)}</t></si># } #</sst>');
var K=u.template('<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x14ac" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac"><numFmts count="${formats.length}"># for (var fi = 0; fi < formats.length; fi++) { ## var format = formats[fi]; #<numFmt formatCode="${format.format}" numFmtId="${165+fi}" /># } #</numFmts><fonts count="${fonts.length+1}" x14ac:knownFonts="1"><font><sz val="11" /><color theme="1" /><name val="Calibri" /><family val="2" /><scheme val="minor" /></font># for (var fi = 0; fi < fonts.length; fi++) { ## var font = fonts[fi]; #<font># if (font.fontSize) { #<sz val="${font.fontSize}" /># } else { #<sz val="11" /># } ## if (font.bold) { #<b/># } ## if (font.italic) { #<i/># } ## if (font.underline) { #<u/># } ## if (font.color) { #<color rgb="${font.color}" /># } else { #<color theme="1" /># } ## if (font.fontFamily) { #<name val="${font.fontFamily}" /><family val="2" /># } else { #<name val="Calibri" /><family val="2" /><scheme val="minor" /># } #</font># } #</fonts><fills count="${fills.length+2}"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill># for (var fi = 0; fi < fills.length; fi++) { ## var fill = fills[fi]; ## if (fill.background) { #<fill><patternFill patternType="solid"><fgColor rgb="${fill.background}"/></patternFill></fill># } ## } #</fills><borders count="${borders.length+1}"><border><left/><right/><top/><bottom/><diagonal/></border># for (var bi = 0; bi < borders.length; bi++) { ##= kendo.ooxml.borderTemplate(borders[bi]) ## } #</borders><cellStyleXfs count="1"><xf borderId="0" fillId="0" fontId="0" /></cellStyleXfs><cellXfs count="${styles.length+1}"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/># for (var si = 0; si < styles.length; si++) { ## var style = styles[si]; #<xf xfId="0"# if (style.fontId) { # fontId="${style.fontId}" applyFont="1"# } ## if (style.fillId) { # fillId="${style.fillId}" applyFill="1"# } ## if (style.numFmtId) { # numFmtId="${style.numFmtId}" applyNumberFormat="1"# } ## if (style.textAlign || style.verticalAlign || style.wrap) { # applyAlignment="1"# } ## if (style.borderId) { # borderId="${style.borderId}" applyBorder="1"# } #># if (style.textAlign || style.verticalAlign || style.wrap) { #<alignment# if (style.textAlign) { # horizontal="${style.textAlign}"# } ## if (style.verticalAlign) { # vertical="${style.verticalAlign}"# } ## if (style.wrap) { # wrapText="1"# } #/># } #</xf># } #</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><dxfs count="0" /><tableStyles count="0" defaultTableStyle="TableStyleMedium2" defaultPivotStyle="PivotStyleMedium9" /></styleSheet>');
function x(T){var U=Math.floor(T/26)-1;
return(U>=0?x(U):"")+String.fromCharCode(65+T%26);
}function y(U,T){return x(T)+(U+1);
}function c(U,T){return x(T)+"$"+(U+1);
}function p(U){var T=U.frozenRows||(U.freezePane||{}).rowSplit||1;
return T-1;
}function M(T){return(T/7*100+0.5)/100;
}function L(T){return T*0.75;
}function J(T){return(T+"").replace(/[\x00-\x08]/g,"").replace(/\n/g,"\r\n");
}var l=new Date(1900,0,0);
var Q=u.Class.extend({init:function(U,V,W,T){this.options=U;
this._strings=V;
this._styles=W;
this._borders=T;
this._validations={};
},relsToXML:function(){var T=this.options.hyperlinks||[];
if(!T.length){return"";
}return S({hyperlinks:T});
},toXML:function(Z){var aa=this.options.mergedCells||[];
var ab=this.options.rows||[];
var U=r(ab,aa);
this._readCells(U);
var T=this.options.filter;
var W;
if(T&&typeof T.from==="number"&&typeof T.to==="number"){T={from:y(p(this.options),T.from),to:y(p(this.options),T.to)};
}else{if(T&&T.ref&&T.columns){W=T;
T=null;
}}var ac=[];
for(var Y in this._validations){if(Object.prototype.hasOwnProperty.call(this._validations,Y)){ac.push(this._validations[Y]);
}}var V=null;
if(this.options.defaultCellStyle){V=this._lookupStyle(this.options.defaultCellStyle);
}var X=this.options.freezePane||{};
return R({frozenColumns:this.options.frozenColumns||X.colSplit,frozenRows:this.options.frozenRows||X.rowSplit,columns:this.options.columns,defaults:this.options.defaults||{},data:U,index:Z,mergeCells:aa,autoFilter:T,filter:W,showGridLines:this.options.showGridLines,hyperlinks:this.options.hyperlinks||[],validations:ac,defaultCellStyleId:V});
},_lookupString:function(V){var U="$"+V;
var T=this._strings.indexes[U];
if(T!==undefined){V=T;
}else{V=this._strings.indexes[U]=this._strings.uniqueCount;
this._strings.uniqueCount++;
}this._strings.count++;
return V;
},_lookupStyle:function(V){var U=u.stringify(V);
if(U=="{}"){return 0;
}var T=b.inArray(U,this._styles);
if(T<0){T=this._styles.push(U)-1;
}return T+1;
},_lookupBorder:function(T){var V=u.stringify(T);
if(V=="{}"){return;
}var U=b.inArray(V,this._borders);
if(U<0){U=this._borders.push(V)-1;
}return U+1;
},_readCells:function(Y){for(var V=0;
V<Y.length;
V++){var X=Y[V];
var U=X.cells;
X.data=[];
for(var W=0;
W<U.length;
W++){var T=this._cell(U[W],X.index,W);
if(T){X.data.push(T);
}}}},_cell:function(Y,ac,U){if(!Y||Y===n){return null;
}var af=Y.value;
var T={};
if(Y.borderLeft){T.left=Y.borderLeft;
}if(Y.borderRight){T.right=Y.borderRight;
}if(Y.borderTop){T.top=Y.borderTop;
}if(Y.borderBottom){T.bottom=Y.borderBottom;
}T=this._lookupBorder(T);
var Z=this.options.defaultCellStyle||{};
var ad={borderId:T};
(function(ag){ag("color");
ag("background");
ag("bold");
ag("italic");
ag("underline");
if(!ag("fontFamily")){ag("fontName","fontFamily");
}ag("fontSize");
ag("format");
if(!ag("textAlign")){ag("hAlign","textAlign");
}if(!ag("verticalAlign")){ag("vAlign","verticalAlign");
}ag("wrap");
}(function(ag,ah){var ai=Y[ag];
if(ai===undefined){ai=Z[ag];
}if(ai!==undefined){ad[ah||ag]=ai;
return true;
}}));
var X=this.options.columns||[];
var W=X[U];
var ae=typeof af;
if(W&&W.autoWidth){var aa=af;
if(ae==="number"){aa=u.toString(af,Y.format);
}W.width=Math.max(W.width||0,(aa+"").length);
}if(ae==="string"){af=J(af);
af=this._lookupString(af);
ae="s";
}else{if(ae==="number"){ae="n";
}else{if(ae==="boolean"){ae="b";
af=+af;
}else{if(af&&af.getTime){ae=null;
var ab=(af.getTimezoneOffset()-l.getTimezoneOffset())*u.date.MS_PER_MINUTE;
af=(af-l-ab)/u.date.MS_PER_DAY+1;
if(!ad.format){ad.format="mm-dd-yy";
}}else{ae=null;
af=null;
}}}}ad=this._lookupStyle(ad);
var V=y(ac,U);
if(Y.validation){this._addValidation(Y.validation,V);
}return{value:af,formula:Y.formula,type:ae,style:ad,ref:V};
},_addValidation:function(W,U){var V={showErrorMessage:W.type=="reject"?1:0,formula1:W.from,formula2:W.to,type:w[W.dataType]||W.dataType,operator:v[W.comparerType]||W.comparerType,allowBlank:W.allowNulls?1:0,showDropDown:W.showButton?0:1,error:W.messageTemplate,errorTitle:W.titleTemplate};
var T=JSON.stringify(V);
if(!this._validations[T]){this._validations[T]=V;
V.sqref=[];
}this._validations[T].sqref.push(U);
}});
var v={greaterThanOrEqualTo:"greaterThanOrEqual",lessThanOrEqualTo:"lessThanOrEqual"};
var w={number:"decimal"};
var m={General:0,"0":1,"0.00":2,"#,##0":3,"#,##0.00":4,"0%":9,"0.00%":10,"0.00E+00":11,"# ?/?":12,"# ??/??":13,"mm-dd-yy":14,"d-mmm-yy":15,"d-mmm":16,"mmm-yy":17,"h:mm AM/PM":18,"h:mm:ss AM/PM":19,"h:mm":20,"h:mm:ss":21,"m/d/yy h:mm":22,"#,##0 ;(#,##0)":37,"#,##0 ;[Red](#,##0)":38,"#,##0.00;(#,##0.00)":39,"#,##0.00;[Red](#,##0.00)":40,"mm:ss":45,"[h]:mm:ss":46,"mmss.0":47,"##0.0E+0":48,"@":49,"[$-404]e/m/d":27,"m/d/yy":30,t0:59,"t0.00":60,"t#,##0":61,"t#,##0.00":62,"t0%":67,"t0.00%":68,"t# ?/?":69,"t# ??/??":70};
function j(T){if(T.length<6){T=T.replace(/(\w)/g,function(U,V){return V+V;
});
}T=T.substring(1).toUpperCase();
if(T.length<8){T="FF"+T;
}return T;
}var N=u.Class.extend({init:function(T){this.options=T||{};
this._strings={indexes:{},count:0,uniqueCount:0};
this._styles=[];
this._borders=[];
this._sheets=b.map(this.options.sheets||[],b.proxy(function(U){U.defaults=this.options;
return new Q(U,this._strings,this._styles,this._borders);
},this));
},toDataURL:function(){if(typeof JSZip==="undefined"){throw new Error("JSZip not found. Check http://docs.telerik.com/kendo-ui/framework/excel/introduction#requirements for more details.");
}var al=new JSZip();
var U=al.folder("docProps");
U.file("core.xml",k({creator:this.options.creator||"Kendo UI",lastModifiedBy:this.options.creator||"Kendo UI",created:this.options.date||new Date().toJSON(),modified:this.options.date||new Date().toJSON()}));
var ad=this._sheets.length;
U.file("app.xml",d({sheets:this._sheets}));
var aa=al.folder("_rels");
aa.file(".rels",z);
var aj=al.folder("xl");
var ak=aj.folder("_rels");
ak.file("workbook.xml.rels",P({count:ad}));
var ae={};
aj.file("workbook.xml",O({sheets:this._sheets,filterNames:b.map(this._sheets,function(ap,an){var ao=ap.options;
var aq=ao.name||ao.title||"Sheet"+(an+1);
ae[aq.toLowerCase()]=an;
var am=ao.filter;
if(am&&typeof am.from!=="undefined"&&typeof am.to!=="undefined"){return{localSheetId:an,name:aq,from:c(p(ao),am.from),to:c(p(ao),am.to)};
}}),userNames:b.map(this.options.names||[],function(am){return{name:am.localName,localSheetId:am.sheet?ae[am.sheet.toLowerCase()]:null,value:am.value,hidden:am.hidden};
})}));
var ai=aj.folder("worksheets");
var ag=ai.folder("_rels");
for(var Z=0;
Z<ad;
Z++){var ac=this._sheets[Z];
var af=u.format("sheet{0}.xml",Z+1);
var ab=ac.relsToXML();
if(ab){ag.file(af+".rels",ab);
}ai.file(af,ac.toXML(Z));
}var T=b.map(this._borders,b.parseJSON);
var ah=b.map(this._styles,b.parseJSON);
var Y=function(am){return am.underline||am.bold||am.italic||am.color||am.fontFamily||am.fontSize;
};
var W=b.map(ah,function(am){if(am.color){am.color=j(am.color);
}if(Y(am)){return am;
}});
var X=b.map(ah,function(am){if(am.format&&m[am.format]===undefined){return am;
}});
var V=b.map(ah,function(am){if(am.background){am.background=j(am.background);
return am;
}});
aj.file("styles.xml",K({fonts:W,fills:V,formats:X,borders:T,styles:b.map(ah,function(an){var am={};
if(Y(an)){am.fontId=b.inArray(an,W)+1;
}if(an.background){am.fillId=b.inArray(an,V)+2;
}am.textAlign=an.textAlign;
am.verticalAlign=an.verticalAlign;
am.wrap=an.wrap;
am.borderId=an.borderId;
if(an.format){if(m[an.format]!==undefined){am.numFmtId=m[an.format];
}else{am.numFmtId=165+b.inArray(an,X);
}}return am;
})}));
aj.file("sharedStrings.xml",A(this._strings));
al.file("[Content_Types].xml",i({count:ad}));
return"data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,"+al.generate({compression:"DEFLATE"});
}});
function g(U){var T="thin";
if(U===2){T="medium";
}else{if(U===3){T="thick";
}}return T;
}function f(T,V){var U="";
if(V){U+="<"+T+' style="'+g(V.size)+'">';
if(V.color){U+='<color rgb="'+j(V.color)+'"/>';
}U+="</"+T+">";
}return U;
}function h(T){return"<border>"+f("left",T.left)+f("right",T.right)+f("top",T.top)+f("bottom",T.bottom)+"</border>";
}var n={};
function r(X,V){var W=[];
var Y=[];
q(X,function(ac,ab){var aa={_source:ac,index:ab,height:ac.height,cells:[]};
W.push(aa);
Y[ab]=aa;
});
var Z=B(W).slice(0);
var T={rowData:W,rowsByIndex:Y,mergedCells:V};
for(var U=0;
U<Z.length;
U++){o(Z[U],T);
delete Z[U]._source;
}return B(W);
}function q(X,T){for(var U=0;
U<X.length;
U++){var W=X[U];
if(!W){continue;
}var V=W.index;
if(typeof V!=="number"){V=U;
}T(W,V);
}}function B(T){return T.sort(function(U,V){return U.index-V.index;
});
}function o(Z,Y){var ad=Z._source;
var ae=Z.index;
var W=ad.cells;
var U=Z.cells;
if(!W){return;
}for(var aa=0;
aa<W.length;
aa++){var T=W[aa]||n;
var af=T.rowSpan||1;
var X=T.colSpan||1;
var V=s(U,T);
C(T,U,V,X);
if(af>1||X>1){Y.mergedCells.push(y(ae,V)+":"+y(ae+af-1,V+X-1));
}if(af>1){for(var ac=ae+1;
ac<ae+af;
ac++){var ab=Y.rowsByIndex[ac];
if(!ab){ab=Y.rowsByIndex[ac]={index:ac,cells:[]};
Y.rowData.push(ab);
}C(T,ab.cells,V-1,X+1);
}}}}function s(U,T){var V;
if(typeof T.index==="number"){V=T.index;
t(U,T,T.index);
}else{V=e(U,T);
}return V;
}function t(U,T,V){U[V]=T;
}function e(U,T){var W=U.length;
for(var V=0;
V<U.length+1;
V++){if(!U[V]){U[V]=T;
W=V;
break;
}}return W;
}function C(T,W,X,U){for(var V=1;
V<U;
V++){var Y={borderTop:T.borderTop,borderRight:T.borderRight,borderBottom:T.borderBottom,borderLeft:T.borderLeft};
t(W,Y,X+V);
}}var F=u.template('<autoFilter ref="${ref}"># for (var i = 0; i < columns.length; ++i) { ## var col = columns[i]; #<filterColumn colId="${col.index}">#= generators[col.filter](col) #</filterColumn># } #</autoFilter>');
var D=u.template('<customFilters# if (logic == "and") {# and="1"# } #># for (var i = 0; i < criteria.length; ++i) { ## var f = criteria[i]; ## var op = kendo.ooxml.spreadsheetFilters.customOperator(f); ## var val = kendo.ooxml.spreadsheetFilters.customValue(f); #<customFilter# if (op) {# operator="${op}"#}# val="${val}"/># } #</customFilters>');
var E=u.template('<dynamicFilter type="${kendo.ooxml.spreadsheetFilters.dynamicFilterType(type)}" />');
var G=u.template('<top10 percent="#= /percent$/i.test(type) ? 1 : 0 #" top="#= /^top/i.test(type) ? 1 : 0 #"  val="#: value #" />');
var H=u.template('<filters# if (blanks) {# blank="1"#}#># for (var i = 0; i < values.length; ++i) { #<filter val="${values[i]}" /># } #</filters>');
function I(T){return F({ref:T.ref,columns:T.columns,generators:{custom:D,dynamic:E,top:G,value:H}});
}I.customOperator=function(T){return{eq:"equal",gt:"greaterThan",gte:"greaterThanOrEqual",lt:"lessThan",lte:"lessThanOrEqual",ne:"notEqual",doesnotstartwith:"notEqual",doesnotendwith:"notEqual",doesnotcontain:"notEqual",doesnotmatch:"notEqual"}[T.operator.toLowerCase()];
};
I.customValue=function(U){function T(V){return V.replace(/([*?])/g,"~$1");
}switch(U.operator.toLowerCase()){case"startswith":case"doesnotstartwith":return T(U.value)+"*";
case"endswith":case"doesnotendwith":return"*"+T(U.value);
case"contains":case"doesnotcontain":return"*"+T(U.value)+"*";
}return U.value;
};
I.dynamicFilterType=function(T){return{quarter1:"Q1",quarter2:"Q2",quarter3:"Q3",quarter4:"Q4",january:"M1",february:"M2",march:"M3",april:"M4",may:"M5",june:"M6",july:"M7",august:"M8",september:"M9",october:"M10",november:"M11",december:"M12"}[T.toLowerCase()]||T;
};
u.ooxml={Workbook:N,Worksheet:Q,toWidth:M,toHeight:L,borderTemplate:h,spreadsheetFilters:I};
}(kendo.jQuery,kendo));
return kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
