(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(j){this._size=j;
this._length=0;
this._map={};
},put:function(k,m){var l=this._map;
var j={key:k,value:m};
l[k]=j;
if(!this._head){this._head=this._tail=j;
}else{this._tail.newer=j;
j.older=this._tail;
this._tail=j;
}if(this._length>=this._size){l[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(k){var j=this._map[k];
if(j){if(j===this._head&&j!==this._tail){this._head=j.newer;
this._head.older=null;
}if(j!==this._tail){if(j.older){j.older.newer=j.newer;
j.newer.older=j.older;
}j.older=this._tail;
j.newer=null;
this._tail.newer=j;
this._tail=j;
}return j.value;
}}});
function g(k){var l=[];
for(var j in k){l.push(j+k[j]);
}return l.sort().join("");
}function d(l){var j=2166136261;
for(var k=0;
k<l.length;
++k){j+=(j<<1)+(j<<4)+(j<<7)+(j<<8)+(j<<24);
j^=l.charCodeAt(k);
}return j>>>0;
}function i(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;";
}var h=kendo.Class.extend({init:function(j){this._cache=new e(1000);
this.options=a.extend({},b,j);
},measure:function(s,q,k){if(!s){return i();
}var r=g(q);
var m=d(s+r);
var l=this._cache.get(m);
if(l){return l;
}var p=i();
var o=k||c;
var j=this._baselineMarker().cloneNode(false);
for(var n in q){var t=q[n];
if(typeof t!=="undefined"){o.style[n]=t;
}}o.textContent=s;
o.appendChild(j);
document.body.appendChild(o);
if(String(s).length){p.width=o.offsetWidth-this.options.baselineMarkerSize;
p.height=o.offsetHeight;
p.baseline=j.offsetTop+this.options.baselineMarkerSize;
}if(p.width>0&&p.height>0){this._cache.put(m,p);
}o.parentNode.removeChild(o);
return p;
},_baselineMarker:function(){var j=document.createElement("div");
j.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return j;
}});
h.current=new h();
function f(l,k,j){return h.current.measure(l,k,j);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:h,measureText:f,objectKey:g,hashKey:d});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("pdf/core",["kendo.core","kendo.color","kendo.drawing"],b);
}(function(){(function(V){window.kendo.pdf=window.kendo.pdf||{};
var a3=V.support;
var a4=a3.browser;
var x=V.drawing;
var be=x.util;
var W=V.geometry;
var K=typeof Uint8Array!=="undefined";
var c=function(){var bh="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
return{decode:function(bt){var bq=bt.replace(/[^A-Za-z0-9\+\/\=]/g,""),bp=0,br=bq.length,bs=[];
while(bp<br){var bl=bh.indexOf(bq.charAt(bp++));
var bm=bh.indexOf(bq.charAt(bp++));
var bn=bh.indexOf(bq.charAt(bp++));
var bo=bh.indexOf(bq.charAt(bp++));
var bi=bl<<2|bm>>>4;
var bj=(bm&15)<<4|bn>>>2;
var bk=(bn&3)<<6|bo;
bs.push(bi);
if(bn!=64){bs.push(bj);
}if(bo!=64){bs.push(bk);
}}return bs;
},encode:function(bi){var bq=0,br=bi.length;
var bs="";
while(bq<br){var bj=bi[bq++];
var bk=bi[bq++];
var bl=bi[bq++];
var bm=bj>>>2;
var bn=(bj&3)<<4|bk>>>4;
var bo=(bk&15)<<2|bl>>>6;
var bp=bl&63;
if(bq-br==2){bo=bp=64;
}else{if(bq-br==1){bp=64;
}}bs+=bh.charAt(bm)+bh.charAt(bn)+bh.charAt(bo)+bh.charAt(bp);
}return bs;
}};
}();
function d(bh){var bm=0,bl=0;
if(bh==null){bh=K?new Uint8Array(256):[];
}else{bl=bh.length;
}var bi=K?function(bI){if(bI>=bh.length){var bJ=new Uint8Array(Math.max(bI+256,bh.length*2));
bJ.set(bh,0);
bh=bJ;
}}:function(){};
var bk=K?function(){return new Uint8Array(bh.buffer,0,bl);
}:function(){return bh;
};
var bz=K?function(bI){if(typeof bI=="string"){return bH(bI);
}var bJ=bI.length;
bi(bm+bJ);
bh.set(bI,bm);
bm+=bJ;
if(bm>bl){bl=bm;
}}:function(bI){if(typeof bI=="string"){return bH(bI);
}for(var bJ=0;
bJ<bI.length;
++bJ){bA(bI[bJ]);
}};
var bw=K?function(bJ,bI){if(bh.buffer.slice){return new Uint8Array(bh.buffer.slice(bJ,bJ+bI));
}else{var bK=new Uint8Array(bI);
bK.set(new Uint8Array(bh.buffer,bJ,bI));
return bK;
}}:function(bJ,bI){return bh.slice(bJ,bJ+bI);
};
function bj(){return bm>=bl;
}function bo(){return bm<bl?bh[bm++]:0;
}function bA(bI){bi(bm);
bh[bm++]=bI&255;
if(bm>bl){bl=bm;
}}function bt(){return bo()<<8|bo();
}function bF(bI){bA(bI>>8);
bA(bI);
}function bu(){var bI=bt();
return bI>=32768?bI-65536:bI;
}function bG(bI){bF(bI<0?bI+65536:bI);
}function br(){return bt()*65536+bt();
}function bD(bI){bF(bI>>>16&65535);
bF(bI&65535);
}function bs(){var bI=br();
return bI>=2147483648?bI-4294967296:bI;
}function bE(bI){bD(bI<0?bI+4294967296:bI);
}function bp(){return br()/65536;
}function bB(bI){bD(Math.round(bI*65536));
}function bq(){return bs()/65536;
}function bC(bI){bE(Math.round(bI*65536));
}function bn(bI){return by(bI,bo);
}function bv(bI){return String.fromCharCode.apply(String,bn(bI));
}function bH(bJ){for(var bI=0;
bI<bJ.length;
++bI){bA(bJ.charCodeAt(bI));
}}function by(bJ,bK){for(var bL=new Array(bJ),bI=0;
bI<bJ;
++bI){bL[bI]=bK();
}return bL;
}var bx={eof:bj,readByte:bo,writeByte:bA,readShort:bt,writeShort:bF,readLong:br,writeLong:bD,readFixed:bp,writeFixed:bB,readShort_:bu,writeShort_:bG,readLong_:bs,writeLong_:bE,readFixed_:bq,writeFixed_:bC,read:bn,write:bz,readString:bv,writeString:bH,times:by,get:bk,slice:bw,offset:function(bI){if(bI!=null){bm=bI;
return bx;
}return bm;
},skip:function(bI){bm+=bI;
},toString:function(){throw new Error("FIX CALLER.  BinaryStream is no longer convertible to string!");
},length:function(){return bl;
},saveExcursion:function(bI){var bJ=bm;
try{return bI();
}finally{bm=bJ;
}},writeBase64:function(bI){if(window.atob){bH(window.atob(bI));
}else{bz(c.decode(bI));
}},base64:function(){return c.encode(bk());
}};
return bx;
}function ba(bl){var bk=[],bh=0,bj=bl.length,bm,bi;
while(bh<bj){bm=bl.charCodeAt(bh++);
if(bm>=55296&&bm<=56319&&bh<bj){bi=bl.charCodeAt(bh++);
if((bi&64512)==56320){bk.push(((bm&1023)<<10)+(bi&1023)+65536);
}else{bk.push(bm);
bh--;
}}else{bk.push(bm);
}}return bk;
}function bb(bh){return bh.map(function(bj){var bi="";
if(bj>65535){bj-=65536;
bi+=String.fromCharCode(bj>>>10&1023|55296);
bj=56320|bj&1023;
}bi+=String.fromCharCode(bj);
return bi;
}).join("");
}function M(bi,bh){return Object.prototype.hasOwnProperty.call(bi,bh);
}function a0(bh){return Object.keys(bh).sort(function(bi,bj){return bi-bj;
}).map(parseFloat);
}function q(bh){this.raw=bh;
this.scalerType=bh.readLong();
this.tableCount=bh.readShort();
this.searchRange=bh.readShort();
this.entrySelector=bh.readShort();
this.rangeShift=bh.readShort();
var bk=this.tables={};
for(var bj=0;
bj<this.tableCount;
++bj){var bi={tag:bh.readString(4),checksum:bh.readLong(),offset:bh.readLong(),length:bh.readLong()};
bk[bi.tag]=bi;
}}q.prototype={readTable:function(bj,bh){var bi=this.tables[bj];
if(!bi){throw new Error("Table "+bj+" not found in directory");
}return this[bj]=bi.table=new bh(this,bi);
},render:function(bu){var bw=this;
var bs=Object.keys(bu).length;
var bl=Math.pow(2,Math.floor(Math.log(bs)/Math.LN2));
var bp=bl*16;
var bj=Math.floor(Math.log(bl)/Math.LN2);
var bo=bs*16-bp;
var bn=d();
bn.writeLong(this.scalerType);
bn.writeShort(bs);
bn.writeShort(bp);
bn.writeShort(bj);
bn.writeShort(bo);
var bi=bs*16;
var bm=bn.offset()+bi;
var bk=null;
var bt=d();
for(var bv in bu){if(M(bu,bv)){var br=bu[bv];
bn.writeString(bv);
bn.writeLong(bw.checksum(br));
bn.writeLong(bm);
bn.writeLong(br.length);
bt.write(br);
if(bv=="head"){bk=bm;
}bm+=br.length;
while(bm%4){bt.writeByte(0);
bm++;
}}}bn.write(bt.get());
var bq=this.checksum(bn.get());
var bh=2981146554-bq;
bn.offset(bk+8);
bn.writeLong(bh);
return bn.get();
},checksum:function(bh){bh=d(bh);
var bi=0;
while(!bh.eof()){bi+=bh.readLong();
}return bi&4294967295;
}};
function p(bj){function bh(bl,bk){this.definition=bk;
this.length=bk.length;
this.offset=bk.offset;
this.file=bl;
this.rawData=bl.raw;
this.parse(bl.raw);
}bh.prototype.raw=function(){return this.rawData.slice(this.offset,this.length);
};
for(var bi in bj){if(M(bj,bi)){bh[bi]=bh.prototype[bi]=bj[bi];
}}return bh;
}var N=p({parse:function(bh){bh.offset(this.offset);
this.version=bh.readLong();
this.revision=bh.readLong();
this.checkSumAdjustment=bh.readLong();
this.magicNumber=bh.readLong();
this.flags=bh.readShort();
this.unitsPerEm=bh.readShort();
this.created=bh.read(8);
this.modified=bh.read(8);
this.xMin=bh.readShort_();
this.yMin=bh.readShort_();
this.xMax=bh.readShort_();
this.yMax=bh.readShort_();
this.macStyle=bh.readShort();
this.lowestRecPPEM=bh.readShort();
this.fontDirectionHint=bh.readShort_();
this.indexToLocFormat=bh.readShort_();
this.glyphDataFormat=bh.readShort_();
},render:function(bh){var bi=d();
bi.writeLong(this.version);
bi.writeLong(this.revision);
bi.writeLong(0);
bi.writeLong(this.magicNumber);
bi.writeShort(this.flags);
bi.writeShort(this.unitsPerEm);
bi.write(this.created);
bi.write(this.modified);
bi.writeShort_(this.xMin);
bi.writeShort_(this.yMin);
bi.writeShort_(this.xMax);
bi.writeShort_(this.yMax);
bi.writeShort(this.macStyle);
bi.writeShort(this.lowestRecPPEM);
bi.writeShort_(this.fontDirectionHint);
bi.writeShort_(bh);
bi.writeShort_(this.glyphDataFormat);
return bi.get();
}});
var ae=p({parse:function(bh){bh.offset(this.offset);
var bi=this.file.head.indexToLocFormat;
if(bi===0){this.offsets=bh.times(this.length/2,function(){return 2*bh.readShort();
});
}else{this.offsets=bh.times(this.length/4,bh.readLong);
}},offsetOf:function(bh){return this.offsets[bh];
},lengthOf:function(bh){return this.offsets[bh+1]-this.offsets[bh];
},render:function(bj){var bk=d();
var bi=bj[bj.length-1]>65535;
for(var bh=0;
bh<bj.length;
++bh){if(bi){bk.writeLong(bj[bh]);
}else{bk.writeShort(bj[bh]/2);
}}return{format:bi?1:0,table:bk.get()};
}});
var O=p({parse:function(bh){bh.offset(this.offset);
this.version=bh.readLong();
this.ascent=bh.readShort_();
this.descent=bh.readShort_();
this.lineGap=bh.readShort_();
this.advanceWidthMax=bh.readShort();
this.minLeftSideBearing=bh.readShort_();
this.minRightSideBearing=bh.readShort_();
this.xMaxExtent=bh.readShort_();
this.caretSlopeRise=bh.readShort_();
this.caretSlopeRun=bh.readShort_();
this.caretOffset=bh.readShort_();
bh.skip(4*2);
this.metricDataFormat=bh.readShort_();
this.numOfLongHorMetrics=bh.readShort();
},render:function(bh){var bi=d();
bi.writeLong(this.version);
bi.writeShort_(this.ascent);
bi.writeShort_(this.descent);
bi.writeShort_(this.lineGap);
bi.writeShort(this.advanceWidthMax);
bi.writeShort_(this.minLeftSideBearing);
bi.writeShort_(this.minRightSideBearing);
bi.writeShort_(this.xMaxExtent);
bi.writeShort_(this.caretSlopeRise);
bi.writeShort_(this.caretSlopeRun);
bi.writeShort_(this.caretOffset);
bi.write([0,0,0,0,0,0,0,0]);
bi.writeShort_(this.metricDataFormat);
bi.writeShort(bh.length);
return bi.get();
}});
var aj=p({parse:function(bh){bh.offset(this.offset);
this.version=bh.readLong();
this.numGlyphs=bh.readShort();
this.maxPoints=bh.readShort();
this.maxContours=bh.readShort();
this.maxComponentPoints=bh.readShort();
this.maxComponentContours=bh.readShort();
this.maxZones=bh.readShort();
this.maxTwilightPoints=bh.readShort();
this.maxStorage=bh.readShort();
this.maxFunctionDefs=bh.readShort();
this.maxInstructionDefs=bh.readShort();
this.maxStackElements=bh.readShort();
this.maxSizeOfInstructions=bh.readShort();
this.maxComponentElements=bh.readShort();
this.maxComponentDepth=bh.readShort();
},render:function(bh){var bi=d();
bi.writeLong(this.version);
bi.writeShort(bh.length);
bi.writeShort(this.maxPoints);
bi.writeShort(this.maxContours);
bi.writeShort(this.maxComponentPoints);
bi.writeShort(this.maxComponentContours);
bi.writeShort(this.maxZones);
bi.writeShort(this.maxTwilightPoints);
bi.writeShort(this.maxStorage);
bi.writeShort(this.maxFunctionDefs);
bi.writeShort(this.maxInstructionDefs);
bi.writeShort(this.maxStackElements);
bi.writeShort(this.maxSizeOfInstructions);
bi.writeShort(this.maxComponentElements);
bi.writeShort(this.maxComponentDepth);
return bi.get();
}});
var P=p({parse:function(bh){bh.offset(this.offset);
var bi=this.file,bj=bi.hhea;
this.metrics=bh.times(bj.numOfLongHorMetrics,function(){return{advance:bh.readShort(),lsb:bh.readShort_()};
});
var bk=bi.maxp.numGlyphs-bi.hhea.numOfLongHorMetrics;
this.leftSideBearings=bh.times(bk,bh.readShort_);
},forGlyph:function(bh){var bi=this.metrics;
var bj=bi.length;
if(bh<bj){return bi[bh];
}return{advance:bi[bj-1].advance,lsb:this.leftSideBearings[bh-bj]};
},render:function(bh){var bl=this;
var bk=d();
for(var bi=0;
bi<bh.length;
++bi){var bj=bl.forGlyph(bh[bi]);
bk.writeShort(bj.advance);
bk.writeShort_(bj.lsb);
}return bk.get();
}});
var I=function(){function bk(bo){this.raw=bo;
}bk.prototype={compound:false,render:function(){return this.raw.get();
}};
var bh=1;
var bl=8;
var bj=32;
var bn=64;
var bm=128;
function bi(bo){this.raw=bo;
var bq=this.glyphIds=[];
var br=this.idOffsets=[];
while(true){var bp=bo.readShort();
br.push(bo.offset());
bq.push(bo.readShort());
if(!(bp&bj)){break;
}bo.skip(bp&bh?4:2);
if(bp&bm){bo.skip(8);
}else{if(bp&bn){bo.skip(4);
}else{if(bp&bl){bo.skip(2);
}}}}}bi.prototype={compound:true,render:function(bq){var bs=this;
var br=d(this.raw.get());
for(var bo=0;
bo<this.glyphIds.length;
++bo){var bp=bs.glyphIds[bo];
br.offset(bs.idOffsets[bo]);
br.writeShort(bq[bp]);
}return br.get();
}};
return p({parse:function(){this.cache={};
},glyphFor:function(br){var bo=this.cache;
if(M(bo,br)){return bo[br];
}var bt=this.file.loca;
var bs=bt.lengthOf(br);
if(bs===0){return bo[br]=null;
}var bp=this.rawData;
var bv=this.offset+bt.offsetOf(br);
var bw=d(bp.slice(bv,bs));
var bu=bw.readShort_();
var by=bw.readShort_();
var bA=bw.readShort_();
var bx=bw.readShort_();
var bz=bw.readShort_();
var bq=bo[br]=bu==-1?new bi(bw):new bk(bw);
bq.numberOfContours=bu;
bq.xMin=by;
bq.yMin=bA;
bq.xMax=bx;
bq.yMax=bz;
return bq;
},render:function(bp,bu,bt){var bv=d(),bs=[];
for(var bq=0;
bq<bu.length;
++bq){var br=bu[bq];
var bo=bp[br];
bs.push(bv.offset());
if(bo){bv.write(bo.render(bt));
}}bs.push(bv.offset());
return{table:bv.get(),offsets:bs};
}});
}();
var ap=function(){function bh(bj,bi){this.text=bj;
this.length=bj.length;
this.platformID=bi.platformID;
this.platformSpecificID=bi.platformSpecificID;
this.languageID=bi.languageID;
this.nameID=bi.nameID;
}return p({parse:function(bj){bj.offset(this.offset);
bj.readShort();
var bi=bj.readShort();
var bn=this.offset+bj.readShort();
var bl=bj.times(bi,function(){return{platformID:bj.readShort(),platformSpecificID:bj.readShort(),languageID:bj.readShort(),nameID:bj.readShort(),length:bj.readShort(),offset:bj.readShort()+bn};
});
var bo=this.strings={};
for(var bk=0;
bk<bl.length;
++bk){var bm=bl[bk];
bj.offset(bm.offset);
var bp=bj.readString(bm.length);
if(!bo[bm.nameID]){bo[bm.nameID]=[];
}bo[bm.nameID].push(new bh(bp,bm));
}this.postscriptEntry=bo[6][0];
this.postscriptName=this.postscriptEntry.text.replace(/[^\x20-\x7F]/g,"");
},render:function(bm){var br=this;
var bp=this.strings;
var bo=0;
for(var bi in bp){if(M(bp,bi)){bo+=bp[bi].length;
}}var bl=d();
var bq=d();
bl.writeShort(0);
bl.writeShort(bo);
bl.writeShort(6+12*bo);
for(bi in bp){if(M(bp,bi)){var bk=bi==6?[new bh(bm,br.postscriptEntry)]:bp[bi];
for(var bj=0;
bj<bk.length;
++bj){var bn=bk[bj];
bl.writeShort(bn.platformID);
bl.writeShort(bn.platformSpecificID);
bl.writeShort(bn.languageID);
bl.writeShort(bn.nameID);
bl.writeShort(bn.length);
bl.writeShort(bq.offset());
bq.writeString(bn.text);
}}}bl.write(bq.get());
return bl.get();
}});
}();
var aQ=function(){var bh=".notdef .null nonmarkingreturn space exclam quotedbl numbersign dollar percent ampersand quotesingle parenleft parenright asterisk plus comma hyphen period slash zero one two three four five six seven eight nine colon semicolon less equal greater question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z bracketleft backslash bracketright asciicircum underscore grave a b c d e f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright asciitilde Adieresis Aring Ccedilla Eacute Ntilde Odieresis Udieresis aacute agrave acircumflex adieresis atilde aring ccedilla eacute egrave ecircumflex edieresis iacute igrave icircumflex idieresis ntilde oacute ograve ocircumflex odieresis otilde uacute ugrave ucircumflex udieresis dagger degree cent sterling section bullet paragraph germandbls registered copyright trademark acute dieresis notequal AE Oslash infinity plusminus lessequal greaterequal yen mu partialdiff summation product pi integral ordfeminine ordmasculine Omega ae oslash questiondown exclamdown logicalnot radical florin approxequal Delta guillemotleft guillemotright ellipsis nonbreakingspace Agrave Atilde Otilde OE oe endash emdash quotedblleft quotedblright quoteleft quoteright divide lozenge ydieresis Ydieresis fraction currency guilsinglleft guilsinglright fi fl daggerdbl periodcentered quotesinglbase quotedblbase perthousand Acircumflex Ecircumflex Aacute Edieresis Egrave Iacute Icircumflex Idieresis Igrave Oacute Ocircumflex apple Ograve Uacute Ucircumflex Ugrave dotlessi circumflex tilde macron breve dotaccent ring cedilla hungarumlaut ogonek caron Lslash lslash Scaron scaron Zcaron zcaron brokenbar Eth eth Yacute yacute Thorn thorn minus multiply onesuperior twosuperior threesuperior onehalf onequarter threequarters franc Gbreve gbreve Idotaccent Scedilla scedilla Cacute cacute Ccaron ccaron dcroat".split(/\s+/g);
return p({parse:function(bi){var bl=this;
bi.offset(this.offset);
this.format=bi.readLong();
this.italicAngle=bi.readFixed_();
this.underlinePosition=bi.readShort_();
this.underlineThickness=bi.readShort_();
this.isFixedPitch=bi.readLong();
this.minMemType42=bi.readLong();
this.maxMemType42=bi.readLong();
this.minMemType1=bi.readLong();
this.maxMemType1=bi.readLong();
var bk;
switch(this.format){case 65536:case 196608:break;
case 131072:bk=bi.readShort();
this.glyphNameIndex=bi.times(bk,bi.readShort);
this.names=[];
var bj=this.offset+this.length;
while(bi.offset()<bj){bl.names.push(bi.readString(bi.readByte()));
}break;
case 151552:bk=bi.readShort();
this.offsets=bi.read(bk);
break;
case 262144:this.map=bi.times(this.file.maxp.numGlyphs,bi.readShort);
break;
}},glyphFor:function(bi){switch(this.format){case 65536:return bh[bi]||".notdef";
case 131072:var bj=this.glyphNameIndex[bi];
if(bj<bh.length){return bh[bj];
}return this.names[bj-bh.length]||".notdef";
case 151552:case 196608:return".notdef";
case 262144:return this.map[bi]||65535;
}},render:function(bm){var bq=this;
if(this.format==196608){return this.raw();
}var bn=d(this.rawData.slice(this.offset,32));
bn.writeLong(131072);
bn.offset(32);
var bl=[];
var bp=[];
for(var bi=0;
bi<bm.length;
++bi){var bj=bm[bi];
var bo=bq.glyphFor(bj);
var bk=bh.indexOf(bo);
if(bk>=0){bl.push(bk);
}else{bl.push(bh.length+bp.length);
bp.push(bo);
}}bn.writeShort(bm.length);
for(bi=0;
bi<bl.length;
++bi){bn.writeShort(bl[bi]);
}for(bi=0;
bi<bp.length;
++bi){bn.writeByte(bp[bi].length);
bn.writeString(bp[bi]);
}return bn.get();
}});
}();
var l=function(){function bh(bk,bl,bj){var bm=this;
bm.platformID=bk.readShort();
bm.platformSpecificID=bk.readShort();
bm.offset=bl+bk.readLong();
bk.saveExcursion(function(){var bn;
bk.offset(bm.offset);
bm.format=bk.readShort();
switch(bm.format){case 0:bm.length=bk.readShort();
bm.language=bk.readShort();
for(var bv=0;
bv<256;
++bv){bj[bv]=bk.readByte();
}break;
case 4:bm.length=bk.readShort();
bm.language=bk.readShort();
var bB=bk.readShort()/2;
bk.skip(6);
var br=bk.times(bB,bk.readShort);
bk.skip(2);
var bD=bk.times(bB,bk.readShort);
var bw=bk.times(bB,bk.readShort_);
var bx=bk.times(bB,bk.readShort);
var bo=(bm.length+bm.offset-bk.offset())/2;
var bu=bk.times(bo,bk.readShort);
for(bv=0;
bv<bB;
++bv){var bC=bD[bv],bp=br[bv];
for(bn=bC;
bn<=bp;
++bn){var bt;
if(bx[bv]===0){bt=bn+bw[bv];
}else{var by=bx[bv]/2-(bB-bv)+(bn-bC);
bt=bu[by]||0;
if(bt!==0){bt+=bw[bv];
}}bj[bn]=bt&65535;
}}break;
case 6:bm.length=bk.readShort();
bm.language=bk.readShort();
bn=bk.readShort();
var bz=bk.readShort();
while(bz-->0){bj[bn++]=bk.readShort();
}break;
case 12:bk.readShort();
bm.length=bk.readLong();
bm.language=bk.readLong();
var bA=bk.readLong();
while(bA-->0){bn=bk.readLong();
var bq=bk.readLong();
var bs=bk.readLong();
while(bn<=bq){bj[bn++]=bs++;
}}break;
default:if(window.console){window.console.error("Unhandled CMAP format: "+bm.format);
}}});
}function bi(bw,by){var bk=a0(bw);
var bG=[];
var bp=[];
var bv=null;
var bn=null;
function bx(bI){return by[bw[bI]];
}for(var bt=0;
bt<bk.length;
++bt){var bj=bk[bt];
var br=bx(bj);
var bl=br-bj;
if(bv==null||bl!==bn){if(bv){bp.push(bv);
}bG.push(bj);
bn=bl;
}bv=bj;
}if(bv){bp.push(bv);
}bp.push(65535);
bG.push(65535);
var bD=bG.length;
var bE=bD*2;
var bC=2*Math.pow(2,Math.floor(Math.log(bD)/Math.LN2));
var bq=Math.log(bC/2)/Math.LN2;
var bB=bE-bC;
var bm=[];
var bA=[];
var bs=[];
for(bt=0;
bt<bD;
++bt){var bF=bG[bt];
var bo=bp[bt];
if(bF==65535){bm.push(0);
bA.push(0);
break;
}var bH=bx(bF);
if(bF-bH>=32768){bm.push(0);
bA.push(2*(bs.length+bD-bt));
for(var bu=bF;
bu<=bo;
++bu){bs.push(bx(bu));
}}else{bm.push(bH-bF);
bA.push(0);
}}var bz=d();
bz.writeShort(3);
bz.writeShort(1);
bz.writeLong(12);
bz.writeShort(4);
bz.writeShort(16+bD*8+bs.length*2);
bz.writeShort(0);
bz.writeShort(bE);
bz.writeShort(bC);
bz.writeShort(bq);
bz.writeShort(bB);
bp.forEach(bz.writeShort);
bz.writeShort(0);
bG.forEach(bz.writeShort);
bm.forEach(bz.writeShort_);
bA.forEach(bz.writeShort);
bs.forEach(bz.writeShort);
return bz.get();
}return p({parse:function(bj){var bl=this;
var bk=bl.offset;
bj.offset(bk);
bl.codeMap={};
bl.version=bj.readShort();
var bm=bj.readShort();
bl.tables=bj.times(bm,function(){return new bh(bj,bk,bl.codeMap);
});
},render:function(bj,bk){var bl=d();
bl.writeShort(0);
bl.writeShort(1);
bl.write(bi(bj,bk));
return bl.get();
}});
}();
var au=p({parse:function(bh){bh.offset(this.offset);
this.version=bh.readShort();
this.averageCharWidth=bh.readShort_();
this.weightClass=bh.readShort();
this.widthClass=bh.readShort();
this.type=bh.readShort();
this.ySubscriptXSize=bh.readShort_();
this.ySubscriptYSize=bh.readShort_();
this.ySubscriptXOffset=bh.readShort_();
this.ySubscriptYOffset=bh.readShort_();
this.ySuperscriptXSize=bh.readShort_();
this.ySuperscriptYSize=bh.readShort_();
this.ySuperscriptXOffset=bh.readShort_();
this.ySuperscriptYOffset=bh.readShort_();
this.yStrikeoutSize=bh.readShort_();
this.yStrikeoutPosition=bh.readShort_();
this.familyClass=bh.readShort_();
this.panose=bh.times(10,bh.readByte);
this.charRange=bh.times(4,bh.readLong);
this.vendorID=bh.readString(4);
this.selection=bh.readShort();
this.firstCharIndex=bh.readShort();
this.lastCharIndex=bh.readShort();
if(this.version>0){this.ascent=bh.readShort_();
this.descent=bh.readShort_();
this.lineGap=bh.readShort_();
this.winAscent=bh.readShort();
this.winDescent=bh.readShort();
this.codePageRange=bh.times(2,bh.readLong);
if(this.version>1){this.xHeight=bh.readShort();
this.capHeight=bh.readShort();
this.defaultChar=bh.readShort();
this.breakChar=bh.readShort();
this.maxContext=bh.readShort();
}}},render:function(){return this.raw();
}});
var a2=100000;
function aq(){var bj="",bi=String(a2);
for(var bh=0;
bh<bi.length;
++bh){bj+=String.fromCharCode(bi.charCodeAt(bh)-48+65);
}++a2;
return bj;
}function a1(bh){this.font=bh;
this.subset={};
this.unicodes={};
this.ogid2ngid={0:0};
this.ngid2ogid={0:0};
this.ncid2ogid={};
this.next=this.firstChar=1;
this.nextGid=1;
this.psName=aq()+"+"+this.font.psName;
}a1.prototype={use:function(bh){var bl=this;
if(typeof bh=="string"){return ba(bh).reduce(function(bn,bm){return bn+String.fromCharCode(bl.use(bm));
},"");
}var bi=bl.unicodes[bh];
if(!bi){bi=bl.next++;
bl.subset[bi]=bh;
bl.unicodes[bh]=bi;
var bk=bl.font.cmap.codeMap[bh];
if(bk){bl.ncid2ogid[bi]=bk;
if(bl.ogid2ngid[bk]==null){var bj=bl.nextGid++;
bl.ogid2ngid[bk]=bj;
bl.ngid2ogid[bj]=bk;
}}}return bi;
},encodeText:function(bh){return this.use(bh);
},glyphIds:function(){return a0(this.ogid2ngid);
},glyphsFor:function(bi,bl){var bm=this;
if(!bl){bl={};
}for(var bj=0;
bj<bi.length;
++bj){var bk=bi[bj];
if(!bl[bk]){var bh=bl[bk]=bm.font.glyf.glyphFor(bk);
if(bh&&bh.compound){bm.glyphsFor(bh.glyphIds,bl);
}}}return bl;
},render:function(){var bq=this;
var bj=this.glyphsFor(this.glyphIds());
for(var bn in bj){if(M(bj,bn)){bn=parseInt(bn,10);
if(bq.ogid2ngid[bn]==null){var bl=bq.nextGid++;
bq.ogid2ngid[bn]=bl;
bq.ngid2ogid[bl]=bn;
}}}var bm=a0(this.ngid2ogid);
var bo=bm.map(function(br){return this.ngid2ogid[br];
},this);
var bh=this.font;
var bi=bh.glyf.render(bj,bo,this.ogid2ngid);
var bk=bh.loca.render(bi.offsets);
this.lastChar=this.next-1;
var bp={cmap:l.render(this.ncid2ogid,this.ogid2ngid),glyf:bi.table,loca:bk.table,hmtx:bh.hmtx.render(bo),hhea:bh.hhea.render(bo),maxp:bh.maxp.render(bo),post:bh.post.render(bo),name:bh.name.render(this.psName),head:bh.head.render(bk.format),"OS/2":bh.os2.render()};
return this.font.directory.render(bp);
},cidToGidMap:function(){var bm=this;
var bl=d(),bi=0;
for(var bh=this.firstChar;
bh<this.next;
++bh){while(bi<bh){bl.writeShort(0);
bi++;
}var bk=bm.ncid2ogid[bh];
if(bk){var bj=bm.ogid2ngid[bk];
bl.writeShort(bj);
}else{bl.writeShort(0);
}bi++;
}return bl.get();
}};
function a9(bn,bj){var bo=this;
var bh=bo.contents=d(bn);
if(bh.readString(4)=="ttcf"){var bl;
var bm=function(){bh.offset(bl);
bo.parse();
};
if(!bj){throw new Error("Must specify a name for TTC files");
}bh.readLong();
var bk=bh.readLong();
for(var bi=0;
bi<bk;
++bi){bl=bh.readLong();
bh.saveExcursion(bm);
if(bo.psName==bj){return;
}}throw new Error("Font "+bj+" not found in collection");
}else{bh.offset(0);
bo.parse();
}}a9.prototype={parse:function(){var bh=this.directory=new q(this.contents);
this.head=bh.readTable("head",N);
this.loca=bh.readTable("loca",ae);
this.hhea=bh.readTable("hhea",O);
this.maxp=bh.readTable("maxp",aj);
this.hmtx=bh.readTable("hmtx",P);
this.glyf=bh.readTable("glyf",I);
this.name=bh.readTable("name",ap);
this.post=bh.readTable("post",aQ);
this.cmap=bh.readTable("cmap",l);
this.os2=bh.readTable("OS/2",au);
this.psName=this.name.postscriptName;
this.ascent=this.os2.ascent||this.hhea.ascent;
this.descent=this.os2.descent||this.hhea.descent;
this.lineGap=this.os2.lineGap||this.hhea.lineGap;
this.scale=1000/this.head.unitsPerEm;
},widthOfGlyph:function(bh){return this.hmtx.forGlyph(bh).advance*this.scale;
},makeSubset:function(){return new a1(this);
}};
var e=V.support.browser;
var J=typeof Uint8Array!=="undefined";
var ar="\n";
var aU=0;
var aw={a0:[2383.94,3370.39],a1:[1683.78,2383.94],a2:[1190.55,1683.78],a3:[841.89,1190.55],a4:[595.28,841.89],a5:[419.53,595.28],a6:[297.64,419.53],a7:[209.76,297.64],a8:[147.4,209.76],a9:[104.88,147.4],a10:[73.7,104.88],b0:[2834.65,4008.19],b1:[2004.09,2834.65],b2:[1417.32,2004.09],b3:[1000.63,1417.32],b4:[708.66,1000.63],b5:[498.9,708.66],b6:[354.33,498.9],b7:[249.45,354.33],b8:[175.75,249.45],b9:[124.72,175.75],b10:[87.87000000000001,124.72],c0:[2599.37,3676.54],c1:[1836.85,2599.37],c2:[1298.27,1836.85],c3:[918.43,1298.27],c4:[649.13,918.43],c5:[459.21,649.13],c6:[323.15,459.21],c7:[229.61,323.15],c8:[161.57,229.61],c9:[113.39,161.57],c10:[79.37000000000001,113.39],executive:[521.86,756],folio:[612,936],legal:[612,1008],letter:[612,792],tabloid:[792,1224]};
function ah(){var bh=0,bj=d();
function bi(){var bk=arguments;
for(var bl=0;
bl<arguments.length;
++bl){var bn=bk[bl];
if(bn===undefined){throw new Error("Cannot output undefined to PDF");
}else{if(bn instanceof aP){bn.beforeRender(bi);
bn.render(bi);
}else{if(S(bn)){aS(bn,bi);
}else{if(T(bn)){aT(bn,bi);
}else{if(typeof bn=="number"){if(isNaN(bn)){throw new Error("Cannot output NaN to PDF");
}var bm=bn.toFixed(7);
if(bm.indexOf(".")>=0){bm=bm.replace(/\.?0+$/,"");
}if(bm=="-0"){bm="0";
}bj.writeString(bm);
}else{if(/string|boolean/.test(typeof bn)){bj.writeString(String(bn));
}else{if(typeof bn.get=="function"){bj.write(bn.get());
}else{if(typeof bn=="object"){if(!bn){bj.writeString("null");
}else{bi(new aA(bn));
}}}}}}}}}}}bi.writeData=function(bk){bj.write(bk);
};
bi.withIndent=function(bk){++bh;
bk(bi);
--bh;
};
bi.indent=function(){bi(ar,av("",bh*2,"  "));
bi.apply(null,arguments);
};
bi.offset=function(){return bj.offset();
};
bi.toString=function(){throw new Error("FIX CALLER");
};
bi.get=function(){return bj.get();
};
bi.stream=function(){return bj;
};
return bi;
}function bf(bk,bi){var bh=bk.beforeRender;
var bj=bk.render;
bk.beforeRender=function(){};
bk.render=function(bl){bl(bi," 0 R");
};
bk.renderFull=function(bl){bk._offset=bl.offset();
bl(bi," 0 obj ");
bh.call(bk,bl);
bj.call(bk,bl);
bl(" endobj");
};
}function H(bh){if(typeof bh!="function"){var bj=bh;
bh=function(bm,bl){return bm in bj?bj[bm]:bl;
};
}var bk=bh("paperSize",aw.a4);
if(!bk){return{};
}if(typeof bk=="string"){bk=aw[bk.toLowerCase()];
if(bk==null){throw new Error("Unknown paper size");
}}bk[0]=bc(bk[0]);
bk[1]=bc(bk[1]);
if(bh("landscape",false)){bk=[Math.max(bk[0],bk[1]),Math.min(bk[0],bk[1])];
}var bi=bh("margin");
if(bi){if(typeof bi=="string"||typeof bi=="number"){bi=bc(bi,0);
bi={left:bi,top:bi,right:bi,bottom:bi};
}else{bi={left:bc(bi.left,0),top:bc(bi.top,0),right:bc(bi.right,0),bottom:bc(bi.bottom,0)};
}if(bh("addMargin")){bk[0]+=bi.left+bi.right;
bk[1]+=bi.top+bi.bottom;
}}return{paperSize:bk,margin:bi};
}function aB(bl){var bo=this;
var bm=ah();
var bj=0;
var bk=[];
function bi(bq,bp){return bl&&bl[bq]!=null?bl[bq]:bp;
}bo.getOption=bi;
bo.attach=function(bp){if(bk.indexOf(bp)<0){bf(bp,++bj);
bk.push(bp);
}return bp;
};
bo.pages=[];
bo.FONTS={};
bo.IMAGES={};
bo.GRAD_COL_FUNCTIONS={};
bo.GRAD_OPC_FUNCTIONS={};
bo.GRAD_COL={};
bo.GRAD_OPC={};
var bh=bo.attach(new az());
var bn=bo.attach(new aI());
bh.setPages(bn);
bo.addPage=function(bt){var bv=H(function(bz,by){return bt&&bt[bz]!=null?bt[bz]:by;
});
var bw=bv.paperSize;
var bs=bv.margin;
var br=bw[0];
var bq=bw[1];
if(bs){br-=bs.left+bs.right;
bq-=bs.top+bs.bottom;
}var bp=new aL(ah(),null,true);
var bx={Contents:bo.attach(bp),Parent:bn,MediaBox:[0,0,bw[0],bw[1]]};
var bu=new aH(bo,bx);
bu._content=bp;
bn.addPage(bo.attach(bu));
bu.transform(1,0,0,-1,0,bw[1]);
if(bs){bu.translate(bs.left,bs.top);
bu.rect(0,0,br,bq);
bu.clip();
}bo.pages.push(bu);
return bu;
};
bo.render=function(){var bp;
bm("%PDF-1.4",ar,"%базон",ar,ar);
for(bp=0;
bp<bk.length;
++bp){bk[bp].renderFull(bm);
bm(ar,ar);
}var bq=bm.offset();
bm("xref",ar,0," ",bk.length+1,ar);
bm("0000000000 65535 f ",ar);
for(bp=0;
bp<bk.length;
++bp){bm(bg(bk[bp]._offset,10)," 00000 n ",ar);
}bm(ar);
bm("trailer",ar);
bm(new aA({Size:bk.length+1,Root:bh,Info:new aA({Producer:new aM(bi("producer","Kendo UI PDF Generator")),Title:new aM(bi("title","")),Author:new aM(bi("author","")),Subject:new aM(bi("subject","")),Keywords:new aM(bi("keywords","")),Creator:new aM(bi("creator","Kendo UI PDF Generator")),CreationDate:bi("date",new Date())})}),ar,ar);
bm("startxref",ar,bq,ar);
bm("%%EOF",ar);
return bm.stream().offset(0);
};
}var D={"Times-Roman":true,"Times-Bold":true,"Times-Italic":true,"Times-BoldItalic":true,Helvetica:true,"Helvetica-Bold":true,"Helvetica-Oblique":true,"Helvetica-BoldOblique":true,Courier:true,"Courier-Bold":true,"Courier-Oblique":true,"Courier-BoldOblique":true,Symbol:true,ZapfDingbats:true};
function Z(bk,bh){function bi(){if(window.console){if(window.console.error){window.console.error("Cannot load URL: %s",bk);
}else{window.console.log("Cannot load URL: %s",bk);
}}bh(null);
}var bj=new XMLHttpRequest();
bj.open("GET",bk,true);
if(J){bj.responseType="arraybuffer";
}bj.onload=function(){if(bj.status==200||bj.status==304){if(J){bh(new Uint8Array(bj.response));
}else{bh(new window.VBArray(bj.responseBody).toArray());
}}else{bi();
}};
bj.onerror=bi;
bj.send(null);
}function aa(bj,bh){var bi=D[bj];
if(bi){bh(bi);
}else{Z(bj,function(bk){if(bk==null){throw new Error("Cannot load font from "+bj);
}else{var bl=new a9(bk);
D[bj]=bl;
bh(bl);
}});
}}var Q={};
function ac(bo,bm){var bn=Q[bo],bl,bk;
if(bn){bm(bn);
}else{bn=new Image();
if(!/^data:/i.test(bo)){bn.crossOrigin="Anonymous";
}if(J&&!/^data:/i.test(bo)){var bp=new XMLHttpRequest();
bp.onload=function(){bk=bp.response;
bl=URL.createObjectURL(bk);
bh(bl);
};
bp.onerror=bi;
bp.open("GET",bo,true);
bp.responseType="blob";
bp.send();
}else{bh(bo);
}}function bh(bq){bn.src=bq;
if(bn.complete&&!e.msie){bj();
}else{bn.onload=bj;
bn.onerror=bi;
}}function bi(){bm(Q[bo]="TAINTED");
}function bj(){if(bk&&/^image\/jpe?g$/i.test(bk.type)){var bA=new FileReader();
bA.onload=function(){bn=new aE(bn.width,bn.height,d(new Uint8Array(this.result)));
URL.revokeObjectURL(bl);
bm(Q[bo]=bn);
};
bA.readAsArrayBuffer(bk);
return;
}var bs=document.createElement("canvas");
bs.width=bn.width;
bs.height=bn.height;
var bt=bs.getContext("2d");
bt.drawImage(bn,0,0);
var by;
try{by=bt.getImageData(0,0,bn.width,bn.height);
}catch(bv){bi();
return;
}finally{if(bl){URL.revokeObjectURL(bl);
}}var bw=false,bB=d(),br=d();
var bz=by.data;
var bx=0;
while(bx<bz.length){bB.writeByte(bz[bx++]);
bB.writeByte(bz[bx++]);
bB.writeByte(bz[bx++]);
var bq=bz[bx++];
if(bq<255){bw=true;
}br.writeByte(bq);
}if(bw){bn=new aJ(bn.width,bn.height,bB,br);
}else{var bu=bs.toDataURL("image/jpeg");
bu=bu.substr(bu.indexOf(";base64,")+8);
var bC=d();
bC.writeBase64(bu);
bC.offset(0);
bn=new aE(bn.width,bn.height,bC);
}bm(Q[bo]=bn);
}}function ai(bh){return function(bm,bi){var bk=bm.length,bj=bk;
if(bk===0){return bi();
}function bl(){if(--bk===0){bi();
}}while(bj-->0){bh(bm[bj],bl);
}};
}var ab=ai(aa);
var ad=ai(ac);
aB.prototype={loadFonts:ab,loadImages:ad,getFont:function(bi){var bh=this.FONTS[bi];
if(!bh){bh=D[bi];
if(!bh){throw new Error("Font "+bi+" has not been loaded");
}if(bh===true){bh=this.attach(new aK(bi));
}else{bh=this.attach(new aC(this,bh));
}this.FONTS[bi]=bh;
}return bh;
},getImage:function(bi){var bh=this.IMAGES[bi];
if(!bh){bh=Q[bi];
if(!bh){throw new Error("Image "+bi+" has not been loaded");
}if(bh==="TAINTED"){return null;
}bh=this.IMAGES[bi]=this.attach(bh.asStream(this));
}return bh;
},getOpacityGS:function(bl,bi){var bk=parseFloat(bl).toFixed(3);
bl=parseFloat(bk);
bk+=bi?"S":"F";
var bh=this._opacityGSCache||(this._opacityGSCache={});
var bj=bh[bk];
if(!bj){var bm={Type:a("ExtGState")};
if(bi){bm.CA=bl;
}else{bm.ca=bl;
}bj=this.attach(new aA(bm));
bj._resourceName=a("GS"+ ++aU);
bh[bk]=bj;
}return bj;
},dict:function(bh){return new aA(bh);
},name:function(bh){return a(bh);
},stream:function(bi,bh){return new aL(bh,bi);
}};
function av(bj,bi,bh){while(bj.length<bi){bj=bh+bj;
}return bj;
}function bg(bi,bh){return av(String(bi),bh,"0");
}function L(bi,bh){return Object.prototype.hasOwnProperty.call(bi,bh);
}var S=Array.isArray||function(bh){return bh instanceof Array;
};
function T(bh){return bh instanceof Date;
}function aS(bh,bi){bi("[");
if(bh.length>0){bi.withIndent(function(){for(var bj=0;
bj<bh.length;
++bj){if(bj>0&&bj%8===0){bi.indent(bh[bj]);
}else{bi(" ",bh[bj]);
}}});
}bi(" ]");
}function aT(bh,bi){bi("(D:",bg(bh.getUTCFullYear(),4),bg(bh.getUTCMonth()+1,2),bg(bh.getUTCDate(),2),bg(bh.getUTCHours(),2),bg(bh.getUTCMinutes(),2),bg(bh.getUTCSeconds(),2),"Z)");
}function an(bh){return bh*(72/25.4);
}function k(bh){return an(bh*10);
}function R(bh){return bh*72;
}function bc(bk,bh){if(typeof bk=="number"){return bk;
}if(typeof bk=="string"){var bi;
bi=/^\s*([0-9.]+)\s*(mm|cm|in|pt)\s*$/.exec(bk);
if(bi){var bj=parseFloat(bi[1]);
if(!isNaN(bj)){if(bi[2]=="pt"){return bj;
}return{mm:an,cm:k,"in":R}[bi[2]](bj);
}}}if(bh!=null){return bh;
}throw new Error("Can't parse unit: "+bk);
}function aP(){}aP.prototype.beforeRender=function(){};
function n(bi,bk,bh){if(!bh){bh=aP;
}bi.prototype=new bh();
for(var bj in bk){if(L(bk,bj)){bi.prototype[bj]=bk[bj];
}}return bi;
}var aM=n(function aM(bh){this.value=bh;
},{render:function(bj){var bk="",bh=this.escape();
for(var bi=0;
bi<bh.length;
++bi){bk+=String.fromCharCode(bh.charCodeAt(bi)&255);
}bj("(",bk,")");
},escape:function(){return this.value.replace(/([\(\)\\])/g,"\\$1");
},toString:function(){return this.value;
}});
var aD=n(function aD(bh){this.value=bh;
},{render:function(bi){var bj=this;
bi("<");
for(var bh=0;
bh<this.value.length;
++bh){bi(bg(bj.value.charCodeAt(bh).toString(16),4));
}bi(">");
}},aM);
var aF=n(function aF(bh){this.name=bh;
},{render:function(bh){bh("/"+this.escape());
},escape:function(){return this.name.replace(/[^\x21-\x7E]/g,function(bh){return"#"+bg(bh.charCodeAt(0).toString(16),2);
});
},toString:function(){return this.name;
}});
var aG={};
aF.get=a;
function a(bh){if(L(aG,bh)){return aG[bh];
}return aG[bh]=new aF(bh);
}var aA=n(function aA(bh){this.props=bh;
},{render:function(bi){var bj=this.props,bh=true;
bi("<<");
bi.withIndent(function(){for(var bk in bj){if(L(bj,bk)&&!/^_/.test(bk)){bh=false;
bi.indent(a(bk)," ",bj[bk]);
}}});
if(!bh){bi.indent();
}bi(">>");
}});
var aL=n(function aL(bi,bj,bh){if(typeof bi=="string"){var bk=d();
bk.write(bi);
bi=bk;
}this.data=bi;
this.props=bj||{};
this.compress=bh;
},{render:function(bi){var bh=this.data.get(),bj=this.props;
if(this.compress&&window.pako&&typeof window.pako.deflate=="function"){if(!bj.Filter){bj.Filter=[];
}else{if(!(bj.Filter instanceof Array)){bj.Filter=[bj.Filter];
}}bj.Filter.unshift(a("FlateDecode"));
bh=window.pako.deflate(bh);
}bj.Length=bh.length;
bi(new aA(bj)," stream",ar);
bi.writeData(bh);
bi(ar,"endstream");
}});
var az=n(function az(bh){bh=this.props=bh||{};
bh.Type=a("Catalog");
},{setPages:function(bh){this.props.Pages=bh;
}},aA);
var aI=n(function aI(){this.props={Type:a("Pages"),Kids:[],Count:0};
},{addPage:function(bh){this.props.Kids.push(bh);
this.props.Count++;
}},aA);
function aE(bj,bi,bh){this.asStream=function(){var bk=new aL(bh,{Type:a("XObject"),Subtype:a("Image"),Width:bj,Height:bi,BitsPerComponent:8,ColorSpace:a("DeviceRGB"),Filter:a("DCTDecode")});
bk._resourceName=a("I"+ ++aU);
return bk;
};
}function aJ(bk,bi,bj,bh){this.asStream=function(bm){var bl=new aL(bh,{Type:a("XObject"),Subtype:a("Image"),Width:bk,Height:bi,BitsPerComponent:8,ColorSpace:a("DeviceGray")},true);
var bn=new aL(bj,{Type:a("XObject"),Subtype:a("Image"),Width:bk,Height:bi,BitsPerComponent:8,ColorSpace:a("DeviceRGB"),SMask:bm.attach(bl)},true);
bn._resourceName=a("I"+ ++aU);
return bn;
};
}var aK=n(function aK(bh){this.props={Type:a("Font"),Subtype:a("Type1"),BaseFont:a(bh)};
this._resourceName=a("F"+ ++aU);
},{encodeText:function(bh){return new aM(String(bh));
}},aA);
var aC=n(function aC(bj,bh,bk){bk=this.props=bk||{};
bk.Type=a("Font");
bk.Subtype=a("Type0");
bk.Encoding=a("Identity-H");
this._pdf=bj;
this._font=bh;
this._sub=bh.makeSubset();
this._resourceName=a("F"+ ++aU);
var bi=bh.head;
this.name=bh.psName;
var bl=this.scale=bh.scale;
this.bbox=[bi.xMin*bl,bi.yMin*bl,bi.xMax*bl,bi.yMax*bl];
this.italicAngle=bh.post.italicAngle;
this.ascent=bh.ascent*bl;
this.descent=bh.descent*bl;
this.lineGap=bh.lineGap*bl;
this.capHeight=bh.os2.capHeight||this.ascent;
this.xHeight=bh.os2.xHeight||0;
this.stemV=0;
this.familyClass=(bh.os2.familyClass||0)>>8;
this.isSerif=this.familyClass>=1&&this.familyClass<=7;
this.isScript=this.familyClass==10;
this.flags=(bh.post.isFixedPitch?1:0)|(this.isSerif?1<<1:0)|(this.isScript?1<<3:0)|(this.italicAngle!==0?1<<6:0)|1<<5;
},{encodeText:function(bh){return new aD(this._sub.encodeText(String(bh)));
},getTextWidth:function(bi,bl){var bm=this;
var bn=0,bh=this._font.cmap.codeMap;
for(var bk=0;
bk<bl.length;
++bk){var bj=bh[bl.charCodeAt(bk)];
bn+=bm._font.widthOfGlyph(bj||0);
}return bn*bi/1000;
},beforeRender:function(){var br=this;
var bs=br._sub;
var bj=bs.render();
var bo=new aL(d(bj),{Length1:bj.length},true);
var bl=br._pdf.attach(new aA({Type:a("FontDescriptor"),FontName:a(br._sub.psName),FontBBox:br.bbox,Flags:br.flags,StemV:br.stemV,ItalicAngle:br.italicAngle,Ascent:br.ascent,Descent:br.descent,CapHeight:br.capHeight,XHeight:br.xHeight,FontFile2:br._pdf.attach(bo)}));
var bi=bs.ncid2ogid;
var bn=bs.firstChar;
var bp=bs.lastChar;
var bh=[];
(function bq(bx,bv){if(bx<=bp){var bw=bi[bx];
if(bw==null){bq(bx+1);
}else{if(!bv){bh.push(bx,bv=[]);
}bv.push(br._font.widthOfGlyph(bw));
bq(bx+1,bv);
}}}(bn));
var bk=new aA({Type:a("Font"),Subtype:a("CIDFontType2"),BaseFont:a(br._sub.psName),CIDSystemInfo:new aA({Registry:new aM("Adobe"),Ordering:new aM("Identity"),Supplement:0}),FontDescriptor:bl,FirstChar:bn,LastChar:bp,DW:Math.round(br._font.widthOfGlyph(0)),W:bh,CIDToGIDMap:br._pdf.attach(br._makeCidToGidMap())});
var bm=br.props;
bm.BaseFont=a(br._sub.psName);
bm.DescendantFonts=[br._pdf.attach(bk)];
var bt=new aN(bn,bp,bs.subset);
var bu=new aL(ah(),null,true);
bu.data(bt);
bm.ToUnicode=br._pdf.attach(bu);
},_makeCidToGidMap:function(){return new aL(d(this._sub.cidToGidMap()),null,true);
}},aA);
var aN=n(function aO(bh,bi,bj){this.firstChar=bh;
this.lastChar=bi;
this.map=bj;
},{render:function(bh){bh.indent("/CIDInit /ProcSet findresource begin");
bh.indent("12 dict begin");
bh.indent("begincmap");
bh.indent("/CIDSystemInfo <<");
bh.indent("  /Registry (Adobe)");
bh.indent("  /Ordering (UCS)");
bh.indent("  /Supplement 0");
bh.indent(">> def");
bh.indent("/CMapName /Adobe-Identity-UCS def");
bh.indent("/CMapType 2 def");
bh.indent("1 begincodespacerange");
bh.indent("  <0000><ffff>");
bh.indent("endcodespacerange");
var bi=this;
bh.indent(bi.lastChar-bi.firstChar+1," beginbfchar");
bh.withIndent(function(){for(var bj=bi.firstChar;
bj<=bi.lastChar;
++bj){var bm=bi.map[bj];
var bl=bb([bm]);
bh.indent("<",bg(bj.toString(16),4),">","<");
for(var bk=0;
bk<bl.length;
++bk){bh(bg(bl.charCodeAt(bk).toString(16),4));
}bh(">");
}});
bh.indent("endbfchar");
bh.indent("endcmap");
bh.indent("CMapName currentdict /CMap defineresource pop");
bh.indent("end");
bh.indent("end");
}});
function ag(bh){return bh.map(function(bi){return S(bi)?ag(bi):typeof bi=="number"?(Math.round(bi*1000)/1000).toFixed(3):bi;
}).join(" ");
}function g(bn,bo,bk,bh,bp,bl,bi){var bm=ag([bo,bk,bh,bp,bl,bi]);
var bj=bn.GRAD_COL_FUNCTIONS[bm];
if(!bj){bj=bn.GRAD_COL_FUNCTIONS[bm]=bn.attach(new aA({FunctionType:2,Domain:[0,1],Range:[0,1,0,1,0,1],N:1,C0:[bo,bk,bh],C1:[bp,bl,bi]}));
}return bj;
}function j(bl,bh,bi){var bk=ag([bh,bi]);
var bj=bl.GRAD_OPC_FUNCTIONS[bk];
if(!bj){bj=bl.GRAD_OPC_FUNCTIONS[bk]=bl.attach(new aA({FunctionType:2,Domain:[0,1],Range:[0,1],N:1,C0:[bh],C1:[bi]}));
}return bj;
}function af(bq,bt){var bm=false;
var bp=[];
var bi=[];
var bo=[];
var bl=[];
var bn,br,bj,bs,bk;
for(bn=1;
bn<bt.length;
++bn){br=bt[bn-1];
bj=bt[bn];
bs=br.color;
bk=bj.color;
bi.push(g(bq,bs.r,bs.g,bs.b,bk.r,bk.g,bk.b));
if(bs.a<1||bk.a<1){bm=true;
}bo.push(bj.offset);
bl.push(0,1);
}if(bm){for(bn=1;
bn<bt.length;
++bn){br=bt[bn-1];
bj=bt[bn];
bs=br.color;
bk=bj.color;
bp.push(j(bq,bs.a,bk.a));
}}bo.pop();
return{hasAlpha:bm,colors:bh(bi),opacities:bm?bh(bp):null};
function bh(bu){if(bu.length==1){return bu[0];
}return{FunctionType:3,Functions:bu,Domain:[0,1],Bounds:bo,Encode:bl};
}}function f(bn,bm,bp,bj,bk,bi){var bo,bl;
if(!bi){var bh=[bm].concat(bj);
bp.forEach(function(bq){bh.push(bq.offset,bq.color.r,bq.color.g,bq.color.b);
});
bl=ag(bh);
bo=bn.GRAD_COL[bl];
}if(!bo){bo=new aA({Type:a("Shading"),ShadingType:bm?3:2,ColorSpace:a("DeviceRGB"),Coords:bj,Domain:[0,1],Function:bk,Extend:[true,true]});
bn.attach(bo);
bo._resourceName="S"+ ++aU;
if(bl){bn.GRAD_COL[bl]=bo;
}}return bo;
}function i(bo,bm,bp,bj,bk,bi){var bn,bl;
if(!bi){var bh=[bm].concat(bj);
bp.forEach(function(bq){bh.push(bq.offset,bq.color.a);
});
bl=ag(bh);
bn=bo.GRAD_OPC[bl];
}if(!bn){bn=new aA({Type:a("ExtGState"),AIS:false,CA:1,ca:1,SMask:{Type:a("Mask"),S:a("Luminosity"),G:bo.attach(new aL("/a0 gs /s0 sh",{Type:a("XObject"),Subtype:a("Form"),FormType:1,BBox:bi?[bi.left,bi.top+bi.height,bi.left+bi.width,bi.top]:[0,1,1,0],Group:{Type:a("Group"),S:a("Transparency"),CS:a("DeviceGray"),I:true},Resources:{ExtGState:{a0:{CA:1,ca:1}},Shading:{s0:{ColorSpace:a("DeviceGray"),Coords:bj,Domain:[0,1],ShadingType:bm?3:2,Function:bk,Extend:[true,true]}}}}))}});
bo.attach(bn);
bn._resourceName="O"+ ++aU;
if(bl){bo.GRAD_OPC[bl]=bn;
}}return bn;
}function h(bn,bk,bh){var bl=bk.type=="radial";
var bj=af(bn,bk.stops);
var bi=bl?[bk.start.x,bk.start.y,bk.start.r,bk.end.x,bk.end.y,bk.end.r]:[bk.start.x,bk.start.y,bk.end.x,bk.end.y];
var bo=f(bn,bl,bk.stops,bi,bj.colors,bk.userSpace&&bh);
var bm=bj.hasAlpha?i(bn,bl,bk.stops,bi,bj.opacities,bk.userSpace&&bh):null;
return{hasAlpha:bj.hasAlpha,shading:bo,opacity:bm};
}var aH=n(function aH(bh,bi){this._pdf=bh;
this._rcount=0;
this._textMode=false;
this._fontResources={};
this._gsResources={};
this._xResources={};
this._patResources={};
this._shResources={};
this._opacity=1;
this._matrix=[1,0,0,1,0,0];
this._annotations=[];
this._font=null;
this._fontSize=null;
this._contextStack=[];
bi=this.props=bi||{};
bi.Type=a("Page");
bi.ProcSet=[a("PDF"),a("Text"),a("ImageB"),a("ImageC"),a("ImageI")];
bi.Resources=new aA({Font:new aA(this._fontResources),ExtGState:new aA(this._gsResources),XObject:new aA(this._xResources),Pattern:new aA(this._patResources),Shading:new aA(this._shResources)});
bi.Annots=this._annotations;
},{_out:function(){this._content.data.apply(null,arguments);
},transform:function(bh,bi,bj,bk,bl,bm){if(!U(arguments)){this._matrix=ao(arguments,this._matrix);
this._out(bh," ",bi," ",bj," ",bk," ",bl," ",bm," cm");
this._out(ar);
}},translate:function(bh,bi){this.transform(1,0,0,1,bh,bi);
},scale:function(bh,bi){this.transform(bh,0,0,bi,0,0);
},rotate:function(bh){var bi=Math.cos(bh),bj=Math.sin(bh);
this.transform(bi,bj,-bj,bi,0,0);
},beginText:function(){this._textMode=true;
this._out("BT",ar);
},endText:function(){this._textMode=false;
this._out("ET",ar);
},_requireTextMode:function(){if(!this._textMode){throw new Error("Text mode required; call page.beginText() first");
}},_requireFont:function(){if(!this._font){throw new Error("No font selected; call page.setFont() first");
}},setFont:function(bh,bi){this._requireTextMode();
if(bh==null){bh=this._font;
}else{if(!(bh instanceof aC)){bh=this._pdf.getFont(bh);
}}if(bi==null){bi=this._fontSize;
}this._fontResources[bh._resourceName]=bh;
this._font=bh;
this._fontSize=bi;
this._out(bh._resourceName," ",bi," Tf",ar);
},setTextLeading:function(bh){this._requireTextMode();
this._out(bh," TL",ar);
},setTextRenderingMode:function(bh){this._requireTextMode();
this._out(bh," Tr",ar);
},showText:function(bk,bi){this._requireFont();
if(bk.length>1&&bi&&this._font instanceof aC){var bh=this._font.getTextWidth(this._fontSize,bk);
var bj=bi/bh*100;
this._out(bj," Tz ");
}this._out(this._font.encodeText(bk)," Tj",ar);
},showTextNL:function(bh){this._requireFont();
this._out(this._font.encodeText(bh)," '",ar);
},addLink:function(bk,bh){var bi=this._toPage({x:bh.left,y:bh.bottom});
var bj=this._toPage({x:bh.right,y:bh.top});
this._annotations.push(new aA({Type:a("Annot"),Subtype:a("Link"),Rect:[bi.x,bi.y,bj.x,bj.y],Border:[0,0,0],A:new aA({Type:a("Action"),S:a("URI"),URI:new aM(bk)})}));
},setStrokeColor:function(bj,bi,bh){this._out(bj," ",bi," ",bh," RG",ar);
},setOpacity:function(bh){this.setFillOpacity(bh);
this.setStrokeOpacity(bh);
this._opacity*=bh;
},setStrokeOpacity:function(bi){if(bi<1){var bh=this._pdf.getOpacityGS(this._opacity*bi,true);
this._gsResources[bh._resourceName]=bh;
this._out(bh._resourceName," gs",ar);
}},setFillColor:function(bj,bi,bh){this._out(bj," ",bi," ",bh," rg",ar);
},setFillOpacity:function(bi){if(bi<1){var bh=this._pdf.getOpacityGS(this._opacity*bi,false);
this._gsResources[bh._resourceName]=bh;
this._out(bh._resourceName," gs",ar);
}},gradient:function(bj,bh){this.save();
this.rect(bh.left,bh.top,bh.width,bh.height);
this.clip();
if(!bj.userSpace){this.transform(bh.width,0,0,bh.height,bh.left,bh.top);
}var bi=h(this._pdf,bj,bh);
var bl=bi.shading._resourceName,bk;
this._shResources[bl]=bi.shading;
if(bi.hasAlpha){bk=bi.opacity._resourceName;
this._gsResources[bk]=bi.opacity;
this._out("/"+bk+" gs ");
}this._out("/"+bl+" sh",ar);
this.restore();
},setDashPattern:function(bh,bi){this._out(bh," ",bi," d",ar);
},setLineWidth:function(bh){this._out(bh," w",ar);
},setLineCap:function(bh){this._out(bh," J",ar);
},setLineJoin:function(bh){this._out(bh," j",ar);
},setMitterLimit:function(bh){this._out(bh," M",ar);
},save:function(){this._contextStack.push(this._context());
this._out("q",ar);
},restore:function(){this._out("Q",ar);
this._context(this._contextStack.pop());
},moveTo:function(bh,bi){this._out(bh," ",bi," m",ar);
},lineTo:function(bh,bi){this._out(bh," ",bi," l",ar);
},bezier:function(bh,bk,bi,bl,bj,bm){this._out(bh," ",bk," ",bi," ",bl," ",bj," ",bm," c",ar);
},bezier1:function(bh,bj,bi,bk){this._out(bh," ",bj," ",bi," ",bk," y",ar);
},bezier2:function(bh,bj,bi,bk){this._out(bh," ",bj," ",bi," ",bk," v",ar);
},close:function(){this._out("h",ar);
},rect:function(bj,bk,bi,bh){this._out(bj," ",bk," ",bi," ",bh," re",ar);
},ellipse:function(bm,bn,bk,bl){function bh(bo){return bm+bo;
}function bi(bo){return bn+bo;
}var bj=0.5522847498307936;
this.moveTo(bh(0),bi(bl));
this.bezier(bh(bk*bj),bi(bl),bh(bk),bi(bl*bj),bh(bk),bi(0));
this.bezier(bh(bk),bi(-bl*bj),bh(bk*bj),bi(-bl),bh(0),bi(-bl));
this.bezier(bh(-bk*bj),bi(-bl),bh(-bk),bi(-bl*bj),bh(-bk),bi(0));
this.bezier(bh(-bk),bi(bl*bj),bh(-bk*bj),bi(bl),bh(0),bi(bl));
},circle:function(bi,bj,bh){this.ellipse(bi,bj,bh,bh);
},stroke:function(){this._out("S",ar);
},nop:function(){this._out("n",ar);
},clip:function(){this._out("W n",ar);
},clipStroke:function(){this._out("W S",ar);
},closeStroke:function(){this._out("s",ar);
},fill:function(){this._out("f",ar);
},fillStroke:function(){this._out("B",ar);
},drawImage:function(bi){var bh=this._pdf.getImage(bi);
if(bh){this._xResources[bh._resourceName]=bh;
this._out(bh._resourceName," Do",ar);
}},comment:function(bi){var bh=this;
bi.split(/\r?\n/g).forEach(function(bj){bh._out("% ",bj,ar);
});
},_context:function(bh){if(bh!=null){this._opacity=bh.opacity;
this._matrix=bh.matrix;
}else{return{opacity:this._opacity,matrix:this._matrix};
}},_toPage:function(bo){var bn=this._matrix;
var bh=bn[0],bi=bn[1],bj=bn[2],bk=bn[3],bl=bn[4],bm=bn[5];
return{x:bh*bo.x+bj*bo.y+bl,y:bi*bo.x+bk*bo.y+bm};
}},aA);
function bd(bh){return bh.replace(/^\s*(['"])(.*)\1\s*$/,"$2");
}function ay(bh){var bk=/^\s*((normal|italic)\s+)?((normal|small-caps)\s+)?((normal|bold|\d+)\s+)?(([0-9.]+)(px|pt))(\/(([0-9.]+)(px|pt)|normal))?\s+(.*?)\s*$/i;
var bj=bk.exec(bh);
if(!bj){return{fontSize:12,fontFamily:"sans-serif"};
}var bi=bj[8]?parseInt(bj[8],10):12;
return{italic:bj[2]&&bj[2].toLowerCase()=="italic",variant:bj[4],bold:bj[6]&&/bold|700/i.test(bj[6]),fontSize:bi,lineHeight:bj[12]?bj[12]=="normal"?bi:parseInt(bj[12],10):null,fontFamily:bj[14].split(/\s*,\s*/g).map(bd)};
}function G(bl){function bj(bn){if(bl.bold){bn+="|bold";
}if(bl.italic){bn+="|italic";
}return bn.toLowerCase();
}var bh=bl.fontFamily;
var bk,bm;
if(bh instanceof Array){for(var bi=0;
bi<bh.length;
++bi){bk=bj(bh[bi]);
bm=E[bk];
if(bm){break;
}}}else{bm=E[bh.toLowerCase()];
}while(typeof bm=="function"){bm=bm();
}if(!bm){bm="Times-Roman";
}return bm;
}var E={serif:"Times-Roman","serif|bold":"Times-Bold","serif|italic":"Times-Italic","serif|bold|italic":"Times-BoldItalic","sans-serif":"Helvetica","sans-serif|bold":"Helvetica-Bold","sans-serif|italic":"Helvetica-Oblique","sans-serif|bold|italic":"Helvetica-BoldOblique",monospace:"Courier","monospace|bold":"Courier-Bold","monospace|italic":"Courier-Oblique","monospace|bold|italic":"Courier-BoldOblique",zapfdingbats:"ZapfDingbats","zapfdingbats|bold":"ZapfDingbats","zapfdingbats|italic":"ZapfDingbats","zapfdingbats|bold|italic":"ZapfDingbats"};
function F(bh,bi){bh=bh.toLowerCase();
E[bh]=function(){return E[bi];
};
E[bh+"|bold"]=function(){return E[bi+"|bold"];
};
E[bh+"|italic"]=function(){return E[bi+"|italic"];
};
E[bh+"|bold|italic"]=function(){return E[bi+"|bold|italic"];
};
}F("Times New Roman","serif");
F("Courier New","monospace");
F("Arial","sans-serif");
F("Helvetica","sans-serif");
F("Verdana","sans-serif");
F("Tahoma","sans-serif");
F("Georgia","sans-serif");
F("Monaco","monospace");
F("Andale Mono","monospace");
function o(bi,bj){if(arguments.length==1){for(var bh in bi){if(L(bi,bh)){o(bh,bi[bh]);
}}}else{bi=bi.toLowerCase();
E[bi]=bj;
switch(bi){case"dejavu sans":E["sans-serif"]=bj;
break;
case"dejavu sans|bold":E["sans-serif|bold"]=bj;
break;
case"dejavu sans|italic":E["sans-serif|italic"]=bj;
break;
case"dejavu sans|bold|italic":E["sans-serif|bold|italic"]=bj;
break;
case"dejavu serif":E.serif=bj;
break;
case"dejavu serif|bold":E["serif|bold"]=bj;
break;
case"dejavu serif|italic":E["serif|italic"]=bj;
break;
case"dejavu serif|bold|italic":E["serif|bold|italic"]=bj;
break;
case"dejavu mono":E.monospace=bj;
break;
case"dejavu mono|bold":E["monospace|bold"]=bj;
break;
case"dejavu mono|italic":E["monospace|italic"]=bj;
break;
case"dejavu mono|bold|italic":E["monospace|bold|italic"]=bj;
break;
}}}function ao(bh,bk){var bi=bh[0],bl=bh[1],bn=bh[2],bp=bh[3],br=bh[4],bt=bh[5];
var bj=bk[0],bm=bk[1],bo=bk[2],bq=bk[3],bs=bk[4],bu=bk[5];
return[bi*bj+bl*bo,bi*bm+bl*bq,bn*bj+bp*bo,bn*bm+bp*bq,br*bj+bt*bo+bs,br*bm+bt*bq+bu];
}function U(bh){return bh[0]===1&&bh[1]===0&&bh[2]===0&&bh[3]===1&&bh[4]===0&&bh[5]===0;
}var a5={fill:0,stroke:1,fillAndStroke:2,invisible:3,fillAndClip:4,strokeAndClip:5,fillStrokeClip:6,clip:7};
var a6=a5;
var m={dash:[4],dashDot:[4,2,1,2],dot:[1,2],longDash:[8,2],longDashDot:[8,2,1,2],longDashDotDot:[8,2,1,2,1,2],solid:[]};
var X={butt:0,round:1,square:2};
var Y={miter:0,round:1,bevel:2};
function aR(bm,bh){var bk=[],bn=[],bp=bm.options;
function bl(bs,bq,br){if(!br){br=bp;
}if(br.pdf&&br.pdf[bs]!=null){return br.pdf[bs];
}return bq;
}var bo=bl("multiPage");
bm.traverse(function(bq){r({Image:function(br){if(bn.indexOf(br.src())<0){bn.push(br.src());
}},Text:function(br){var bs=ay(br.options.font);
var bt=G(bs);
if(bk.indexOf(bt)<0){bk.push(bt);
}}},bq);
});
function bj(){if(--bi>0){return;
}var br=new aB({producer:bl("producer"),title:bl("title"),author:bl("author"),subject:bl("subject"),keywords:bl("keywords"),creator:bl("creator"),date:bl("date")});
function bq(bu){var bv=bu.options;
var bA=at(bu);
var bt=bA.bbox;
bu=bA.root;
var by=bl("paperSize",bl("paperSize","auto"),bv),bs=false;
if(by=="auto"){if(bt){var bz=bt.getSize();
by=[bz.width,bz.height];
bs=true;
var bw=bt.getOrigin();
bA=new x.Group();
bA.transform(new W.Matrix(1,0,0,1,-bw.x,-bw.y));
bA.append(bu);
bu=bA;
}else{by="A4";
}}var bx;
bx=br.addPage({paperSize:by,margin:bl("margin",bl("margin"),bv),addMargin:bs,landscape:bl("landscape",bl("landscape",false),bv)});
u(bu,bx,br);
}if(bo){bm.children.forEach(bq);
}else{bq(bm);
}bh(br.render(),br);
}var bi=2;
ab(bk,bj);
ad(bn,bj);
}function a8(bi,bh){aR(bi,function(bj){bh("data:application/pdf;base64,"+bj.base64());
});
}function a7(bi,bh){aR(bi,function(bj){bh(new window.Blob([bj.get()],{type:"application/pdf"}));
});
}function aV(bj,bi,bk,bh){if(window.Blob&&!a4.safari){a7(bj,function(bl){V.saveAs({dataURI:bl,fileName:bi});
if(bh){bh(bl);
}});
}else{a8(bj,function(bl){V.saveAs({dataURI:bl,fileName:bi,proxyURL:bk});
if(bh){bh(bl);
}});
}}function r(bj,bh){var bi=bj[bh.nodeType];
if(bi){return bi.call.apply(bi,arguments);
}return bh;
}function u(bh,bk,bl){if(bh.options._pdfDebug){bk.comment("BEGIN: "+bh.options._pdfDebug);
}var bm=bh.transform();
var bj=bh.opacity();
bk.save();
if(bj!=null&&bj<1){bk.setOpacity(bj);
}aY(bh,bk,bl);
aX(bh,bk,bl);
if(bm){var bi=bm.matrix();
bk.transform(bi.a,bi.b,bi.c,bi.d,bi.e,bi.f);
}aW(bh,bk,bl);
r({Path:z,MultiPath:y,Circle:t,Arc:s,Text:B,Image:w,Group:v,Rect:A},bh,bk,bl);
bk.restore();
if(bh.options._pdfDebug){bk.comment("END: "+bh.options._pdfDebug);
}}function aY(bj,bn){var bo=bj.stroke&&bj.stroke();
if(!bo){return;
}var bh=bo.color;
if(bh){bh=ax(bh);
if(bh==null){return;
}bn.setStrokeColor(bh.r,bh.g,bh.b);
if(bh.a!=1){bn.setStrokeOpacity(bh.a);
}}var bp=bo.width;
if(bp!=null){if(bp===0){return;
}bn.setLineWidth(bp);
}var bi=bo.dashType;
if(bi){bn.setDashPattern(m[bi],0);
}var bk=bo.lineCap;
if(bk){bn.setLineCap(X[bk]);
}var bl=bo.lineJoin;
if(bl){bn.setLineJoin(Y[bl]);
}var bm=bo.opacity;
if(bm!=null){bn.setStrokeOpacity(bm);
}}function aX(bi,bl){var bj=bi.fill&&bi.fill();
if(!bj){return;
}if(bj instanceof x.Gradient){return;
}var bh=bj.color;
if(bh){bh=ax(bh);
if(bh==null){return;
}bl.setFillColor(bh.r,bh.g,bh.b);
if(bh.a!=1){bl.setFillOpacity(bh.a);
}}var bk=bj.opacity;
if(bk!=null){bl.setFillOpacity(bk);
}}function aW(bi,bj,bk){var bh=bi.clip();
if(bh){b(bh,bj,bk);
bj.clip();
}}function aZ(bh){return bh&&(bh instanceof x.Gradient||bh.color&&!/^(none|transparent)$/i.test(bh.color)&&(bh.width==null||bh.width>0)&&(bh.opacity==null||bh.opacity>0));
}function am(bi,bn,bo,bs){var bk=bi.fill();
if(bk instanceof x.Gradient){if(bs){bn.clipStroke();
}else{bn.clip();
}var bm=bk instanceof x.RadialGradient;
var bq,bj;
if(bm){bq={x:bk.center().x,y:bk.center().y,r:0};
bj={x:bk.center().x,y:bk.center().y,r:bk.radius()};
}else{bq={x:bk.start().x,y:bk.start().y};
bj={x:bk.end().x,y:bk.end().y};
}var br=bk.stops.elements().map(function(bw){var bv=bw.offset();
if(/%$/.test(bv)){bv=parseFloat(bv)/100;
}else{bv=parseFloat(bv);
}var bu=ax(bw.color());
bu.a*=bw.opacity();
return{offset:bv,color:bu};
});
br.unshift(br[0]);
br.push(br[br.length-1]);
var bl={userSpace:bk.userSpace(),type:bm?"radial":"linear",start:bq,end:bj,stops:br};
var bh=bi.rawBBox();
var bt=bh.topLeft(),bp=bh.getSize();
bh={left:bt.x,top:bt.y,width:bp.width,height:bp.height};
bn.gradient(bl,bh);
return true;
}}function al(bh,bi,bj){if(aZ(bh.fill())&&aZ(bh.stroke())){if(!am(bh,bi,bj,true)){bi.fillStroke();
}}else{if(aZ(bh.fill())){if(!am(bh,bi,bj,false)){bi.fill();
}}else{if(aZ(bh.stroke())){bi.stroke();
}else{bi.nop();
}}}}function ak(bl,bk){var bm=bl.segments;
if(bm.length==4&&bl.options.closed){var bh=[];
for(var bi=0;
bi<bm.length;
++bi){if(bm[bi].controlIn()){return false;
}bh[bi]=bm[bi].anchor();
}var bj=bh[0].y==bh[1].y&&bh[1].x==bh[2].x&&bh[2].y==bh[3].y&&bh[3].x==bh[0].x||bh[0].x==bh[1].x&&bh[1].y==bh[2].y&&bh[2].x==bh[3].x&&bh[3].y==bh[0].y;
if(bj){bk.rect(bh[0].x,bh[0].y,bh[2].x-bh[0].x,bh[2].y-bh[0].y);
return true;
}}}function b(bj,bl,bm){var bq=bj.segments;
if(bq.length===0){return;
}if(!ak(bj,bl,bm)){for(var bn,bk=0;
bk<bq.length;
++bk){var bp=bq[bk];
var bh=bp.anchor();
if(!bn){bl.moveTo(bh.x,bh.y);
}else{var bo=bn.controlOut();
var bi=bp.controlIn();
if(bo&&bi){bl.bezier(bo.x,bo.y,bi.x,bi.y,bh.x,bh.y);
}else{bl.lineTo(bh.x,bh.y);
}}bn=bp;
}if(bj.options.closed){bl.close();
}}}function z(bh,bi,bj){b(bh,bi,bj);
al(bh,bi,bj);
}function y(bh,bj,bl){var bk=bh.paths;
for(var bi=0;
bi<bk.length;
++bi){b(bk[bi],bj,bl);
}al(bh,bj,bl);
}function t(bh,bj,bk){var bi=bh.geometry();
bj.circle(bi.center.x,bi.center.y,bi.radius);
al(bh,bj,bk);
}function s(bh,bj,bk){var bl=bh.geometry().curvePoints();
bj.moveTo(bl[0].x,bl[0].y);
for(var bi=1;
bi<bl.length;
){bj.bezier(bl[bi].x,bl[bi++].y,bl[bi].x,bl[bi++].y,bl[bi].x,bl[bi++].y);
}al(bh,bj,bk);
}function B(bh,bj){var bl=ay(bh.options.font);
var bk=bh._position;
var bi;
if(bh.fill()&&bh.stroke()){bi=a6.fillAndStroke;
}else{if(bh.fill()){bi=a6.fill;
}else{if(bh.stroke()){bi=a6.stroke;
}}}bj.transform(1,0,0,-1,bk.x,bk.y+bl.fontSize);
bj.beginText();
bj.setFont(G(bl),bl.fontSize);
bj.setTextRenderingMode(bi);
bj.showText(bh.content(),bh._pdfRect?bh._pdfRect.width():null);
bj.endText();
}function v(bi,bk,bl){if(bi._pdfLink){bk.addLink(bi._pdfLink.url,bi._pdfLink);
}var bh=bi.children;
for(var bj=0;
bj<bh.length;
++bj){u(bh[bj],bk,bl);
}}function w(bh,bi){var bm=bh.src();
if(!bm){return;
}var bj=bh.rect();
var bl=bj.getOrigin();
var bk=bj.getSize();
bi.transform(bk.width,0,0,-bk.height,bl.x,bl.y+bk.height);
bi.drawImage(bm);
}function A(bh,bj,bk){var bi=bh.geometry();
bj.rect(bi.origin.x,bi.origin.y,bi.size.width,bi.size.height);
al(bh,bj,bk);
}function ax(bi){var bh=V.parseColor(bi,true);
return bh?bh.toRGB():null;
}function at(bp){var bj=false;
var bm=W.Matrix.unit();
var bk=null;
var bi;
do{bi=false;
bp=bn(bp);
}while(bp&&bi);
return{root:bp,bbox:bk};
function bh(bs){bi=true;
return bs;
}function bq(bs){return bs.visible()&&bs.opacity()>0&&(aZ(bs.fill())||aZ(bs.stroke()));
}function bo(bs){var bt=[];
for(var bv=0;
bv<bs.length;
++bv){var bu=bn(bs[bv]);
if(bu!=null){bt.push(bu);
}}return bt;
}function br(bw,bt){var bu=bj;
var bv=bm;
if(bw.transform()){bm=bm.multiplyCopy(bw.transform().matrix());
}var bs=bw.clip();
if(bs){bs=bs.bbox();
if(bs){bs=bs.bbox(bm);
bj=bj?W.Rect.intersect(bj,bs):bs;
}}try{return bt();
}finally{bj=bu;
bm=bv;
}}function bl(bt){if(bj==null){return false;
}var bs=bt.rawBBox().bbox(bm);
if(bj&&bs){bs=W.Rect.intersect(bs,bj);
}return bs;
}function bn(bs){return br(bs,function(){if(!(bs instanceof x.Group||bs instanceof x.MultiPath)){var bt=bl(bs);
if(!bt){return bh(null);
}bk=bk?W.Rect.union(bk,bt):bt;
}return r({Path:function(bu){if(bu.segments.length===0||!bq(bu)){return bh(null);
}return bu;
},MultiPath:function(bv){if(!bq(bv)){return bh(null);
}var bu=new x.MultiPath(bv.options);
bu.paths=bo(bv.paths);
if(bu.paths.length===0){return bh(null);
}return bu;
},Circle:function(bu){if(!bq(bu)){return bh(null);
}return bu;
},Arc:function(bu){if(!bq(bu)){return bh(null);
}return bu;
},Text:function(bu){if(!/\S/.test(bu.content())||!bq(bu)){return bh(null);
}return bu;
},Image:function(bu){if(!(bu.visible()&&bu.opacity()>0)){return bh(null);
}return bu;
},Group:function(bv){var bu=new x.Group(bv.options);
bu.children=bo(bv.children);
bu._pdfLink=bv._pdfLink;
if(bv!==bp&&bu.children.length===0&&!bv._pdfLink){return bh(null);
}return bu;
},Rect:function(bu){if(!bq(bu)){return bh(null);
}return bu;
}},bs);
});
}}function C(bh,bj){var bk=be.createPromise();
for(var bi in bj){if(bi=="margin"&&bh.options.pdf&&bh.options.pdf._ignoreMargin){continue;
}bh.options.set("pdf."+bi,bj[bi]);
}a8(bh,bk.resolve);
return bk;
}V.deepExtend(V.pdf,{Document:aB,BinaryStream:d,defineFont:o,parseFontDef:ay,getFontURL:G,loadFonts:ab,loadImages:ad,getPaperOptions:H,TEXT_RENDERING_MODE:a5,exportPDF:C,saveAs:aV,toDataURL:a8,toBlob:a7,render:aR});
V.drawing.exportPDF=V.pdf.exportPDF;
V.drawing.pdf=V.pdf;
}(kendo));
return kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("pdf/mixins",["pdf/core"],b);
}(function(){(function(a,b){kendo.PDFMixin={extend:function(c){c.events.push("pdfExport");
c.options.pdf=this.options;
c.saveAsPDF=this.saveAsPDF;
c._drawPDF=this._drawPDF;
c._drawPDFShadow=this._drawPDFShadow;
},options:{fileName:"Export.pdf",proxyURL:"",paperSize:"auto",allPages:false,landscape:false,margin:null,title:null,author:null,subject:null,keywords:null,creator:"Kendo UI PDF Generator v."+kendo.version,date:null},saveAsPDF:function(){var e=new a.Deferred();
var f=e.promise();
var c={promise:f};
if(this.trigger("pdfExport",c)){return;
}var d=this.options.pdf;
d.multiPage=d.multiPage||d.allPages;
this._drawPDF(e).then(function(g){return kendo.drawing.exportPDF(g,d);
}).done(function(g){kendo.saveAs({dataURI:g,fileName:d.fileName,proxyURL:d.proxyURL,forceProxy:d.forceProxy,proxyTarget:d.proxyTarget});
e.resolve();
}).fail(function(g){e.reject(g);
});
return f;
},_drawPDF:function(c){var d=new a.Deferred();
kendo.drawing.drawDOM(this.wrapper).done(function(f){var e={page:f,pageNumber:1,progress:1,totalPages:1};
c.notify(e);
d.resolve(e.page);
}).fail(function(e){d.reject(e);
});
return d;
},_drawPDFShadow:function(e,d){e=e||{};
var g=this.wrapper;
var f=a("<div class='k-pdf-export-shadow'>");
if(e.width){f.css({width:e.width,overflow:"visible"});
}g.before(f);
f.append(e.content||g.clone(true,true));
var c=a.Deferred();
setTimeout(function(){var h=kendo.drawing.drawDOM(f,d);
h.always(function(){f.remove();
}).then(function(){c.resolve.apply(c,arguments);
}).fail(function(){c.reject.apply(c,arguments);
}).progress(function(){c.progress.apply(c,arguments);
});
},15);
return c.promise();
}};
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.pdf",["kendo.core","kendo.drawing","pdf/core","pdf/mixins"],b);
}(function(){var a={id:"pdf",name:"PDF export",description:"PDF Generation framework",mixin:true,category:"framework",depends:["core","drawing"]};
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
