(function(b,a){a("kendo.popup",["kendo.core"],b);
}(function(){var a={id:"popup",name:"Pop-up",category:"framework",depends:["core"],advanced:true};
(function(b,L){var u=window.kendo,K=u.ui,N=K.Widget,H=u.support,s=u.getOffset,B=u._outerWidth,A=u._outerHeight,z="open",l="close",o="deactivate",d="activate",k="center",v="left",E="right",I="top",j="bottom",c="absolute",t="hidden",i="body",w="location",D="position",M="visible",q="effects",e="k-state-active",f="k-state-border",g=/k-state-border-(\w+)/,h=".k-picker-wrap, .k-dropdown-wrap, .k-link",x="down",p=b(document.documentElement),O=b(window),F="scroll",n=H.transitions.css,J=n+"transform",r=b.extend,y=".kendoPopup",G=["font-size","font-family","font-stretch","font-style","font-weight","line-height"];
function m(P,Q){if(!P||!Q){return false;
}return P===Q||b.contains(P,Q);
}var C=N.extend({init:function(P,Q){var S=this,R;
Q=Q||{};
if(Q.isRtl){Q.origin=Q.origin||j+" "+E;
Q.position=Q.position||I+" "+E;
}N.fn.init.call(S,P,Q);
P=S.element;
Q=S.options;
S.collisions=Q.collision?Q.collision.split(" "):[];
S.downEvent=u.applyEventMap(x,u.guid());
if(S.collisions.length===1){S.collisions.push(S.collisions[0]);
}R=b(S.options.anchor).closest(".k-popup,.k-group").filter(":not([class^=km-])");
Q.appendTo=b(b(Q.appendTo)[0]||R[0]||document.body);
S.element.hide().addClass("k-popup k-group k-reset").toggleClass("k-rtl",!!Q.isRtl).css({position:c}).appendTo(Q.appendTo).on("mouseenter"+y,function(){S._hovered=true;
}).on("mouseleave"+y,function(){S._hovered=false;
});
S.wrapper=b();
if(Q.animation===false){Q.animation={open:{effects:{}},close:{hide:true,effects:{}}};
}r(Q.animation.open,{complete:function(){S.wrapper.css({overflow:M});
S._activated=true;
S._trigger(d);
}});
r(Q.animation.close,{complete:function(){S._animationClose();
}});
S._mousedownProxy=function(T){S._mousedown(T);
};
if(H.mobileOS.android){S._resizeProxy=function(T){setTimeout(function(){S._resize(T);
},600);
};
}else{S._resizeProxy=function(T){S._resize(T);
};
}if(Q.toggleTarget){b(Q.toggleTarget).on(Q.toggleEvent+y,b.proxy(S.toggle,S));
}},events:[z,d,l,o],options:{name:"Popup",toggleEvent:"click",origin:j+" "+v,position:I+" "+v,anchor:i,appendTo:null,collision:"flip fit",viewport:window,copyAnchorStyles:true,autosize:false,modal:false,adjustSize:{width:0,height:0},animation:{open:{effects:"slideIn:down",transition:true,duration:200},close:{duration:100,hide:true}}},_animationClose:function(){var Q=this;
var P=Q.wrapper.data(w);
Q.wrapper.hide();
if(P){Q.wrapper.css(P);
}if(Q.options.anchor!=i){Q._hideDirClass();
}Q._closing=false;
Q._trigger(o);
},destroy:function(){var S=this,Q=S.options,P=S.element.off(y),R;
N.fn.destroy.call(S);
if(Q.toggleTarget){b(Q.toggleTarget).off(y);
}if(!Q.modal){p.unbind(S.downEvent,S._mousedownProxy);
S._toggleResize(false);
}u.destroy(S.element.children());
P.removeData();
if(Q.appendTo[0]===document.body){R=P.parent(".k-animation-container");
if(R[0]){R.remove();
}else{P.remove();
}}},open:function(X,Y){var V=this,S={isFixed:!isNaN(parseInt(Y,10)),x:X,y:Y},R=V.element,U=V.options,Q,W,P=b(U.anchor),T=R[0]&&R.hasClass("km-widget");
if(!V.visible()){if(U.copyAnchorStyles){if(T&&G[0]=="font-size"){G.shift();
}R.css(u.getComputedStyles(P[0],G));
}if(R.data("animating")||V._trigger(z)){return;
}V._activated=false;
if(!U.modal){p.unbind(V.downEvent,V._mousedownProxy).bind(V.downEvent,V._mousedownProxy);
V._toggleResize(false);
V._toggleResize(true);
}V.wrapper=W=u.wrap(R,U.autosize).css({overflow:t,display:"block",position:c});
if(H.mobileOS.android){W.css(J,"translatez(0)");
}W.css(D);
if(b(U.appendTo)[0]==document.body){W.css(I,"-10000px");
}V.flipped=V._position(S);
Q=V._openAnimation();
if(U.anchor!=i){V._showDirClass(Q);
}R.data(q,Q.effects).kendoStop(true).kendoAnimate(Q);
}},_openAnimation:function(){var P=r(true,{},this.options.animation.open);
P.effects=u.parseEffects(P.effects,this.flipped);
return P;
},_hideDirClass:function(){var P=b(this.options.anchor);
var R=((P.attr("class")||"").match(g)||["","down"])[1];
var Q=f+"-"+R;
P.removeClass(Q).children(h).removeClass(e).removeClass(Q);
this.element.removeClass(f+"-"+u.directions[R].reverse);
},_showDirClass:function(P){var R=P.effects.slideIn?P.effects.slideIn.direction:"down";
var Q=f+"-"+R;
b(this.options.anchor).addClass(Q).children(h).addClass(e).addClass(Q);
this.element.addClass(f+"-"+u.directions[R].reverse);
},position:function(){if(this.visible()){this.flipped=this._position();
}},toggle:function(){var P=this;
P[P.visible()?l:z]();
},visible:function(){return this.element.is(":"+M);
},close:function(T){var U=this,S=U.options,V,P,R,Q;
if(U.visible()){V=U.wrapper[0]?U.wrapper:u.wrap(U.element).hide();
U._toggleResize(false);
if(U._closing||U._trigger(l)){U._toggleResize(true);
return;
}U.element.find(".k-popup").each(function(){var X=b(this),W=X.data("kendoPopup");
if(W){W.close(T);
}});
p.unbind(U.downEvent,U._mousedownProxy);
if(T){P={hide:true,effects:{}};
}else{P=r(true,{},S.animation.close);
R=U.element.data(q);
Q=P.effects;
if(!Q&&!u.size(Q)&&R&&u.size(R)){P.effects=R;
P.reverse=true;
}U._closing=true;
}U.element.kendoStop(true);
V.css({overflow:t});
U.element.kendoAnimate(P);
if(T){U._animationClose();
}}},_trigger:function(P){return this.trigger(P,{type:P});
},_resize:function(P){var Q=this;
if(H.resize.indexOf(P.type)!==-1){clearTimeout(Q._resizeTimeout);
Q._resizeTimeout=setTimeout(function(){Q._position();
Q._resizeTimeout=null;
},50);
}else{if(!Q._hovered||Q._activated&&Q.element.hasClass("k-list-container")){Q.close();
}}},_toggleResize:function(R){var Q=R?"on":"off";
var P=H.resize;
if(!(H.mobileOS.ios||H.mobileOS.android)){P+=" "+F;
}this._scrollableParents()[Q](F,this._resizeProxy);
O[Q](P,this._resizeProxy);
},_mousedown:function(R){var W=this,Q=W.element[0],T=W.options,P=b(T.anchor)[0],X=T.toggleTarget,V=u.eventTarget(R),U=b(V).closest(".k-popup"),S=U.parent().parent(".km-shim").length;
U=U[0];
if(!S&&U&&U!==W.element[0]){return;
}if(b(R.target).closest("a").data("rel")==="popover"){return;
}if(!m(Q,V)&&!m(P,V)&&!(X&&m(b(X)[0],V))){W.close();
}},_fit:function(Q,R,S){var P=0;
if(Q+R>S){P=S-(Q+R);
}if(Q<0){P=-Q;
}return P;
},_flip:function(R,V,P,W,S,U,Q){var T=0;
Q=Q||V;
if(U!==S&&U!==k&&S!==k){if(R+Q>W){T+=-(P+V);
}if(R+T<0){T+=P+V;
}}return T;
},_scrollableParents:function(){return b(this.options.anchor).parentsUntil("body").filter(function(Q,P){return u.isScrollable(P);
});
},_position:function(W){var al=this,U=al.element,aq=al.wrapper,ae=al.options,am=b(ae.viewport),au=H.zoomLevel(),Z=!!(am[0]==window&&window.innerWidth&&au<=1.02),Q=b(ae.anchor),af=ae.origin.toLowerCase().split(" "),aj=ae.position.toLowerCase().split(" "),S=al.collisions,ak,ag,ah,at=10002,Y=0,T=document.documentElement,aa,ao,ap,an;
if(ae.viewport===window){ao={top:window.pageYOffset||document.documentElement.scrollTop||0,left:window.pageXOffset||document.documentElement.scrollLeft||0};
}else{ao=am.offset();
}if(Z){ap=window.innerWidth;
an=window.innerHeight;
}else{ap=am.width();
an=am.height();
}if(Z&&T.scrollHeight-T.clientHeight>0){ap-=u.support.scrollbar();
}ak=Q.parents().filter(aq.siblings());
if(ak[0]){ah=Math.max(Number(ak.css("zIndex")),0);
if(ah){at=ah+10;
}else{ag=Q.parentsUntil(ak);
for(aa=ag.length;
Y<aa;
Y++){ah=Number(b(ag[Y]).css("zIndex"));
if(ah&&at<ah){at=ah+10;
}}}}aq.css("zIndex",at);
if(W&&W.isFixed){aq.css({left:W.x,top:W.y});
}else{aq.css(al._align(af,aj));
}var ai=s(aq,D,Q[0]===aq.offsetParent()[0]),ac=s(aq),R=Q.offsetParent().parent(".k-animation-container,.k-popup,.k-group");
if(R.length){ai=s(aq,D,true);
ac=s(aq);
}ac.top-=ao.top;
ac.left-=ao.left;
if(!al.wrapper.data(w)){aq.data(w,r({},ai));
}var ad=r({},ac),ab=r({},ai),P=ae.adjustSize;
if(S[0]==="fit"){ab.top+=al._fit(ad.top,A(aq)+P.height,an/au);
}if(S[1]==="fit"){ab.left+=al._fit(ad.left,B(aq)+P.width,ap/au);
}var X=r({},ab);
var V=A(U);
var ar=A(aq);
if(!aq.height()&&V){ar=ar+V;
}if(S[0]==="flip"){ab.top+=al._flip(ad.top,V,A(Q),an/au,af[0],aj[0],ar);
}if(S[1]==="flip"){ab.left+=al._flip(ad.left,B(U),B(Q),ap/au,af[1],aj[1],B(aq));
}U.css(D,c);
aq.css(ab);
return ab.left!=X.left||ab.top!=X.top;
},_align:function(aa,ab){var ad=this,V=ad.wrapper,P=b(ad.options.anchor),af=aa[0],X=aa[1],ag=ab[0],Y=ab[1],R=s(P),T=b(ad.options.appendTo),U,ah=B(V),W=A(V),S=B(P),Q=A(P),ae=R.top,Z=R.left,ac=Math.round;
if(T[0]!=document.body){U=s(T);
ae-=U.top;
Z-=U.left;
}if(af===j){ae+=Q;
}if(af===k){ae+=ac(Q/2);
}if(ag===j){ae-=W;
}if(ag===k){ae-=ac(W/2);
}if(X===E){Z+=S;
}if(X===k){Z+=ac(S/2);
}if(Y===E){Z-=ah;
}if(Y===k){Z-=ac(ah/2);
}return{top:ae,left:Z};
}});
K.plugin(C);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
