(function(b,a){a("kendo.window",["kendo.draganddrop"],b);
}(function(){var a={id:"window",name:"Window",category:"web",description:"The Window widget displays content in a modal or non-modal HTML window.",depends:["draganddrop"],features:[{id:"window-fx",name:"Animation",description:"Support for animation",depends:["fx"]}]};
(function(b,aa){var v=window.kendo,ac=v.ui.Widget,l=v.ui.Draggable,t=b.isPlainObject,d=v._activeElement,O=v._outerWidth,N=v._outerHeight,R=b.proxy,q=b.extend,n=b.each,X=v.template,e="body",Y,L=".kendoWindow",B=".k-window",E=".k-window-title",F=E+"bar",C=".k-window-content",D=".k-resize-handle",y=".k-overlay",u="k-content-frame",G="k-i-loading",x="k-state-hover",w="k-state-focused",I="k-window-maximized",ab=":visible",r="hidden",h="cursor",M="open",c="activate",i="deactivate",f="close",S="refresh",J="minimize",H="maximize",W="resizeStart",U="resize",V="resizeEnd",m="dragstart",k="dragend",o="error",P="overflow",ag="zIndex",K=".k-window-actions .k-i-window-minimize,.k-window-actions .k-i-window-maximize",z=".k-i-pin",A=".k-i-unpin",Q=z+","+A,Z=".k-window-titlebar .k-window-action",T=".k-window-titlebar .k-i-refresh",s=v.isLocalUrl;
function j(ah){return typeof ah!="undefined";
}function g(aj,ai,ah){return Math.max(Math.min(parseInt(aj,10),ah===Infinity?ah:parseInt(ah,10)),parseInt(ai,10));
}function p(){return !this.type||this.type.toLowerCase().indexOf("script")>=0;
}var ad=ac.extend({init:function(aj,an){var aq=this,au,am={},ar,ai,ao,al=false,ah,at,ap=an&&an.actions&&!an.actions.length,ak;
ac.fn.init.call(aq,aj,an);
an=aq.options;
ao=an.position;
aj=aq.element;
ah=an.content;
if(ap){an.actions=[];
}aq.appendTo=b(an.appendTo);
if(ah&&!t(ah)){ah=an.content={url:ah};
}aj.find("script").filter(p).remove();
if(!aj.parent().is(aq.appendTo)&&(ao.top===aa||ao.left===aa)){if(aj.is(ab)){am=aj.offset();
al=true;
}else{ar=aj.css("visibility");
ai=aj.css("display");
aj.css({visibility:r,display:""});
am=aj.offset();
aj.css({visibility:ar,display:ai});
}if(ao.top===aa){ao.top=am.top;
}if(ao.left===aa){ao.left=am.left;
}}if(!j(an.visible)||an.visible===null){an.visible=aj.is(ab);
}au=aq.wrapper=aj.closest(B);
if(!aj.is(".k-content")||!au[0]){aj.addClass("k-window-content k-content");
aq._createWindow(aj,an);
au=aq.wrapper=aj.closest(B);
aq._dimensions();
}aq._position();
if(an.pinned){aq.pin(true);
}if(ah){aq.refresh(ah);
}if(an.visible){aq.toFront();
}at=au.children(C);
aq._tabindex(at);
if(an.visible&&an.modal){aq._overlay(au.is(ab)).css({opacity:0.5});
}au.on("mouseenter"+L,Z,R(aq._buttonEnter,aq)).on("mouseleave"+L,Z,R(aq._buttonLeave,aq)).on("click"+L,"> "+Z,R(aq._windowActionHandler,aq));
at.on("keydown"+L,R(aq._keydown,aq)).on("focus"+L,R(aq._focus,aq)).on("blur"+L,R(aq._blur,aq));
this._resizable();
this._draggable();
ak=aj.attr("id");
if(ak){ak=ak+"_wnd_title";
au.children(F).children(E).attr("id",ak);
at.attr({role:"dialog","aria-labelledby":ak});
}au.add(au.children(".k-resize-handle,"+F)).on("mousedown"+L,R(aq.toFront,aq));
aq.touchScroller=v.touchScroller(aj);
aq._resizeHandler=R(aq._onDocumentResize,aq);
aq._marker=v.guid().substring(0,8);
b(window).on("resize"+L+aq._marker,aq._resizeHandler);
if(an.visible){aq.trigger(M);
aq.trigger(c);
}v.notify(aq);
},_buttonEnter:function(ah){b(ah.currentTarget).addClass(x);
},_buttonLeave:function(ah){b(ah.currentTarget).removeClass(x);
},_focus:function(){this.wrapper.addClass(w);
},_blur:function(){this.wrapper.removeClass(w);
},_dimensions:function(){var ao=this.wrapper;
var al=this.options;
var an=al.width;
var ai=al.height;
var ak=al.maxHeight;
var ah=["minWidth","minHeight","maxWidth","maxHeight"];
this.title(al.title);
for(var aj=0;
aj<ah.length;
aj++){var am=al[ah[aj]]||"";
if(am!=Infinity){ao.css(ah[aj],am);
}}if(ak!=Infinity){this.element.css("maxHeight",ak);
}if(an){if(an.toString().indexOf("%")>0){ao.width(an);
}else{ao.width(g(an,al.minWidth,al.maxWidth));
}}else{ao.width("");
}if(ai){if(ai.toString().indexOf("%")>0){ao.height(ai);
}else{ao.height(g(ai,al.minHeight,al.maxHeight));
}}else{ao.height("");
}if(!al.visible){ao.hide();
}},_position:function(){var ai=this.wrapper,ah=this.options.position;
if(ah.top===0){ah.top=ah.top.toString();
}if(ah.left===0){ah.left=ah.left.toString();
}ai.css({top:ah.top||"",left:ah.left||""});
},_animationOptions:function(aj){var ah=this.options.animation;
var ai={open:{effects:{}},close:{hide:true,effects:{}}};
return ah&&ah[aj]||ai[aj];
},_resize:function(){v.resize(this.element.children());
},_resizable:function(){var ah=this.options.resizable;
var ai=this.wrapper;
if(this.resizing){ai.off("dblclick"+L).children(D).remove();
this.resizing.destroy();
this.resizing=null;
}if(ah){ai.on("dblclick"+L,F,R(function(aj){if(!b(aj.target).closest(".k-window-action").length){this.toggleMaximization();
}},this));
n("n e s w se sw ne nw".split(" "),function(ak,aj){ai.append(Y.resizeHandle(aj));
});
this.resizing=new af(this);
}ai=null;
},_draggable:function(){var ah=this.options.draggable;
if(this.dragging){this.dragging.destroy();
this.dragging=null;
}if(ah){this.dragging=new ae(this,ah.dragHandle||F);
}},_actions:function(){var ah=this.options.actions;
var aj=this.wrapper.children(F);
var ai=aj.find(".k-window-actions");
var ak=["maximize","minimize"];
ah=b.map(ah,function(al){return{name:ak.indexOf(al.toLowerCase())>-1?"window-"+al:al};
});
ai.html(v.render(Y.action,ah));
},setOptions:function(ah){ac.fn.setOptions.call(this,ah);
var ai=this.options.scrollable!==false;
this.restore();
this._dimensions();
this._position();
this._resizable();
this._draggable();
this._actions();
if(typeof ah.modal!=="undefined"){var aj=this.options.visible!==false;
this._overlay(ah.modal&&aj);
}this.element.css(P,ai?"":"hidden");
},events:[M,c,i,f,J,H,S,W,U,V,m,k,o],options:{name:"Window",animation:{open:{effects:{zoom:{direction:"in"},fade:{direction:"in"}},duration:350},close:{effects:{zoom:{direction:"out",properties:{scale:0.7}},fade:{direction:"out"}},duration:350,hide:true}},title:"",actions:["Close"],autoFocus:true,modal:false,resizable:true,draggable:true,minWidth:90,minHeight:50,maxWidth:Infinity,maxHeight:Infinity,pinned:false,scrollable:true,position:{},content:null,visible:null,height:null,width:null,appendTo:"body",isMaximized:false,isMinimized:false},_closable:function(){return b.inArray("close",b.map(this.options.actions,function(ah){return ah.toLowerCase();
}))>-1;
},_keydown:function(ai){var at=this,ar=at.options,an=v.keys,am=ai.keyCode,av=at.wrapper,aq,ak,ah=10,al=at.options.isMaximized,ap,ao,au,aj;
if(ai.target!=ai.currentTarget||at._closing){return;
}if(am==an.ESC&&at._closable()){at._close(false);
}if(ar.draggable&&!ai.ctrlKey&&!al){aq=v.getOffset(av);
if(am==an.UP){ak=av.css("top",aq.top-ah);
}else{if(am==an.DOWN){ak=av.css("top",aq.top+ah);
}else{if(am==an.LEFT){ak=av.css("left",aq.left-ah);
}else{if(am==an.RIGHT){ak=av.css("left",aq.left+ah);
}}}}}if(ar.resizable&&ai.ctrlKey&&!al){if(am==an.UP){ak=true;
ao=av.height()-ah;
}else{if(am==an.DOWN){ak=true;
ao=av.height()+ah;
}}if(am==an.LEFT){ak=true;
ap=av.width()-ah;
}else{if(am==an.RIGHT){ak=true;
ap=av.width()+ah;
}}if(ak){au=g(ap,ar.minWidth,ar.maxWidth);
aj=g(ao,ar.minHeight,ar.maxHeight);
if(!isNaN(au)){av.width(au);
at.options.width=au+"px";
}if(!isNaN(aj)){av.height(aj);
at.options.height=aj+"px";
}at.resize();
}}if(ak){ai.preventDefault();
}},_overlay:function(ai){var ah=this.appendTo.children(y),aj=this.wrapper;
if(!ah.length){ah=b("<div class='k-overlay' />");
}ah.insertBefore(aj[0]).toggle(ai).css(ag,parseInt(aj.css(ag),10)-1);
return ah;
},_actionForIcon:function(ah){var ai=/\bk-i(-\w+)+\b/.exec(ah[0].className)[0];
return{"k-i-close":"_close","k-i-window-maximize":"maximize","k-i-window-minimize":"minimize","k-i-window-restore":"restore","k-i-refresh":"refresh","k-i-pin":"pin","k-i-unpin":"unpin"}[ai];
},_windowActionHandler:function(ai){if(this._closing){return;
}var aj=b(ai.target).closest(".k-window-action").find(".k-icon");
var ah=this._actionForIcon(aj);
if(ah){ai.preventDefault();
this[ah]();
return false;
}},_modals:function(){var ah=this;
var ai=b(B).filter(function(){var aj=b(this);
var ak=ah._object(aj);
var al=ak&&ak.options;
return al&&al.modal&&al.visible&&al.appendTo===ah.options.appendTo&&aj.is(ab);
}).sort(function(aj,ak){return +b(aj).css("zIndex")-+b(ak).css("zIndex");
});
ah=null;
return ai;
},_object:function(ai){var ah=ai.children(C);
var aj=v.widgetInstance(ah);
if(aj instanceof ad){return aj;
}return aa;
},center:function(){var an=this,ak=an.options.position,ao=an.wrapper,ah=b(window),am=0,al=0,aj,ai;
if(an.options.isMaximized){return an;
}if(!an.options.pinned){am=ah.scrollTop();
al=ah.scrollLeft();
}ai=al+Math.max(0,(ah.width()-ao.width())/2);
aj=am+Math.max(0,(ah.height()-ao.height()-parseInt(ao.css("paddingTop"),10))/2);
ao.css({left:ai,top:aj});
ak.top=aj;
ak.left=ai;
return an;
},title:function(ai){var aj=this,an=aj.wrapper,ah=aj.options,al=an.children(F),ak=al.children(E),am;
if(!arguments.length){return ak.html();
}if(ai===false){an.addClass("k-window-titleless");
al.remove();
}else{if(!al.length){an.prepend(Y.titlebar(ah));
aj._actions();
al=an.children(F);
}else{ak.html(ai);
}am=parseInt(N(al),10);
an.css("padding-top",am);
al.css("margin-top",-am);
}aj.options.title=ai;
return aj;
},content:function(aj,ai){var ah=this.wrapper.children(C),ak=ah.children(".km-scroll-container");
ah=ak[0]?ak:ah;
if(!j(aj)){return ah.html();
}this.angular("cleanup",function(){return{elements:ah.children()};
});
v.destroy(this.element.children());
ah.empty().html(aj);
this.angular("compile",function(){var al=[];
for(var am=ah.length;
--am>=0;
){al.push({dataItem:ai});
}return{elements:ah.children(),data:al};
});
return this;
},open:function(){var ao=this,ap=ao.wrapper,aj=ao.options,an=this._animationOptions("open"),ah=ap.children(C),al,ak,ai=b(document);
if(!ao.trigger(M)){if(ao._closing){ap.kendoStop(true,true);
}ao._closing=false;
ao.toFront();
if(aj.autoFocus){ao.element.focus();
}aj.visible=true;
if(aj.modal){ak=!!ao._modals().length;
al=ao._overlay(ak);
al.kendoStop(true,true);
if(an.duration&&v.effects.Fade&&!ak){var am=v.fx(al).fadeIn();
am.duration(an.duration||0);
am.endValue(0.5);
am.play();
}else{al.css("opacity",0.5);
}al.show();
}if(!ap.is(ab)){ah.css(P,r);
ap.show().kendoStop().kendoAnimate({effects:an.effects,duration:an.duration,complete:R(this._activate,this)});
}}if(aj.isMaximized){ao._documentScrollTop=ai.scrollTop();
ao._documentScrollLeft=ai.scrollLeft();
b("html, body").css(P,r);
}return ao;
},_activate:function(){var ah=this.options.scrollable!==false;
if(this.options.autoFocus){this.element.focus();
}this.element.css(P,ah?"":"hidden");
v.resize(this.element.children());
this.trigger(c);
},_removeOverlay:function(an){var aj=this._modals();
var ak=this.options;
var ai=ak.modal&&!aj.length;
var al=ak.modal?this._overlay(true):b(aa);
var ah=this._animationOptions("close");
if(ai){if(!an&&ah.duration&&v.effects.Fade){var am=v.fx(al).fadeOut();
am.duration(ah.duration||0);
am.startValue(0.5);
am.play();
}else{this._overlay(false).remove();
}}else{if(aj.length){this._object(aj.last())._overlay(true);
}}},_close:function(al){var am=this,an=am.wrapper,aj=am.options,ak=this._animationOptions("open"),ai=this._animationOptions("close"),ah=b(document);
if(an.is(ab)&&!am.trigger(f,{userTriggered:!al})){if(am._closing){return;
}am._closing=true;
aj.visible=false;
b(B).each(function(aq,ap){var ao=b(ap).children(C);
if(ap!=an&&ao.find("> ."+u).length>0){ao.children(y).remove();
}});
this._removeOverlay();
an.kendoStop().kendoAnimate({effects:ai.effects||ak.effects,reverse:ai.reverse===true,duration:ai.duration,complete:R(this._deactivate,this)});
}if(am.options.isMaximized){b("html, body").css(P,"");
if(am._documentScrollTop&&am._documentScrollTop>0){ah.scrollTop(am._documentScrollTop);
}if(am._documentScrollLeft&&am._documentScrollLeft>0){ah.scrollLeft(am._documentScrollLeft);
}}},_deactivate:function(){var ai=this;
ai.wrapper.hide().css("opacity","");
ai.trigger(i);
if(ai.options.modal){var ah=ai._object(ai._modals().last());
if(ah){ah.toFront();
}}},close:function(){this._close(true);
return this;
},_actionable:function(ah){return b(ah).is(Z+","+Z+" .k-icon,:input,a");
},_shouldFocus:function(aj){var ah=d(),ai=this.element;
return this.options.autoFocus&&!b(ah).is(ai)&&!this._actionable(aj)&&(!ai.find(ah).length||!ai.find(aj).length);
},toFront:function(ai){var am=this,ao=am.wrapper,ah=ao[0],ap=+ao.css(ag),aj=ap,al=ai&&ai.target||null;
b(B).each(function(at,ar){var au=b(ar),av=au.css(ag),aq=au.children(C);
if(!isNaN(av)){ap=Math.max(+av,ap);
}if(ar!=ah&&aq.find("> ."+u).length>0){aq.append(Y.overlay);
}});
if(!ao[0].style.zIndex||aj<ap){ao.css(ag,ap+2);
}am.element.find("> .k-overlay").remove();
if(am._shouldFocus(al)){am.element.focus();
var ak=b(window).scrollTop(),an=parseInt(ao.position().top,10);
if(!am.options.pinned&&an>0&&an<ak){if(ak>0){b(window).scrollTop(an);
}else{ao.css("top",ak);
}}}ao=null;
return am;
},toggleMaximization:function(){if(this._closing){return this;
}return this[this.options.isMaximized?"restore":"maximize"]();
},restore:function(){var al=this;
var aj=al.options;
var ai=aj.minHeight;
var ak=al.restoreOptions;
var ah=b(document);
if(!aj.isMaximized&&!aj.isMinimized){return al;
}if(ai&&ai!=Infinity){al.wrapper.css("min-height",ai);
}al.wrapper.css({position:aj.pinned?"fixed":"absolute",left:ak.left,top:ak.top,width:ak.width,height:ak.height}).removeClass(I).find(".k-window-content,.k-resize-handle").show().end().find(".k-window-titlebar .k-i-window-restore").parent().remove().end().end().find(K).parent().show().end().end().find(Q).parent().show();
al.options.width=ak.width;
al.options.height=ak.height;
b("html, body").css(P,"");
if(this._documentScrollTop&&this._documentScrollTop>0){ah.scrollTop(this._documentScrollTop);
}if(this._documentScrollLeft&&this._documentScrollLeft>0){ah.scrollLeft(this._documentScrollLeft);
}aj.isMaximized=aj.isMinimized=false;
al.resize();
return al;
},_sizingAction:function(ah,ai){var al=this,am=al.wrapper,ak=am[0].style,aj=al.options;
if(aj.isMaximized||aj.isMinimized){return al;
}al.restoreOptions={width:ak.width,height:ak.height};
am.children(D).hide().end().children(F).find(K).parent().hide().eq(0).before(Y.action({name:"window-restore"}));
ai.call(al);
al.wrapper.children(F).find(Q).parent().toggle(ah!=="maximize");
al.trigger(ah);
return al;
},maximize:function(){this._sizingAction("maximize",function(){var aj=this,ak=aj.wrapper,ai=ak.position(),ah=b(document);
q(aj.restoreOptions,{left:ai.left,top:ai.top});
ak.css({left:0,top:0,position:"fixed"}).addClass(I);
this._documentScrollTop=ah.scrollTop();
this._documentScrollLeft=ah.scrollLeft();
b("html, body").css(P,r);
aj.options.isMaximized=true;
aj._onDocumentResize();
});
return this;
},isMaximized:function(){return this.options.isMaximized;
},minimize:function(){this._sizingAction("minimize",function(){var ah=this;
ah.wrapper.css({height:"",minHeight:""});
ah.element.hide();
ah.options.isMinimized=true;
});
return this;
},isMinimized:function(){return this.options.isMinimized;
},pin:function(ah){var aj=this,al=b(window),am=aj.wrapper,ak=parseInt(am.css("top"),10),ai=parseInt(am.css("left"),10);
if(ah||!aj.options.pinned&&!aj.options.isMaximized){am.css({position:"fixed",top:ak-al.scrollTop(),left:ai-al.scrollLeft()});
am.children(F).find(z).addClass("k-i-unpin").removeClass("k-i-pin");
aj.options.pinned=true;
}},unpin:function(){var ai=this,ak=b(window),al=ai.wrapper,aj=parseInt(al.css("top"),10),ah=parseInt(al.css("left"),10);
if(ai.options.pinned&&!ai.options.isMaximized){al.css({position:"",top:aj+ak.scrollTop(),left:ah+ak.scrollLeft()});
al.children(F).find(A).addClass("k-i-pin").removeClass("k-i-unpin");
ai.options.pinned=false;
}},_onDocumentResize:function(){var ai=this,al=ai.wrapper,ak=b(window),am=v.support.zoomLevel(),aj,ah;
if(!ai.options.isMaximized){return;
}aj=ak.width()/am;
ah=ak.height()/am-parseInt(al.css("padding-top"),10);
al.css({width:aj,height:ah});
ai.options.width=aj;
ai.options.height=ah;
ai.resize();
},refresh:function(ak){var am=this,aj=am.options,ah=b(am.element),ai,al,an;
if(!t(ak)){ak={url:ak};
}ak=q({},aj.content,ak);
al=j(aj.iframe)?aj.iframe:ak.iframe;
an=ak.url;
if(an){if(!j(al)){al=!s(an);
}if(!al){am._ajaxRequest(ak);
}else{ai=ah.find("."+u)[0];
if(ai){ai.src=an||ai.src;
}else{ah.html(Y.contentFrame(q({},aj,{content:ak})));
}ah.find("."+u).unbind("load"+L).on("load"+L,R(this._triggerRefresh,this));
}}else{if(ak.template){am.content(X(ak.template)({}));
}am.trigger(S);
}ah.toggleClass("k-window-iframecontent",!!al);
return am;
},_triggerRefresh:function(){this.trigger(S);
},_ajaxComplete:function(){clearTimeout(this._loadingIconTimeout);
this.wrapper.find(T).removeClass(G);
},_ajaxError:function(ai,ah){this.trigger(o,{status:ah,xhr:ai});
},_ajaxSuccess:function(ah){return function(ai){var aj=ai;
if(ah){aj=X(ah)(ai||{});
}this.content(aj,ai);
this.element.prop("scrollTop",0);
this.trigger(S);
};
},_showLoading:function(){this.wrapper.find(T).addClass(G);
},_ajaxRequest:function(ah){this._loadingIconTimeout=setTimeout(R(this._showLoading,this),100);
b.ajax(q({type:"GET",dataType:"html",cache:false,error:R(this._ajaxError,this),complete:R(this._ajaxComplete,this),success:R(this._ajaxSuccess(ah.template),this)},ah));
},_destroy:function(){if(this.resizing){this.resizing.destroy();
}if(this.dragging){this.dragging.destroy();
}this.wrapper.off(L).children(C).off(L).end().find(".k-resize-handle,.k-window-titlebar").off(L);
b(window).off("resize"+L+this._marker);
clearTimeout(this._loadingIconTimeout);
ac.fn.destroy.call(this);
this.unbind(aa);
v.destroy(this.wrapper);
this._removeOverlay(true);
},destroy:function(){this._destroy();
this.wrapper.empty().remove();
this.wrapper=this.appendTo=this.element=b();
},_createWindow:function(){var ah=this.element,ak=this.options,ai,al,aj=v.support.isRtl(ah);
if(ak.scrollable===false){ah.css("overflow","hidden");
}al=b(Y.wrapper(ak));
ai=ah.find("iframe:not(.k-content)").map(function(){var am=this.getAttribute("src");
this.src="";
return am;
});
al.toggleClass("k-rtl",aj).appendTo(this.appendTo).append(ah).find("iframe:not(.k-content)").each(function(am){this.src=ai[am];
});
al.find(".k-window-title").css(aj?"left":"right",O(al.find(".k-window-actions"))+10);
ah.css("visibility","").show();
ah.find("[data-role=editor]").each(function(){var am=b(this).data("kendoEditor");
if(am){am.refresh();
}});
al=ah=null;
}});
Y={wrapper:X("<div class='k-widget k-window' />"),action:X("<a role='button' href='\\#' class='k-window-action k-link' aria-label='#= name #'><span class='k-icon k-i-#= name.toLowerCase() #'></span></a>"),titlebar:X("<div class='k-window-titlebar k-header'>&nbsp;<span class='k-window-title'>#= title #</span><div class='k-window-actions' /></div>"),overlay:"<div class='k-overlay' />",contentFrame:X("<iframe frameborder='0' title='#= title #' class='"+u+"' src='#= content.url #'>This page requires frames in order to show content</iframe>"),resizeHandle:X("<div class='k-resize-handle k-resize-#= data #'></div>")};
function af(ai){var ah=this;
ah.owner=ai;
ah._preventDragging=false;
ah._draggable=new l(ai.wrapper,{filter:">"+D,group:ai.wrapper.id+"-resizing",dragstart:R(ah.dragstart,ah),drag:R(ah.drag,ah),dragend:R(ah.dragend,ah)});
ah._draggable.userEvents.bind("press",R(ah.addOverlay,ah));
ah._draggable.userEvents.bind("release",R(ah.removeOverlay,ah));
}af.prototype={addOverlay:function(){this.owner.wrapper.append(Y.overlay);
},removeOverlay:function(){this.owner.wrapper.find(y).remove();
},dragstart:function(ah){var ai=this;
var aj=ai.owner;
var ak=aj.wrapper;
ai._preventDragging=aj.trigger(W);
if(ai._preventDragging){return;
}ai.elementPadding=parseInt(ak.css("padding-top"),10);
ai.initialPosition=v.getOffset(ak,"position");
ai.resizeDirection=ah.currentTarget.prop("className").replace("k-resize-handle k-resize-","");
ai.initialSize={width:ak.width(),height:ak.height()};
ai.containerOffset=v.getOffset(aj.appendTo,"position");
ak.children(D).not(ah.currentTarget).hide();
b(e).css(h,ah.currentTarget.css(h));
},drag:function(aj){if(this._preventDragging){return;
}var aq=this,au=aq.owner,av=au.wrapper,ap=au.options,ai=aq.resizeDirection,ah=aq.containerOffset,ak=aq.initialPosition,al=aq.initialSize,an,am,ar,at,aw=Math.max(aj.x.location,0),ax=Math.max(aj.y.location,0);
if(ai.indexOf("e")>=0){an=aw-ak.left-ah.left;
av.width(g(an,ap.minWidth,ap.maxWidth));
}else{if(ai.indexOf("w")>=0){at=ak.left+al.width+ah.left;
an=g(at-aw,ap.minWidth,ap.maxWidth);
av.css({left:at-an-ah.left,width:an});
}}var ao=ax;
if(au.options.pinned){ao-=b(window).scrollTop();
}if(ai.indexOf("s")>=0){am=ao-ak.top-aq.elementPadding-ah.top;
av.height(g(am,ap.minHeight,ap.maxHeight));
}else{if(ai.indexOf("n")>=0){ar=ak.top+al.height+ah.top;
am=g(ar-ao,ap.minHeight,ap.maxHeight);
av.css({top:ar-am-ah.top,height:am});
}}if(an){au.options.width=an+"px";
}if(am){au.options.height=am+"px";
}au.resize();
},dragend:function(ah){if(this._preventDragging){return;
}var ai=this,aj=ai.owner,ak=aj.wrapper;
ak.children(D).not(ah.currentTarget).show();
b(e).css(h,"");
if(aj.touchScroller){aj.touchScroller.reset();
}if(ah.keyCode==27){ak.css(ai.initialPosition).css(ai.initialSize);
}aj.trigger(V);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
function ae(aj,ah){var ai=this;
ai.owner=aj;
ai._preventDragging=false;
ai._draggable=new l(aj.wrapper,{filter:ah,group:aj.wrapper.id+"-moving",dragstart:R(ai.dragstart,ai),drag:R(ai.drag,ai),dragend:R(ai.dragend,ai),dragcancel:R(ai.dragcancel,ai)});
ai._draggable.userEvents.stopPropagation=false;
}ae.prototype={dragstart:function(aj){var al=this.owner,ak=al.element,ah=ak.find(".k-window-actions"),ai=v.getOffset(al.appendTo);
this._preventDragging=al.trigger(m);
if(this._preventDragging){return;
}al.initialWindowPosition=v.getOffset(al.wrapper,"position");
al.initialPointerPosition={left:aj.x.client,top:aj.y.client};
al.startPosition={left:aj.x.client-al.initialWindowPosition.left,top:aj.y.client-al.initialWindowPosition.top};
if(ah.length>0){al.minLeftPosition=O(ah)+parseInt(ah.css("right"),10)-O(ak);
}else{al.minLeftPosition=20-O(ak);
}al.minLeftPosition-=ai.left;
al.minTopPosition=-ai.top;
al.wrapper.append(Y.overlay).children(D).hide();
b(e).css(h,aj.currentTarget.css(h));
},drag:function(ah){if(this._preventDragging){return;
}var aj=this.owner;
var ai=aj.options.position;
ai.top=Math.max(ah.y.client-aj.startPosition.top,aj.minTopPosition);
ai.left=Math.max(ah.x.client-aj.startPosition.left,aj.minLeftPosition);
if(v.support.transforms){b(aj.wrapper).css("transform","translate("+(ah.x.client-aj.initialPointerPosition.left)+"px, "+(ah.y.client-aj.initialPointerPosition.top)+"px)");
}else{b(aj.wrapper).css(ai);
}},_finishDrag:function(){var ah=this.owner;
ah.wrapper.children(D).toggle(!ah.options.isMinimized).end().find(y).remove();
b(e).css(h,"");
},dragcancel:function(ah){if(this._preventDragging){return;
}this._finishDrag();
ah.currentTarget.closest(B).css(this.owner.initialWindowPosition);
},dragend:function(){if(this._preventDragging){return;
}b(this.owner.wrapper).css(this.owner.options.position).css("transform","");
this._finishDrag();
this.owner.trigger(k);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
v.ui.plugin(ad);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
