(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(j){this._size=j;
this._length=0;
this._map={};
},put:function(k,m){var l=this._map;
var j={key:k,value:m};
l[k]=j;
if(!this._head){this._head=this._tail=j;
}else{this._tail.newer=j;
j.older=this._tail;
this._tail=j;
}if(this._length>=this._size){l[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(k){var j=this._map[k];
if(j){if(j===this._head&&j!==this._tail){this._head=j.newer;
this._head.older=null;
}if(j!==this._tail){if(j.older){j.older.newer=j.newer;
j.newer.older=j.older;
}j.older=this._tail;
j.newer=null;
this._tail.newer=j;
this._tail=j;
}return j.value;
}}});
function g(k){var l=[];
for(var j in k){l.push(j+k[j]);
}return l.sort().join("");
}function d(l){var j=2166136261;
for(var k=0;
k<l.length;
++k){j+=(j<<1)+(j<<4)+(j<<7)+(j<<8)+(j<<24);
j^=l.charCodeAt(k);
}return j>>>0;
}function i(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;";
}var h=kendo.Class.extend({init:function(j){this._cache=new e(1000);
this.options=a.extend({},b,j);
},measure:function(s,q,k){if(!s){return i();
}var r=g(q);
var m=d(s+r);
var l=this._cache.get(m);
if(l){return l;
}var p=i();
var o=k||c;
var j=this._baselineMarker().cloneNode(false);
for(var n in q){var t=q[n];
if(typeof t!=="undefined"){o.style[n]=t;
}}o.textContent=s;
o.appendChild(j);
document.body.appendChild(o);
if(String(s).length){p.width=o.offsetWidth-this.options.baselineMarkerSize;
p.height=o.offsetHeight;
p.baseline=j.offsetTop+this.options.baselineMarkerSize;
}if(p.width>0&&p.height>0){this._cache.put(m,p);
}o.parentNode.removeChild(o);
return p;
},_baselineMarker:function(){var j=document.createElement("div");
j.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return j;
}});
h.current=new h();
function f(l,k,j){return h.current.measure(l,k,j);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:h,measureText:f,objectKey:g,hashKey:d});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("dataviz/core/kendo-core",["kendo.core","kendo.drawing"],b);
}(function(){(function(a){window.kendo.dataviz=window.kendo.dataviz||{};
var aw=kendo.drawing;
var cz=aw.util;
var bG=aw.Path;
var aW=aw.Group;
var M=kendo.Class;
var aO=kendo.geometry;
var bP=aO.Rect;
var K=aO.Circle;
var aP=aO.transform;
var b2=aO.Segment;
var aj=kendo.deepExtend;
var cG="x";
var cH="y";
var cu="top";
var A="bottom";
var be="left";
var bU="right";
var H="center";
var cF="width";
var aY="height";
var P=3;
var bm=Number.MAX_VALUE;
var bp=-Number.MAX_VALUE;
var aq=600;
var al=400;
var cE="#fff";
var z="#000";
var ak="12px sans-serif";
var ap=10;
var u="axisLabelClick";
var bw="noteClick";
var bx="noteHover";
var bD="outside";
var bu="none";
var L="circle";
var cx="triangle";
var T="cross";
var l="arc";
var a3="inside";
var cA="value";
var cb="string";
var bB="object";
var aa="date";
var aL=/\{\d+:?/;
var O={X:cG,Y:cH,WIDTH:cF,HEIGHT:aY,DEFAULT_HEIGHT:al,DEFAULT_WIDTH:aq,TOP:cu,LEFT:be,BOTTOM:A,RIGHT:bU,CENTER:H,COORD_PRECISION:P,DEFAULT_PRECISION:ap,CIRCLE:L,TRIANGLE:cx,CROSS:T,MAX_VALUE:bm,MIN_VALUE:bp,WHITE:cE,BLACK:z,DEFAULT_FONT:ak,AXIS_LABEL_CLICK:u,OUTSIDE:bD,INSIDE:a3,NONE:bu,NOTE_CLICK:bw,NOTE_HOVER:bx,VALUE:cA,STRING:cb,OBJECT:bB,DATE:aa,ARC:l,FORMAT_REGEX:aL};
function a7(X){return Array.isArray(X);
}function c(cL,Y){var X=a7(Y)?Y:[Y];
for(var cM=0;
cM<X.length;
cM++){var cK=X[cM];
if(cL.className.indexOf(cK)===-1){cL.className+=" "+cK;
}}}var b8=/\s+/g;
function bT(Y,X){if(Y&&Y.className){Y.className=Y.className.replace(X,"").replace(b8," ");
}}function h(cK){var Y=0.5;
if(cK.options.stroke&&kendo.drawing.util.defined(cK.options.stroke.width)){if(cK.options.stroke.width%2===0){Y=0;
}}for(var X=0;
X<cK.segments.length;
X++){cK.segments[X].anchor().round(0).translate(Y,Y);
}return cK;
}function N(X,Y){return -X.x*Y.y+X.y*Y.x<0;
}function ba(X){return typeof X==="object";
}function bc(X){return typeof X===cb;
}function a9(X){return typeof X==="number"&&!isNaN(X);
}function cc(X){if(a9(X)){return X+"px";
}return X;
}var b7=/width|height|top|left|bottom|right/i;
function bb(X){return b7.test(X);
}function aB(X,cO){var cP=bc(cO)?[cO]:cO;
if(a7(cP)){var cM={};
var cN=window.getComputedStyle(X);
for(var cL=0;
cL<cP.length;
cL++){var Y=cP[cL];
cM[Y]=bb(Y)?parseFloat(cN[Y]):cN[Y];
}return cM;
}else{if(ba(cO)){for(var cK in cO){X.style[cK]=cc(cO[cK]);
}}}}function aQ(cK,X){if(X===void 0){X=0;
}var Y={top:0,right:0,bottom:0,left:0};
if(typeof cK==="number"){Y[cu]=Y[bU]=Y[A]=Y[be]=cK;
}else{Y[cu]=cK[cu]||X;
Y[bU]=cK[bU]||X;
Y[A]=cK[A]||X;
Y[be]=cK[be]||X;
}return Y;
}var aF=/\[(\d+)\]|([^\.]+)/g;
var aS={};
aS["undefined"]=function(X){return X;
};
function aR(X){if(aS[X]){return aS[X];
}var Y=[];
X.replace(aF,function(cM,cL,cK){Y.push(kendo.drawing.util.defined(cL)?cL:cK);
});
aS[X]=function(cL){var cM=cL;
for(var cK=0;
cK<Y.length&&cM;
cK++){cM=cM[Y[cK]];
}return cM;
};
return aS[X];
}function aU(X,Y){var cL=X.length;
var cM=[];
for(var cK=0;
cK<cL;
cK++){if(Y(X[cK])){cM.push(X[cK]);
}}return cM;
}function aX(Y,X){if(Y.className){var cL=X.split(" ");
for(var cK=0;
cK<cL.length;
cK++){if(Y.className.indexOf(cL[cK])!==-1){return true;
}}}}function a0(Y,X){if(X){return X.indexOf(Y)!==-1;
}}function a5(cK,X,Y){return kendo.drawing.util.round(cK+(X-cK)*Y,P);
}var a4=M.extend({init:function(Y,X){this.observer=Y;
this.handlerMap=aj({},this.handlerMap,X);
},trigger:function(cL,X){var cN=this;
var cM=cN.observer;
var Y=cN.handlerMap;
var cK;
if(Y[cL]){cK=cM[Y[cL]](X);
}else{if(cM.trigger){cK=cM.trigger(cL,X);
}}return cK;
},requiresHandlers:function(Y){var cK=this;
if(this.observer.requiresHandlers){return this.observer.requiresHandlers(Y);
}for(var X=0;
X<Y.length;
X++){if(cK.handlerMap[Y[X]]){return true;
}}}});
function a8(X){return typeof X==="function";
}function bl(X,Y){var cL=X.length;
var cM=[];
for(var cK=0;
cK<cL;
cK++){var cN=Y(X[cK]);
if(kendo.drawing.util.defined(cN)){cM.push(cN);
}}return cM;
}function bt(Y){var X=0;
if(Y.wheelDelta){X=-Y.wheelDelta/120;
X=X>0?Math.ceil(X):Math.floor(X);
}if(Y.detail){X=kendo.drawing.util.round(Y.detail/3);
}return X;
}var bR=kendo.drawing.util;
var j=bR.append;
var y=bR.bindEvents;
var at=bR.defined;
var au=bR.deg;
var az=bR.elementOffset;
var aA=bR.elementSize;
var aD=bR.eventElement;
var aC=bR.eventCoordinates;
var bd=bR.last;
var bg=bR.limitValue;
var bC=bR.objectKey;
var bJ=bR.rad;
var bY=bR.round;
var cy=bR.unbindEvents;
var cB=bR.valueOrDefault;
var aK=M.extend({});
aK.fetchFonts=function(cK,X,cL){if(cL===void 0){cL={depth:0};
}var Y=5;
if(!cK||cL.depth>Y||!document.fonts){return;
}Object.keys(cK).forEach(function(cM){var cN=cK[cM];
if(cM==="dataSource"||cM[0]==="$"||!cN){return;
}if(cM==="font"){X.push(cN);
}else{if(typeof cN==="object"){cL.depth++;
aK.fetchFonts(cN,X,cL);
cL.depth--;
}}});
};
aK.loadFonts=function(cK,X){var cL=[];
if(cK.length>0&&document.fonts){try{cL=cK.map(function(cM){return document.fonts.load(cM);
});
}catch(Y){kendo.logToConsole(Y);
}Promise.all(cL).then(X,X);
}else{X();
}};
aK.preloadFonts=function(cK,X){var Y=[];
aK.fetchFonts(cK,Y);
aK.loadFonts(Y,X);
};
function b4(cK,X){var Y=cK.prototype;
if(Y.options){Y.options=aj({},Y.options,X);
}else{Y.options=X;
}}function b9(X){var cM=bm;
var cL=bp;
for(var Y=0,cK=X.length;
Y<cK;
Y++){var cN=X[Y];
if(cN!==null&&isFinite(cN)){cM=Math.min(cM,cN);
cL=Math.max(cL,cN);
}}return{min:cM===bm?undefined:cM,max:cL===bp?undefined:cL};
}var bH=M.extend({init:function(X,Y){this.x=X||0;
this.y=Y||0;
},clone:function(){return new bH(this.x,this.y);
},equals:function(X){return X&&this.x===X.x&&this.y===X.y;
},rotate:function(X,cM){var cP=bJ(cM);
var Y=Math.cos(cP);
var cO=Math.sin(cP);
var cK=X.x;
var cL=X.y;
var cN=this;
var cQ=cN.x;
var cR=cN.y;
this.x=bY(cK+(cQ-cK)*Y+(cR-cL)*cO,P);
this.y=bY(cL+(cR-cL)*Y-(cQ-cK)*cO,P);
return this;
},multiply:function(X){this.x*=X;
this.y*=X;
return this;
},distanceTo:function(cK){var X=this.x-cK.x;
var Y=this.y-cK.y;
return Math.sqrt(X*X+Y*Y);
}});
bH.onCircle=function(Y,X,cL){var cK=bJ(X);
return new bH(Y.x-cL*Math.cos(cK),Y.y-cL*Math.sin(cK));
};
var B=M.extend({init:function(X,cK,Y,cL){this.x1=X||0;
this.y1=cK||0;
this.x2=Y||0;
this.y2=cL||0;
},width:function(){return this.x2-this.x1;
},height:function(){return this.y2-this.y1;
},translate:function(X,Y){this.x1+=X;
this.x2+=X;
this.y1+=Y;
this.y2+=Y;
return this;
},move:function(cK,cL){var X=this.height();
var Y=this.width();
if(at(cK)){this.x1=cK;
this.x2=this.x1+Y;
}if(at(cL)){this.y1=cL;
this.y2=this.y1+X;
}return this;
},wrap:function(X){this.x1=Math.min(this.x1,X.x1);
this.y1=Math.min(this.y1,X.y1);
this.x2=Math.max(this.x2,X.x2);
this.y2=Math.max(this.y2,X.y2);
return this;
},wrapPoint:function(Y){var X=a7(Y);
var cK=X?Y[0]:Y.x;
var cL=X?Y[1]:Y.y;
this.wrap(new B(cK,cL,cK,cL));
return this;
},snapTo:function(Y,X){if(X===cG||!X){this.x1=Y.x1;
this.x2=Y.x2;
}if(X===cH||!X){this.y1=Y.y1;
this.y2=Y.y2;
}return this;
},alignTo:function(cN,X){var cL=this.height();
var cP=this.width();
var Y=X===cu||X===A?cH:cG;
var cM=Y===cH?cL:cP;
if(X===H){var cO=cN.center();
var cK=this.center();
this.x1+=cO.x-cK.x;
this.y1+=cO.y-cK.y;
}else{if(X===cu||X===be){this[Y+1]=cN[Y+1]-cM;
}else{this[Y+1]=cN[Y+2];
}}this.x2=this.x1+cP;
this.y2=this.y1+cL;
return this;
},shrink:function(Y,X){this.x2-=Y;
this.y2-=X;
return this;
},expand:function(Y,X){this.shrink(-Y,-X);
return this;
},pad:function(X){var Y=aQ(X);
this.x1-=Y.left;
this.x2+=Y.right;
this.y1-=Y.top;
this.y2+=Y.bottom;
return this;
},unpad:function(X){var Y=aQ(X);
Y.left=-Y.left;
Y.top=-Y.top;
Y.right=-Y.right;
Y.bottom=-Y.bottom;
return this.pad(Y);
},clone:function(){return new B(this.x1,this.y1,this.x2,this.y2);
},center:function(){return new bH(this.x1+this.width()/2,this.y1+this.height()/2);
},containsPoint:function(X){return X.x>=this.x1&&X.x<=this.x2&&X.y>=this.y1&&X.y<=this.y2;
},points:function(){return[new bH(this.x1,this.y1),new bH(this.x2,this.y1),new bH(this.x2,this.y2),new bH(this.x1,this.y2)];
},getHash:function(){return[this.x1,this.y1,this.x2,this.y2].join(",");
},overlaps:function(X){return !(X.y2<this.y1||this.y2<X.y1||X.x2<this.x1||this.x2<X.x1);
},rotate:function(cQ){var cR=this.width();
var cK=this.height();
var cP=this.center();
var X=cP.x;
var Y=cP.y;
var cL=bX(0,0,X,Y,cQ);
var cM=bX(cR,0,X,Y,cQ);
var cN=bX(cR,cK,X,Y,cQ);
var cO=bX(0,cK,X,Y,cQ);
cR=Math.max(cL.x,cM.x,cN.x,cO.x)-Math.min(cL.x,cM.x,cN.x,cO.x);
cK=Math.max(cL.y,cM.y,cN.y,cO.y)-Math.min(cL.y,cM.y,cN.y,cO.y);
this.x2=this.x1+cR;
this.y2=this.y1+cK;
return this;
},toRect:function(){return new bP([this.x1,this.y1],[this.width(),this.height()]);
},hasSize:function(){return this.width()!==0&&this.height()!==0;
},align:function(cO,Y,X){var cK=Y+1;
var cL=Y+2;
var cN=Y===cG?cF:aY;
var cM=this[cN]();
if(a0(X,[be,cu])){this[cK]=cO[cK];
this[cL]=this[cK]+cM;
}else{if(a0(X,[bU,A])){this[cL]=cO[cL];
this[cK]=this[cL]-cM;
}else{if(X===H){this[cK]=cO[cK]+(cO[cN]()-cM)/2;
this[cL]=this[cK]+cM;
}}}}});
function bX(cM,cN,Y,cK,X){var cL=bJ(X);
return new bH(Y+(cM-Y)*Math.cos(cL)+(cN-cK)*Math.sin(cL),cK-(cM-Y)*Math.sin(cL)+(cN-cK)*Math.cos(cL));
}var bV=M.extend({init:function(Y,cK,cL,cM,X){this.center=Y;
this.innerRadius=cK;
this.radius=cL;
this.startAngle=cM;
this.angle=X;
},clone:function(){return new bV(this.center,this.innerRadius,this.radius,this.startAngle,this.angle);
},middle:function(){return this.startAngle+this.angle/2;
},setRadius:function(Y,X){if(X){this.innerRadius=Y;
}else{this.radius=Y;
}return this;
},point:function(X,cL){var cM=bJ(X);
var Y=Math.cos(cM);
var cK=Math.sin(cM);
var cN=cL?this.innerRadius:this.radius;
var cO=bY(this.center.x-Y*cN,P);
var cP=bY(this.center.y-cK*cN,P);
return new bH(cO,cP);
},adjacentBox:function(Y,cR,cK){var cQ=this.clone().expand(Y);
var cN=cQ.middle();
var cO=cQ.point(cN);
var cM=cR/2;
var cL=cK/2;
var cP=Math.sin(bJ(cN));
var X=Math.cos(bJ(cN));
var cS=cO.x-cM;
var cT=cO.y-cL;
if(Math.abs(cP)<0.9){cS+=cM*-X/Math.abs(X);
}if(Math.abs(X)<0.9){cT+=cL*-cP/Math.abs(cP);
}return new B(cS,cT,cS+cR,cT+cK);
},containsPoint:function(cQ){var X=this.center;
var cP=this.innerRadius;
var cR=this.radius;
var cS=this.startAngle;
var cM=this.startAngle+this.angle;
var cK=cQ.x-X.x;
var cL=cQ.y-X.y;
var cV=new bH(cK,cL);
var cT=this.point(cS);
var cU=new bH(cT.x-X.x,cT.y-X.y);
var cN=this.point(cM);
var cO=new bH(cN.x-X.x,cN.y-X.y);
var Y=bY(cK*cK+cL*cL,P);
return(cU.equals(cV)||N(cU,cV))&&!N(cO,cV)&&Y>=cP*cP&&Y<=cR*cR;
},getBBox:function(){var cS=this;
var cK=new B(bm,bm,bp,bp);
var cQ=bY(this.startAngle%360);
var cL=bY((cQ+this.angle)%360);
var cO=this.innerRadius;
var X=[0,90,180,270,cQ,cL].sort(bA);
var cR=X.indexOf(cQ);
var cM=X.indexOf(cL);
var Y;
if(cQ===cL){Y=X;
}else{if(cR<cM){Y=X.slice(cR,cM+1);
}else{Y=[].concat(X.slice(0,cM+1),X.slice(cR,X.length));
}}for(var cN=0;
cN<Y.length;
cN++){var cP=cS.point(Y[cN]);
cK.wrapPoint(cP);
cK.wrapPoint(cP,cO);
}if(!cO){cK.wrapPoint(this.center);
}return cK;
},expand:function(X){this.radius+=X;
return this;
}});
function bA(X,Y){return X-Y;
}var b1=bV.extend({init:function(Y,cK,cL,X){bV.fn.init.call(this,Y,0,cK,cL,X);
},expand:function(X){return bV.fn.expand.call(this,X);
},clone:function(){return new b1(this.center,this.radius,this.startAngle,this.angle);
},setRadius:function(X){this.radius=X;
return this;
}});
var b5=M.extend({createRing:function(cQ,cN){var cR=cQ.startAngle+180;
var cK=cQ.angle+cR;
var Y=new aO.Point(cQ.center.x,cQ.center.y);
var cP=Math.max(cQ.radius,0);
var cM=Math.max(cQ.innerRadius,0);
var X=new aO.Arc(Y,{startAngle:cR,endAngle:cK,radiusX:cP,radiusY:cP});
var cO=bG.fromArc(X,cN).close();
if(cM){X.radiusX=X.radiusY=cM;
var cL=X.pointAt(cK);
cO.lineTo(cL.x,cL.y);
cO.arc(cK,cR,cM,cM,true);
}else{cO.lineTo(Y.x,Y.y);
}return cO;
}});
b5.current=new b5();
var I=M.extend({init:function(X){this.children=[];
this.options=aj({},this.options,X);
},reflow:function(cM){var Y=this.children;
var X;
for(var cL=0;
cL<Y.length;
cL++){var cK=Y[cL];
cK.reflow(cM);
X=X?X.wrap(cK.box):cK.box.clone();
}this.box=X||cM;
},destroy:function(){var X=this.children;
if(this.animation){this.animation.destroy();
}for(var Y=0;
Y<X.length;
Y++){X[Y].destroy();
}},getRoot:function(){var X=this.parent;
return X?X.getRoot():null;
},getSender:function(){var X=this.getService();
if(X){return X.sender;
}},getService:function(){var X=this;
while(X){if(X.chartService){return X.chartService;
}X=X.parent;
}},translateChildren:function(cK,cL){var X=this.children;
var Y=X.length;
for(var cM=0;
cM<Y;
cM++){X[cM].box.translate(cK,cL);
}},append:function(){var X=arguments;
var cL=this;
for(var Y=0;
Y<arguments.length;
Y++){var cK=X[Y];
cL.children.push(cK);
cK.parent=cL;
}},renderVisual:function(){if(this.options.visible===false){return;
}this.createVisual();
this.addVisual();
this.renderChildren();
this.createAnimation();
this.renderComplete();
},addVisual:function(){if(this.visual){this.visual.chartElement=this;
if(this.parent){this.parent.appendVisual(this.visual);
}}},renderChildren:function(){var X=this.children;
var cK=X.length;
for(var Y=0;
Y<cK;
Y++){X[Y].renderVisual();
}},createVisual:function(){this.visual=new aW({zIndex:this.options.zIndex,visible:cB(this.options.visible,true)});
},createAnimation:function(){if(this.visual){this.animation=aw.Animation.create(this.visual,this.options.animation);
}},appendVisual:function(X){if(!X.chartElement){X.chartElement=this;
}if(X.options.noclip){this.clipRoot().visual.append(X);
}else{if(at(X.options.zIndex)){this.stackRoot().stackVisual(X);
}else{if(this.isStackRoot){this.stackVisual(X);
}else{if(this.visual){this.visual.append(X);
}else{this.parent.appendVisual(X);
}}}}},clipRoot:function(){if(this.parent){return this.parent.clipRoot();
}return this;
},stackRoot:function(){if(this.parent){return this.parent.stackRoot();
}return this;
},stackVisual:function(X){var cO=X.options.zIndex||0;
var cN=this.visual.children;
var cK=cN.length;
var cL;
for(cL=0;
cL<cK;
cL++){var cM=cN[cL];
var Y=cB(cM.options.zIndex,0);
if(Y>cO){break;
}}this.visual.insert(cL,X);
},traverse:function(X){var cK=this.children;
var cM=cK.length;
for(var cL=0;
cL<cM;
cL++){var Y=cK[cL];
X(Y);
if(Y.traverse){Y.traverse(X);
}}},closest:function(Y){var X=this;
var cK=false;
while(X&&!cK){cK=Y(X);
if(!cK){X=X.parent;
}}if(cK){return X;
}},renderComplete:function(){},hasHighlight:function(){var X=(this.options||{}).highlight;
return !(!this.createHighlight||X&&X.visible===false);
},toggleHighlight:function(cM){var cN=this;
var cL=(this.options||{}).highlight;
var X=(cL||{}).visual;
var Y=this._highlight;
if(!Y){var cK={fill:{color:cE,opacity:0.2},stroke:{color:cE,width:1,opacity:0.2}};
if(X){Y=this._highlight=X(a.extend(this.highlightVisualArgs(),{createVisual:function(){return cN.createHighlight(cK);
},sender:this.getSender(),series:this.series,dataItem:this.dataItem,category:this.category,value:this.value,percentage:this.percentage,runningTotal:this.runningTotal,total:this.total}));
if(!Y){return;
}}else{Y=this._highlight=this.createHighlight(cK);
}Y.options.zIndex=this.options.zIndex;
this.appendVisual(Y);
}Y.visible(cM);
},createGradientOverlay:function(X,cK,Y){var cL=new bG(a.extend({stroke:{color:"none"},fill:this.createGradient(Y),closed:X.options.closed},cK));
cL.segments.elements(X.segments.elements());
return cL;
},createGradient:function(X){if(this.parent){return this.parent.createGradient(X);
}}});
I.prototype.options={};
var D=I.extend({init:function(X){I.fn.init.call(this,X);
this.options.margin=aQ(this.options.margin);
this.options.padding=aQ(this.options.padding);
},reflow:function(cV){var cW=this;
var cR=this.options;
var cX=cR.width;
var cN=cR.height;
var cU=cR.shrinkToFit;
var cM=cX&&cN;
var cQ=cR.margin;
var cS=cR.padding;
var X=cR.border.width;
var Y;
var cT=function(){cW.align(cV,cG,cR.align);
cW.align(cV,cH,cR.vAlign);
cW.paddingBox=Y.clone().unpad(cQ).unpad(X);
};
var cL=cV.clone();
if(cM){cL.x2=cL.x1+cX;
cL.y2=cL.y1+cN;
}if(cU){cL.unpad(cQ).unpad(X).unpad(cS);
}I.fn.reflow.call(this,cL);
if(cM){Y=this.box=new B(0,0,cX,cN);
}else{Y=this.box;
}if(cU&&cM){cT();
cL=this.contentBox=this.paddingBox.clone().unpad(cS);
}else{cL=this.contentBox=Y.clone();
Y.pad(cS).pad(X).pad(cQ);
cT();
}this.translateChildren(Y.x1-cL.x1+cQ.left+X+cS.left,Y.y1-cL.y1+cQ.top+X+cS.top);
var cK=this.children;
for(var cO=0;
cO<cK.length;
cO++){var cP=cK[cO];
cP.reflow(cP.box);
}},align:function(cK,Y,X){this.box.align(cK,Y,X);
},hasBox:function(){var X=this.options;
return X.border.width||X.background;
},createVisual:function(){I.fn.createVisual.call(this);
var X=this.options;
if(X.visible&&this.hasBox()){this.visual.append(bG.fromRect(this.paddingBox.toRect(),this.visualStyle()));
}},visualStyle:function(){var Y=this.options;
var X=Y.border||{};
return{stroke:{width:X.width,color:X.color,opacity:cB(X.opacity,Y.opacity),dashType:X.dashType},fill:{color:Y.background,opacity:Y.opacity},cursor:Y.cursor};
}});
b4(D,{align:be,vAlign:cu,margin:{},padding:{},border:{color:z,width:0},background:"",shrinkToFit:false,width:0,height:0,visible:true});
var b6=D.extend({init:function(X,Y){D.fn.init.call(this,X);
this.pointData=Y;
},getElement:function(){var cN=this;
var cM=cN.options;
var X=cN.paddingBox;
var cQ=cM.type;
var cO=cM.rotation;
var Y=X.center();
var cL=X.width()/2;
if(!cM.visible||!this.hasBox()){return null;
}var cP=this.visualStyle();
var cK;
if(cQ===L){cK=new aw.Circle(new K([bY(X.x1+cL,P),bY(X.y1+X.height()/2,P)],cL),cP);
}else{if(cQ===cx){cK=bG.fromPoints([[X.x1+cL,X.y1],[X.x1,X.y2],[X.x2,X.y2]],cP).close();
}else{if(cQ===T){cK=new aw.MultiPath(cP);
cK.moveTo(X.x1,X.y1).lineTo(X.x2,X.y2);
cK.moveTo(X.x1,X.y2).lineTo(X.x2,X.y1);
}else{cK=bG.fromRect(X.toRect(),cP);
}}}if(cO){cK.transform(aP().rotate(-cO,[Y.x,Y.y]));
}cK.options.zIndex=cM.zIndex;
return cK;
},createElement:function(){var cK=this;
var X=this.options.visual;
var Y=this.pointData||{};
var cL;
if(X){cL=X({value:Y.value,dataItem:Y.dataItem,sender:this.getSender(),series:Y.series,category:Y.category,rect:this.paddingBox.toRect(),options:this.visualOptions(),createVisual:function(){return cK.getElement();
}});
}else{cL=this.getElement();
}return cL;
},visualOptions:function(){var X=this.options;
return{background:X.background,border:X.border,margin:X.margin,padding:X.padding,type:X.type,size:X.width,visible:X.visible};
},createVisual:function(){this.visual=this.createElement();
}});
b4(b6,{type:L,align:H,vAlign:H});
var bh="linear";
var bO="radial";
var aT={glass:{type:bh,rotation:0,stops:[{offset:0,color:cE,opacity:0},{offset:0.25,color:cE,opacity:0.3},{offset:1,color:cE,opacity:0}]},sharpBevel:{type:bO,stops:[{offset:0,color:cE,opacity:0.55},{offset:0.65,color:cE,opacity:0},{offset:0.95,color:cE,opacity:0.25}]},roundedBevel:{type:bO,stops:[{offset:0.33,color:cE,opacity:0.06},{offset:0.83,color:cE,opacity:0.2},{offset:0.95,color:cE,opacity:0}]},roundedGlass:{type:bO,supportVML:false,stops:[{offset:0,color:cE,opacity:0},{offset:0.5,color:cE,opacity:0.3},{offset:0.99,color:cE,opacity:0}]},sharpGlass:{type:bO,supportVML:false,stops:[{offset:0,color:cE,opacity:0.2},{offset:0.15,color:cE,opacity:0.15},{offset:0.17,color:cE,opacity:0.35},{offset:0.85,color:cE,opacity:0.05},{offset:0.87,color:cE,opacity:0.15},{offset:0.99,color:cE,opacity:0}]},bubbleShadow:{type:bO,center:[0.5,0.5],radius:0.5}};
function C(cR,cS){if(cR.x1===cS.x1&&cR.y1===cS.y1&&cR.x2===cS.x2&&cR.y2===cS.y2){return cS;
}var X=Math.min(cR.x1,cS.x1);
var Y=Math.max(cR.x1,cS.x1);
var cL=Math.min(cR.x2,cS.x2);
var cM=Math.max(cR.x2,cS.x2);
var cN=Math.min(cR.y1,cS.y1);
var cO=Math.max(cR.y1,cS.y1);
var cP=Math.min(cR.y2,cS.y2);
var cQ=Math.max(cR.y2,cS.y2);
var cK=[];
cK[0]=new B(Y,cN,cL,cO);
cK[1]=new B(X,cO,Y,cP);
cK[2]=new B(cL,cO,cM,cP);
cK[3]=new B(Y,cP,cL,cQ);
if(cR.x1===X&&cR.y1===cN||cS.x1===X&&cS.y1===cN){cK[4]=new B(X,cN,Y,cO);
cK[5]=new B(cL,cP,cM,cQ);
}else{cK[4]=new B(cL,cN,cM,cO);
cK[5]=new B(X,cP,Y,cQ);
}return aU(cK,function(cT){return cT.height()>0&&cT.width()>0;
})[0];
}var bW=I.extend({init:function(X){I.fn.init.call(this,X);
var Y=this.options;
Y.width=parseInt(Y.width,10);
Y.height=parseInt(Y.height,10);
this.gradients={};
},reflow:function(){var cM=this;
var cL=cM.options;
var X=cM.children;
var Y=new B(0,0,cL.width,cL.height);
this.box=Y.unpad(cL.margin);
for(var cK=0;
cK<X.length;
cK++){X[cK].reflow(Y);
Y=C(Y,X[cK].box)||new B();
}},createVisual:function(){this.visual=new aW();
this.createBackground();
},createBackground:function(){var cL=this.options;
var Y=cL.border||{};
var cK=this.box.clone().pad(cL.margin).unpad(Y.width);
var X=bG.fromRect(cK.toRect(),{stroke:{color:Y.width?Y.color:"",width:Y.width,dashType:Y.dashType},fill:{color:cL.background,opacity:cL.opacity},zIndex:-10});
this.visual.append(X);
},getRoot:function(){return this;
},createGradient:function(cN){var cL=this.gradients;
var cM=bC(cN);
var Y=aT[cN.gradient];
var X;
if(cL[cM]){X=cL[cM];
}else{var cK=a.extend({},Y,cN);
if(Y.type==="linear"){X=new aw.LinearGradient(cK);
}else{if(cN.innerRadius){cK.stops=a2(cK);
}X=new aw.RadialGradient(cK);
X.supportVML=Y.supportVML!==false;
}cL[cM]=X;
}return X;
}});
b4(bW,{width:aq,height:al,background:cE,border:{color:z,width:0},margin:aQ(5),zIndex:-2});
function a2(cM){var cN=cM.stops;
var cO=cM.innerRadius/cM.radius*100;
var cL=cN.length;
var Y=[];
for(var cK=0;
cK<cL;
cK++){var X=a.extend({},cN[cK]);
X.offset=(X.offset*(100-cO)+cO)/100;
Y.push(X);
}return Y;
}var aH=I.extend({init:function(X){I.fn.init.call(this,X);
this._initDirection();
},_initDirection:function(){var X=this.options;
if(X.vertical){this.groupAxis=cG;
this.elementAxis=cH;
this.groupSizeField=cF;
this.elementSizeField=aY;
this.groupSpacing=X.spacing;
this.elementSpacing=X.vSpacing;
}else{this.groupAxis=cH;
this.elementAxis=cG;
this.groupSizeField=aY;
this.elementSizeField=cF;
this.groupSpacing=X.vSpacing;
this.elementSpacing=X.spacing;
}},reflow:function(X){this.box=X.clone();
this.reflowChildren();
},reflowChildren:function(){var c5=this;
var c3=this;
var X=c3.box;
var cK=c3.elementAxis;
var cQ=c3.groupAxis;
var cN=c3.elementSizeField;
var cX=c3.groupSizeField;
var c4=this.groupOptions();
var cV=c4.groups;
var cY=c4.groupsSize;
var c2=c4.maxGroupElementsSize;
var cW=cV.length;
var cZ=X[cQ+1]+this.alignStart(cY,X[cX]());
if(cW){var c0=cZ;
for(var cU=0;
cU<cW;
cU++){var cP=cV[cU];
var cR=cP.groupElements;
var cO=X[cK+1];
var cS=cR.length;
for(var c1=0;
c1<cS;
c1++){var Y=cR[c1];
var cM=c5.elementSize(Y);
var cT=c0+c5.alignStart(cM[cX],cP.groupSize);
var cL=new B();
cL[cQ+1]=cT;
cL[cQ+2]=cT+cM[cX];
cL[cK+1]=cO;
cL[cK+2]=cO+cM[cN];
Y.reflow(cL);
cO+=cM[cN]+c5.elementSpacing;
}c0+=cP.groupSize+c5.groupSpacing;
}X[cQ+1]=cZ;
X[cQ+2]=cZ+cY;
X[cK+2]=X[cK+1]+c2;
}},alignStart:function(cK,Y){var cL=0;
var X=this.options.align;
if(X===bU||X===A){cL=Y-cK;
}else{if(X===H){cL=(Y-cK)/2;
}}return cL;
},groupOptions:function(){var c0=this;
var cZ=this;
var X=cZ.box;
var Y=cZ.children;
var cN=cZ.elementSizeField;
var cT=cZ.groupSizeField;
var cO=cZ.elementSpacing;
var cU=cZ.groupSpacing;
var cY=bY(X[cN]());
var cK=Y.length;
var cR=[];
var cS=0;
var cQ=0;
var cV=0;
var cX=0;
var cP=[];
for(var cW=0;
cW<cK;
cW++){var cL=Y[cW];
if(!cL.box){cL.reflow(X);
}var cM=c0.elementSize(cL);
if(c0.options.wrap&&bY(cQ+cO+cM[cN])>cY){cR.push({groupElements:cP,groupSize:cS,groupElementsSize:cQ});
cX=Math.max(cX,cQ);
cV+=cU+cS;
cS=0;
cQ=0;
cP=[];
}cS=Math.max(cS,cM[cT]);
if(cQ>0){cQ+=cO;
}cQ+=cM[cN];
cP.push(cL);
}cR.push({groupElements:cP,groupSize:cS,groupElementsSize:cQ});
cX=Math.max(cX,cQ);
cV+=cS;
return{groups:cR,groupsSize:cV,maxGroupElementsSize:cX};
},elementSize:function(X){return{width:X.box.width(),height:X.box.height()};
},createVisual:function(){}});
b4(aH,{vertical:true,wrap:true,vSpacing:0,spacing:0});
var ax=aw.Text;
var ce=I.extend({init:function(X,Y){I.fn.init.call(this,Y);
this.content=X;
this.reflow(new B());
},reflow:function(cK){var X=this.options;
var Y=X.size=cz.measureText(this.content,{font:X.font});
this.baseline=Y.baseline;
this.box=new B(cK.x1,cK.y1,cK.x1+Y.width,cK.y1+Y.height);
},createVisual:function(){var cM=this.options;
var cK=cM.font;
var X=cM.color;
var cL=cM.opacity;
var Y=cM.cursor;
this.visual=new ax(this.content,this.box.toRect().topLeft(),{font:cK,fill:{color:X,opacity:cL},cursor:Y});
}});
b4(ce,{font:ak,color:z});
function bQ(cK){var Y=cK.origin;
var X=cK.bottomRight();
return new B(Y.x,Y.y,X.x,X.y);
}var bZ=/\n|\\n/m;
var cf=D.extend({init:function(X,Y){D.fn.init.call(this,Y);
this.content=X;
this._initContainer();
if(this.options._autoReflow!==false){this.reflow(new B());
}},_initContainer:function(){var Y=this.options;
var cL=String(this.content).split(bZ);
var X=new aH({vertical:true,align:Y.align,wrap:false});
var cN=aj({},Y,{opacity:1,animation:null});
this.container=X;
this.append(X);
for(var cK=0;
cK<cL.length;
cK++){var cM=new ce(cL[cK].trim(),cN);
X.append(cM);
}},reflow:function(cL){var cK=this.options;
var cO=cK.visual;
this.container.options.align=cK.align;
if(cO&&!this._boxReflow){var cN=cL;
if(!cN.hasSize()){this._boxReflow=true;
this.reflow(cN);
this._boxReflow=false;
cN=this.box;
}var cM=this.visual=cO(this.visualContext(cN));
if(cM){cN=bQ(cM.clippedBBox()||new bP());
cM.options.zIndex=cK.zIndex;
cM.options.noclip=cK.noclip;
}this.box=this.contentBox=this.paddingBox=cN;
}else{D.fn.reflow.call(this,cL);
if(cK.rotation){var Y=aQ(cK.margin);
var X=this.box.unpad(Y);
this.targetBox=cL;
this.normalBox=X.clone();
X=this.rotate();
X.translate(Y.left-Y.right,Y.top-Y.bottom);
this.rotatedBox=X.clone();
X.pad(Y);
}}},createVisual:function(){var Y=this.options;
if(!Y.visible){return;
}this.visual=new aW({transform:this.rotationTransform(),zIndex:Y.zIndex,noclip:Y.noclip});
if(this.hasBox()){var X=bG.fromRect(this.paddingBox.toRect(),this.visualStyle());
this.visual.append(X);
}},renderVisual:function(){if(this.options.visual){this.addVisual();
this.createAnimation();
}else{D.fn.renderVisual.call(this);
}},visualOptions:function(){var X=this.options;
return{background:X.background,border:X.border,color:X.color,font:X.font,margin:X.margin,padding:X.padding,visible:X.visible};
},visualContext:function(X){var Y=this;
return{text:this.content,rect:X.toRect(),sender:this.getSender(),options:this.visualOptions(),createVisual:function(){Y._boxReflow=true;
Y.reflow(X);
Y._boxReflow=false;
return Y.getDefaultVisual();
}};
},getDefaultVisual:function(){this.createVisual();
this.renderChildren();
var X=this.visual;
delete this.visual;
return X;
},rotate:function(){var X=this.options;
this.box.rotate(X.rotation);
this.align(this.targetBox,cG,X.align);
this.align(this.targetBox,cH,X.vAlign);
return this.box;
},rotationTransform:function(){var cM=this.options.rotation;
if(!cM){return null;
}var cL=this.normalBox.center();
var Y=cL.x;
var cK=cL.y;
var X=this.rotatedBox.center();
return aP().translate(X.x-Y,X.y-cK).rotate(cM,[Y,cK]);
}});
var cs=I.extend({init:function(X){I.fn.init.call(this,X);
this.append(new cf(this.options.text,a.extend({},this.options,{vAlign:this.options.position})));
},reflow:function(X){I.fn.reflow.call(this,X);
this.box.snapTo(X,cG);
}});
cs.buildTitle=function(Y,cK,X){var cM=Y;
if(typeof Y==="string"){cM={text:Y};
}cM=a.extend({visible:true},X,cM);
var cL;
if(cM&&cM.visible&&cM.text){cL=new cs(cM);
cK.append(cL);
}return cL;
};
b4(cs,{color:z,position:cu,align:H,margin:aQ(5),padding:aQ(5)});
var v=cf.extend({init:function(cM,cL,Y,X,cK){cf.fn.init.call(this,cL,cK);
this.text=cL;
this.value=cM;
this.index=Y;
this.dataItem=X;
this.reflow(new B());
},visualContext:function(Y){var X=cf.fn.visualContext.call(this,Y);
X.value=this.value;
X.dataItem=this.dataItem;
X.format=this.options.format;
X.culture=this.options.culture;
return X;
},click:function(Y,X){Y.trigger(u,{element:aD(X),value:this.value,text:this.text,index:this.index,dataItem:this.dataItem,axis:this.parent.options});
},rotate:function(){if(this.options.alignRotation!==H){var X=this.normalBox.toRect();
var Y=this.rotationTransform();
this.box=bQ(X.bbox(Y.matrix()));
}else{cf.fn.rotate.call(this);
}return this.box;
},rotationTransform:function(){var cT=this.options;
var cW=cT.rotation;
if(!cW){return null;
}if(cT.alignRotation===H){return cf.fn.rotationTransform.call(this);
}var cX=aP().rotate(cW).matrix();
var cP=this.normalBox.toRect();
var cU=this.targetBox.toRect();
var cY=cT.rotationOrigin||cu;
var X=cY===cu||cY===A?cG:cH;
var cQ=cY===cu||cY===A?cH:cG;
var cM=cY===cu||cY===be?cU.origin:cU.bottomRight();
var cZ=cP.topLeft().transformCopy(cX);
var c0=cP.topRight().transformCopy(cX);
var cO=cP.bottomRight().transformCopy(cX);
var cN=cP.bottomLeft().transformCopy(cX);
var cV=bP.fromPoints(cZ,c0,cO,cN);
var c1={};
c1[cQ]=cU.origin[cQ]-cV.origin[cQ];
var cR=Math.abs(cZ[cQ]+c1[cQ]-cM[cQ]);
var cS=Math.abs(c0[cQ]+c1[cQ]-cM[cQ]);
var cL,cK;
if(bY(cR,ap)===bY(cS,ap)){cL=cZ;
cK=c0;
}else{if(cS<cR){cL=c0;
cK=cO;
}else{cL=cZ;
cK=cN;
}}var Y=cL[X]+(cK[X]-cL[X])/2;
c1[X]=cU.center()[X]-Y;
return aP().translate(c1.x,c1.y).rotate(cW);
}});
b4(v,{_autoReflow:false});
var ar={format:function(X,Y){return Y;
},toString:function(X){return X;
},parseDate:function(X){return new Date(X);
}};
var U=ar;
var a6=M.extend({});
a6.register=function(X){U=X;
};
if(Object.defineProperties){Object.defineProperties(a6,{implementation:{get:function(){return U;
}}});
}var aM=/\{(\d+)(:[^\}]+)?\}/g;
var aN=M.extend({init:function(X){this._intlService=X;
},auto:function(X){var cL=[],cK=arguments.length-1;
while(cK-->0){cL[cK]=arguments[cK+1];
}var Y=this.intlService;
if(X.match(aL)){return Y.format.apply(Y,[X].concat(cL));
}return Y.toString(cL[0],X);
},localeAuto:function(X,cM,cK){var Y=this.intlService;
var cL;
if(X.match(aL)){cL=X.replace(aM,function(cO,cN,cP){var cQ=cM[parseInt(cN,10)];
return Y.toString(cQ,cP?cP.substring(1):"",cK);
});
}else{cL=Y.toString(cM[0],X,cK);
}return cL;
}});
if(Object.defineProperties){Object.defineProperties(aN.fn,{intlService:{get:function(){return this._intlService||a6.implementation;
}}});
}var J=M.extend({init:function(X,Y){if(Y===void 0){Y={};
}this._intlService=Y.intlService;
this.sender=Y.sender||X;
this.format=new aN(Y.intlService);
this.chart=X;
},notify:function(Y,X){this.chart.trigger(Y,X);
}});
if(Object.defineProperties){Object.defineProperties(J.fn,{intl:{get:function(){return this._intlService||a6.implementation;
}}});
}var V;
var av=M.extend({});
av.register=function(X){V=X;
};
av.create=function(X,Y){if(V){return V.create(X,Y);
}};
var W={compile:function(X){return X;
}};
var cd=M.extend({});
cd.register=function(X){W=X;
};
cd.compile=function(X){return W.compile(X);
};
var b3={ChartService:J,DomEventsBuilder:av,FormatService:aN,IntlService:a6,TemplateService:cd};
var am=7;
var an="#fff";
var bv=D.extend({init:function(Y,cK,X){D.fn.init.call(this,cK);
this.fields=Y;
this.chartService=X;
this.render();
},hide:function(){this.options.visible=false;
},show:function(){this.options.visible=true;
},render:function(){var cO=this.options;
if(cO.visible){var cL=cO.label;
var cK=cO.icon;
var X=new B();
var cP=cK.size;
var cQ=this.fields.text;
var cR,Y;
if(at(cL)&&cL.visible){if(cL.template){var cN=cd.compile(cL.template);
cQ=cN(this.fields);
}else{if(cL.format){cQ=this.chartService.format.auto(cL.format,cQ);
}}if(!cL.color){cL.color=cL.position===a3?an:cK.background;
}this.label=new cf(cQ,aj({},cL));
if(cL.position===a3&&!at(cP)){if(cK.type===L){cP=Math.max(this.label.box.width(),this.label.box.height());
}else{cR=this.label.box.width();
Y=this.label.box.height();
}X.wrap(this.label.box);
}}cK.width=cR||cP||am;
cK.height=Y||cP||am;
var cM=new b6(aj({},cK));
this.marker=cM;
this.append(cM);
if(this.label){this.append(this.label);
}cM.reflow(new B());
this.wrapperBox=X.wrap(cM.box);
}},reflow:function(cS){var cR=this;
var cP=cR.options;
var cL=cR.label;
var cO=cR.marker;
var cT=cR.wrapperBox;
var Y=cS.center();
var cM=cP.line.length;
var cQ=cP.position;
if(cP.visible){var cN,X,cK;
if(a0(cQ,[be,bU])){if(cQ===be){cK=cT.alignTo(cS,cQ).translate(-cM,cS.center().y-cT.center().y);
if(cP.line.visible){cN=[cS.x1,Y.y];
this.linePoints=[cN,[cK.x2,Y.y]];
X=cK.clone().wrapPoint(cN);
}}else{cK=cT.alignTo(cS,cQ).translate(cM,cS.center().y-cT.center().y);
if(cP.line.visible){cN=[cS.x2,Y.y];
this.linePoints=[cN,[cK.x1,Y.y]];
X=cK.clone().wrapPoint(cN);
}}}else{if(cQ===A){cK=cT.alignTo(cS,cQ).translate(cS.center().x-cT.center().x,cM);
if(cP.line.visible){cN=[Y.x,cS.y2];
this.linePoints=[cN,[Y.x,cK.y1]];
X=cK.clone().wrapPoint(cN);
}}else{cK=cT.alignTo(cS,cQ).translate(cS.center().x-cT.center().x,-cM);
if(cP.line.visible){cN=[Y.x,cS.y1];
this.linePoints=[cN,[Y.x,cK.y2]];
X=cK.clone().wrapPoint(cN);
}}}if(cO){cO.reflow(cK);
}if(cL){cL.reflow(cK);
if(cO){if(cP.label.position===bD){cL.box.alignTo(cO.box,cQ);
}cL.reflow(cL.box);
}}this.contentBox=cK;
this.targetBox=cS;
this.box=X||cK;
}},createVisual:function(){D.fn.createVisual.call(this);
this.visual.options.noclip=this.options.noclip;
if(this.options.visible){this.createLine();
}},renderVisual:function(){var cK=this;
var Y=this.options;
var X=Y.visual;
if(Y.visible&&X){this.visual=X(a.extend(this.fields,{sender:this.getSender(),rect:this.targetBox.toRect(),options:{background:Y.background,border:Y.background,icon:Y.icon,label:Y.label,line:Y.line,position:Y.position,visible:Y.visible},createVisual:function(){cK.createVisual();
cK.renderChildren();
var cL=cK.visual;
delete cK.visual;
return cL;
}}));
this.addVisual();
}else{D.fn.renderVisual.call(this);
}},createLine:function(){var X=this.options.line;
if(this.linePoints){var Y=bG.fromPoints(this.linePoints,{stroke:{color:X.color,width:X.width,dashType:X.dashType}});
h(Y);
this.visual.append(Y);
}},click:function(cK,Y){var X=this.eventArgs(Y);
if(!cK.trigger(bw,X)){Y.preventDefault();
}},hover:function(cK,Y){var X=this.eventArgs(Y);
if(!cK.trigger(bx,X)){Y.preventDefault();
}},leave:function(X){X._unsetActivePoint();
},eventArgs:function(X){var Y=this.options;
return a.extend(this.fields,{element:aD(X),text:at(Y.label)?Y.label.text:"",visual:this.visual});
}});
b4(bv,{icon:{visible:true,type:L},label:{position:a3,visible:true,align:H,vAlign:H},line:{visible:true},visible:true,position:cu,zIndex:2});
function S(X,cL){var cM=X.tickX;
var cN=X.tickY;
var Y=X.position;
var cK=new bG({stroke:{width:cL.width,color:cL.color}});
if(X.vertical){cK.moveTo(cM,Y).lineTo(cM+cL.size,Y);
}else{cK.moveTo(Y,cN).lineTo(Y,cN+cL.size);
}h(cK);
return cK;
}function R(cM,X){var cL=cM.lineStart;
var cK=cM.lineEnd;
var cN=cM.position;
var Y=new bG({stroke:{width:X.width,color:X.color,dashType:X.dashType}});
if(cM.vertical){Y.moveTo(cL,cN).lineTo(cK,cN);
}else{Y.moveTo(cN,cL).lineTo(cN,cK);
}h(Y);
return Y;
}var t=I.extend({init:function(Y,X){if(X===void 0){X=new J();
}I.fn.init.call(this,Y);
this.chartService=X;
if(!this.options.visible){this.options=aj({},this.options,{labels:{visible:false},line:{visible:false},margin:0,majorTickSize:0,minorTickSize:0});
}this.options.minorTicks=aj({},{color:this.options.line.color,width:this.options.line.width,visible:this.options.minorTickType!==bu},this.options.minorTicks,{size:this.options.minorTickSize,align:this.options.minorTickType});
this.options.majorTicks=aj({},{color:this.options.line.color,width:this.options.line.width,visible:this.options.majorTickType!==bu},this.options.majorTicks,{size:this.options.majorTickSize,align:this.options.majorTickType});
if(!this.options._deferLabels){this.createLabels();
}this.createTitle();
this.createNotes();
},labelsRange:function(){return{min:this.options.labels.skip,max:this.labelsCount()};
},createLabels:function(){var cQ=this;
var cM=this.options;
var X=cM.vertical?bU:H;
var cL=aj({},cM.labels,{align:X,zIndex:cM.zIndex});
var cP=Math.max(1,cL.step);
this.children=aU(this.children,function(cR){return !(cR instanceof v);
});
this.labels=[];
if(cL.visible){var cN=this.labelsRange();
var cO=cL.rotation;
if(ba(cO)){cL.alignRotation=cO.align;
cL.rotation=cO.angle;
}if(cL.rotation==="auto"){cL.rotation=0;
cM.autoRotateLabels=true;
}for(var Y=cN.min;
Y<cN.max;
Y+=cP){var cK=cQ.createAxisLabel(Y,cL);
if(cK){cQ.append(cK);
cQ.labels.push(cK);
}}}},lineBox:function(){var cO=this;
var cN=cO.options;
var cK=cO.box;
var cP=cN.vertical;
var cM=cN.labels.mirror;
var X=cM?cK.x1:cK.x2;
var Y=cM?cK.y2:cK.y1;
var cL=cN.line.width||0;
return cP?new B(X,cK.y1,X,cK.y2-cL):new B(cK.x1,Y,cK.x2-cL,Y);
},createTitle:function(){var X=this.options;
var cK=aj({rotation:X.vertical?-90:0,text:"",zIndex:1,visualSize:true},X.title);
if(cK.visible&&cK.text){var Y=new cf(cK.text,cK);
this.append(Y);
this.title=Y;
}},createNotes:function(){var cO=this;
var cN=this.options;
var cM=cN.notes;
var cK=cM.data||[];
this.notes=[];
for(var X=0;
X<cK.length;
X++){var Y=aj({},cM,cK[X]);
Y.value=cO.parseNoteValue(Y.value);
var cL=new bv({value:Y.value,text:Y.label.text,dataItem:Y},Y,cO.chartService);
if(cL.options.visible){if(at(cL.options.position)){if(cN.vertical&&!a0(cL.options.position,[be,bU])){cL.options.position=cN.reverse?be:bU;
}else{if(!cN.vertical&&!a0(cL.options.position,[cu,A])){cL.options.position=cN.reverse?A:cu;
}}}else{if(cN.vertical){cL.options.position=cN.reverse?be:bU;
}else{cL.options.position=cN.reverse?A:cu;
}}cO.append(cL);
cO.notes.push(cL);
}}},parseNoteValue:function(X){return X;
},renderVisual:function(){I.fn.renderVisual.call(this);
this.createPlotBands();
},createVisual:function(){I.fn.createVisual.call(this);
this.createBackground();
this.createLine();
},gridLinesVisual:function(){var X=this._gridLines;
if(!X){X=this._gridLines=new aW({zIndex:-2});
this.appendVisual(this._gridLines);
}return X;
},createTicks:function(Y){var cM=this.options;
var X=this.lineBox();
var cL=cM.labels.mirror;
var cK=cM.majorTicks.visible?cM.majorUnit:0;
var cO={vertical:cM.vertical};
function cN(cU,cT,cR){var cP=cU.length;
var cS=Math.max(1,cT.step);
if(cT.visible){for(var cQ=cT.skip;
cQ<cP;
cQ+=cS){if(at(cR)&&cQ%cR===0){continue;
}cO.tickX=cL?X.x2:X.x2-cT.size;
cO.tickY=cL?X.y1-cT.size:X.y1;
cO.position=cU[cQ];
Y.append(S(cO,cT));
}}}cN(this.getMajorTickPositions(),cM.majorTicks);
cN(this.getMinorTickPositions(),cM.minorTicks,cK/cM.minorUnit);
},createLine:function(){var cL=this.options;
var Y=cL.line;
var cK=this.lineBox();
if(Y.width>0&&Y.visible){var cM=new bG({stroke:{width:Y.width,color:Y.color,dashType:Y.dashType}});
cM.moveTo(cK.x1,cK.y1).lineTo(cK.x2,cK.y2);
if(cL._alignLines){h(cM);
}var X=this._lineGroup=new aW();
X.append(cM);
this.visual.append(X);
this.createTicks(X);
}},getActualTickSize:function(){var X=this.options;
var Y=0;
if(X.majorTicks.visible&&X.minorTicks.visible){Y=Math.max(X.majorTicks.size,X.minorTicks.size);
}else{if(X.majorTicks.visible){Y=X.majorTicks.size;
}else{if(X.minorTicks.visible){Y=X.minorTicks.size;
}}}return Y;
},createBackground:function(){var cL=this;
var cK=cL.options;
var Y=cL.box;
var X=cK.background;
if(X){this._backgroundPath=bG.fromRect(Y.toRect(),{fill:{color:X},stroke:null});
this.visual.append(this._backgroundPath);
}},createPlotBands:function(){var cT=this;
var cN=this.options;
var cQ=cN.plotBands||[];
var cU=cN.vertical;
var cP=this.plotArea;
if(cQ.length===0){return;
}var cK=this._plotbandGroup=new aW({zIndex:-1});
var X=aU(this.pane.axes,function(cV){return cV.options.vertical!==cT.options.vertical;
})[0];
for(var cL=0;
cL<cQ.length;
cL++){var cM=cQ[cL];
var cR=void 0,cS=void 0;
if(cU){cR=(X||cP.axisX).lineBox();
cS=cT.getSlot(cM.from,cM.to,true);
}else{cR=cT.getSlot(cM.from,cM.to,true);
cS=(X||cP.axisY).lineBox();
}if(cR.width()!==0&&cS.height()!==0){var Y=new bP([cR.x1,cS.y1],[cR.width(),cS.height()]);
var cO=bG.fromRect(Y,{fill:{color:cM.color,opacity:cM.opacity},stroke:null});
cK.append(cO);
}}this.appendVisual(cK);
},createGridLines:function(X){var cT=this.options;
var cR=cT.minorGridLines;
var cO=cT.majorGridLines;
var cS=cT.minorUnit;
var cV=cT.vertical;
var Y=X.options.line.visible;
var cQ=cO.visible?cT.majorUnit:0;
var cL=X.lineBox();
var cN=cL[cV?"y1":"x1"];
var cM={lineStart:cL[cV?"x1":"y1"],lineEnd:cL[cV?"x2":"y2"],vertical:cV};
var cP=[];
var cK=this.gridLinesVisual();
function cU(c2,cX,c0){var cW=c2.length;
var c1=Math.max(1,cX.step);
if(cX.visible){for(var cY=cX.skip;
cY<cW;
cY+=c1){var cZ=bY(c2[cY]);
if(!a0(cZ,cP)){if(cY%c0!==0&&(!Y||cN!==cZ)){cM.position=cZ;
cK.append(R(cM,cX));
cP.push(cZ);
}}}}}cU(this.getMajorTickPositions(),cO);
cU(this.getMinorTickPositions(),cR,cQ/cS);
return cK.children;
},reflow:function(X){var cQ=this;
var cP=cQ.options;
var cM=cQ.labels;
var cU=cQ.title;
var cW=cP.vertical;
var cK=cM.length;
var cS=cW?cF:aY;
var cV=cU?cU.box[cS]():0;
var cT=this.getActualTickSize()+cP.margin+cV;
var cR=(this.getRoot()||{}).box||X;
var Y=cR[cS]();
var cO=0;
for(var cL=0;
cL<cK;
cL++){var cN=cM[cL].box[cS]();
if(cN+cT<=Y){cO=Math.max(cO,cN);
}}if(cW){this.box=new B(X.x1,X.y1,X.x1+cO+cT,X.y2);
}else{this.box=new B(X.x1,X.y1,X.x2,X.y1+cO+cT);
}this.arrangeTitle();
this.arrangeLabels();
this.arrangeNotes();
},getLabelsTickPositions:function(){return this.getMajorTickPositions();
},labelTickIndex:function(X){return X.index;
},arrangeLabels:function(){var cZ=this;
var cY=this;
var cX=cY.options;
var cO=cY.labels;
var cP=!cX.justified;
var c2=cX.vertical;
var cT=this.lineBox();
var cV=cX.labels.mirror;
var c1=this.getLabelsTickPositions();
var cM=this.getActualTickSize()+cX.margin;
for(var Y=0;
Y<cO.length;
Y++){var cK=cO[Y];
var c0=cZ.labelTickIndex(cK);
var cQ=c2?cK.box.height():cK.box.width();
var cN=c1[c0]-cQ/2;
var cL=void 0,X=void 0,cW=void 0;
if(c2){if(cP){X=c1[c0];
cW=c1[c0+1];
var cU=X+(cW-X)/2;
cN=cU-cQ/2;
}var cR=cT.x2;
if(cV){cR+=cM;
cK.options.rotationOrigin=be;
}else{cR-=cM+cK.box.width();
cK.options.rotationOrigin=bU;
}cL=cK.box.move(cR,cN);
}else{if(cP){X=c1[c0];
cW=c1[c0+1];
}else{X=cN;
cW=cN+cQ;
}var cS=cT.y1;
if(cV){cS-=cM+cK.box.height();
cK.options.rotationOrigin=A;
}else{cS+=cM;
cK.options.rotationOrigin=cu;
}cL=new B(X,cS,cW,cS+cK.box.height());
}cK.reflow(cL);
}},autoRotateLabels:function(){if(this.options.autoRotateLabels&&!this.options.vertical){var cN=this.getMajorTickPositions();
var cM=this.labels;
var X;
for(var Y=0;
Y<cM.length;
Y++){var cO=cN[Y+1]-cN[Y];
var cL=cM[Y].box;
if(cL.width()>cO){if(cL.height()>cO){X=-90;
break;
}X=-45;
}}if(X){for(var cK=0;
cK<cM.length;
cK++){cM[cK].options.rotation=X;
cM[cK].reflow(new B());
}return true;
}}},arrangeTitle:function(){var cK=this;
var Y=cK.options;
var cL=cK.title;
var X=Y.labels.mirror;
var cM=Y.vertical;
if(cL){if(cM){cL.options.align=X?bU:be;
cL.options.vAlign=cL.options.position;
}else{cL.options.align=cL.options.position;
cL.options.vAlign=X?cu:A;
}cL.reflow(this.box);
}},arrangeNotes:function(){var cL=this;
for(var X=0;
X<this.notes.length;
X++){var Y=cL.notes[X];
var cM=Y.options.value;
var cK=void 0;
if(at(cM)){if(cL.shouldRenderNote(cM)){Y.show();
}else{Y.hide();
}cK=cL.noteSlot(cM);
}else{Y.hide();
}Y.reflow(cK||cL.lineBox());
}},noteSlot:function(X){return this.getSlot(X);
},alignTo:function(cK){var X=cK.lineBox();
var cL=this.options.vertical;
var Y=cL?cH:cG;
this.box.snapTo(X,Y);
if(cL){this.box.shrink(0,this.lineBox().height()-X.height());
}else{this.box.shrink(this.lineBox().width()-X.width(),0);
}this.box[Y+1]-=this.lineBox()[Y+1]-X[Y+1];
this.box[Y+2]-=this.lineBox()[Y+2]-X[Y+2];
},axisLabelText:function(cM,X,Y){var cK=cM;
if(Y.template){var cL=cd.compile(Y.template);
cK=cL({value:cM,dataItem:X,format:Y.format,culture:Y.culture});
}else{if(Y.format){cK=this.chartService.format.localeAuto(Y.format,[cM],Y.culture);
}}return cK;
},slot:function(X,cL,Y){var cK=this.getSlot(X,cL,Y);
if(cK){return cK.toRect();
}},contentBox:function(){var X=this.box.clone();
var Y=this.labels;
if(Y.length){if(Y[0].options.visible){X.wrap(Y[0].box);
}var cK=Y[Y.length-1];
if(cK.options.visible){X.wrap(cK.box);
}}return X;
},limitRange:function(X,cQ,cL,Y,cN){var cO=this.options;
if(X<cL&&cN<0&&(!at(cO.min)||cO.min<=cL)||Y<cQ&&cN>0&&(!at(cO.max)||Y<=cO.max)){return null;
}if(cQ<cL&&cN>0||Y<X&&cN<0){return{min:X,max:cQ};
}var cP=cQ-X;
var cM=X;
var cK=cQ;
if(X<cL){cM=bg(X,cL,Y);
cK=bg(X+cP,cL+cP,Y);
}else{if(cQ>Y){cK=bg(cQ,cL,Y);
cM=bg(cQ-cP,cL,Y-cP);
}}return{min:cM,max:cK};
},valueRange:function(){return{min:this.seriesMin,max:this.seriesMax};
}});
b4(t,{labels:{visible:true,rotation:0,mirror:false,step:1,skip:0},line:{width:1,color:z,visible:true},title:{visible:true,position:H},majorTicks:{align:bD,size:4,skip:0,step:1},minorTicks:{align:bD,size:3,skip:0,step:1},axisCrossingValue:0,majorTickType:bD,minorTickType:bu,majorGridLines:{skip:0,step:1},minorGridLines:{visible:false,width:1,color:z,skip:0,step:1},margin:5,visible:true,reverse:false,justified:true,notes:{label:{text:""}},_alignLines:true,_deferLabels:false});
var bo=0.01;
var E=t.extend({init:function(Y,X){t.fn.init.call(this,Y,X);
this._ticks={};
this._initCategories(this.options);
},_initCategories:function(cN){var X=(cN.categories||[]).slice(0);
var cK=at(cN.min);
var Y=at(cN.max);
cN.categories=X;
if((cK||Y)&&X.length){cN.srcCategories=cN.categories;
var cM=cK?Math.floor(cN.min):0;
var cL;
if(Y){cL=cN.justified?Math.floor(cN.max)+1:Math.ceil(cN.max);
}else{cL=X.length;
}cN.categories=cN.categories.slice(cM,cL);
}},rangeIndices:function(){var cL=this.options;
var X=cL.categories.length||1;
var cK=a9(cL.min)?cL.min%1:0;
var Y;
if(a9(cL.max)&&cL.max%1!==0&&cL.max<this.totalRange().max){Y=X-(1-cL.max%1);
}else{Y=X-(cL.justified?1:0);
}return{min:cK,max:Y};
},totalRangeIndices:function(X){var cL=this.options;
var cK=a9(cL.min)?cL.min:0;
var Y;
if(a9(cL.max)){Y=cL.max;
}else{if(a9(cL.min)){Y=cK+cL.categories.length;
}else{Y=(cL.srcCategories||cL.categories).length-(cL.justified?1:0)||1;
}}if(X){var cM=this.totalRange();
cK=bg(cK,0,cM.max);
Y=bg(Y,0,cM.max);
}return{min:cK,max:Y};
},range:function(){var X=this.options;
return{min:a9(X.min)?X.min:0,max:a9(X.max)?X.max:X.categories.length};
},totalRange:function(){var X=this.options;
return{min:0,max:Math.max(this._seriesMax||0,(X.srcCategories||X.categories).length)-(X.justified?1:0)};
},getScale:function(){var cL=this.rangeIndices();
var cK=cL.min;
var Y=cL.max;
var X=this.lineBox();
var cN=this.options.vertical?X.height():X.width();
var cM=cN/(Y-cK||1);
return cM*(this.options.reverse?-1:1);
},getTickPositions:function(cS){var cO=this.options;
var cT=cO.vertical;
var cQ=cO.reverse;
var cP=this.rangeIndices();
var cL=cP.min;
var cK=cP.max;
var Y=this.lineBox();
var cR=this.getScale();
var cM=Y[(cT?cH:cG)+(cQ?2:1)];
var cN=[];
var X=cL%1!==0?Math.floor(cL/1)+cS:cL;
while(X<=cK){cN.push(cM+bY(cR*(X-cL),P));
X+=cS;
}return cN;
},getLabelsTickPositions:function(){var cP=this.getMajorTickPositions().slice(0);
var cM=this.rangeIndices();
var cN=this.getScale();
var Y=this.lineBox();
var cL=this.options;
var X=cL.vertical?cH:cG;
var cO=cL.reverse?2:1;
var cK=cL.reverse?1:2;
if(cM.min%1!==0){cP.unshift(Y[X+cO]-cN*(cM.min%1));
}if(cM.max%1!==0){cP.push(Y[X+cK]+cN*(1-cM.max%1));
}return cP;
},labelTickIndex:function(Y){var cK=this.rangeIndices();
var X=Y.index;
if(cK.min>0){X=X-Math.floor(cK.min);
}return X;
},arrangeLabels:function(){t.fn.arrangeLabels.call(this);
this.hideOutOfRangeLabels();
},hideOutOfRangeLabels:function(){var cN=this;
var X=cN.box;
var cL=cN.labels;
if(cL.length){var cP=this.options.vertical?cH:cG;
var cO=X[cP+1];
var Y=X[cP+2];
var cK=cL[0];
var cM=bd(cL);
if(cK.box[cP+1]>Y||cK.box[cP+2]<cO){cK.options.visible=false;
}if(cM.box[cP+1]>Y||cM.box[cP+2]<cO){cM.options.visible=false;
}}},getMajorTickPositions:function(){return this.getTicks().majorTicks;
},getMinorTickPositions:function(){return this.getTicks().minorTicks;
},getTicks:function(){var cN=this.options;
var cO=cN.reverse;
var cK=cN.justified;
var X=this._ticks;
var cM=this.rangeIndices();
var cL=this.lineBox();
var Y=cL.getHash()+cM.min+","+cM.max+cO+cK;
if(X._hash!==Y){X._hash=Y;
X.majorTicks=this.getTickPositions(1);
X.minorTicks=this.getTickPositions(0.5);
}return X;
},getSlot:function(Y,cZ,cL){var cS=this;
var cP=cS.options;
var cU=cP.reverse;
var cK=cP.justified;
var c1=cP.vertical;
var cT=this.rangeIndices();
var cO=cT.min;
var c0=c1?cH:cG;
var cM=this.lineBox();
var cV=this.getScale();
var cN=cM[c0+(cU?2:1)];
var cX=cM.clone();
var cW=!at(cZ);
var cY=cB(Y,0);
var X=cB(cZ,cY);
X=Math.max(X-1,cY);
X=Math.max(cY,X);
var cQ=cN+(cY-cO)*cV;
var cR=cN+(X+1-cO)*cV;
if(cW&&cK){cR=cQ;
}if(cL){cQ=bg(cQ,cM[c0+1],cM[c0+2]);
cR=bg(cR,cM[c0+1],cM[c0+2]);
}cX[c0+1]=cU?cR:cQ;
cX[c0+2]=cU?cQ:cR;
return cX;
},slot:function(Y,cM,cK){var cL=Y;
var X=cM;
if(typeof cL==="string"){cL=this.categoryIndex(cL);
}if(typeof X==="string"){X=this.categoryIndex(X);
}return t.fn.slot.call(this,cL,X,cK);
},pointCategoryIndex:function(cN){var cQ=this.options;
var cR=cQ.reverse;
var Y=cQ.justified;
var cW=cQ.vertical;
var cV=cW?cH:cG;
var cK=this.lineBox();
var cP=this.rangeIndices();
var cT=cR?cP.max:cP.min;
var cS=this.getScale();
var cM=cK[cV+1];
var cL=cK[cV+2];
var cO=cN[cV];
if(cO<cM||cO>cL){return null;
}var cU=cT+(cO-cM)/cS;
var X=cU%1;
if(Y){cU=Math.round(cU);
}else{if(X===0&&cU>0){cU--;
}}return Math.floor(cU);
},getCategory:function(Y){var X=this.pointCategoryIndex(Y);
if(X===null){return null;
}return this.options.categories[X];
},categoryIndex:function(cK){var Y=this.options;
var X=(Y.srcCategories||Y.categories).indexOf(cK);
return X-Math.floor(Y.min||0);
},translateRange:function(X){var cL=this.options;
var Y=this.lineBox();
var cO=cL.vertical?Y.height():Y.width();
var cM=cL.categories.length;
var cN=cO/cM;
var cK=bY(X/cN,ap);
return{min:cK,max:cM+cK};
},zoomRange:function(cL){var cK=this.totalRangeIndices();
var cM=this.totalRange();
var cO=cM.min;
var cN=cM.max;
var Y=bg(cK.min+cL,cO,cN);
var X=bg(cK.max-cL,cO,cN);
if(X-Y>0){return{min:Y,max:X};
}},scaleRange:function(cK){var Y=this.options.categories.length;
var X=cK*Y;
return{min:-X,max:Y+X};
},labelsCount:function(){var X=this.labelsRange();
return X.max-X.min;
},labelsRange:function(){var cM=this.options;
var X=cM.justified;
var Y=cM.labels;
var cN=this.totalRangeIndices(true);
var cL=cN.min;
var cK=cN.max;
var cP=Math.floor(cL);
if(!X){cL=Math.floor(cL);
cK=Math.ceil(cK);
}else{cL=Math.ceil(cL);
cK=Math.floor(cK);
}var cO;
if(cL>Y.skip){cO=Y.skip+Y.step*Math.ceil((cL-Y.skip)/Y.step);
}else{cO=Y.skip;
}return{min:cO-cP,max:(cM.categories.length?cK+(X?1:0):0)-cP};
},createAxisLabel:function(cK,cL){var cM=this.options;
var Y=cM.dataItems?cM.dataItems[cK]:null;
var X=cB(cM.categories[cK],"");
var cN=this.axisLabelText(X,Y,cL);
return new v(X,cN,cK,Y,cL);
},shouldRenderNote:function(Y){var X=this.totalRangeIndices();
return Math.floor(X.min)<=Y&&Y<=Math.ceil(X.max);
},noteSlot:function(cK){var Y=this.options;
var X=cK-Math.floor(Y.min||0);
return this.getSlot(X);
},arrangeNotes:function(){t.fn.arrangeNotes.call(this);
this.hideOutOfRangeNotes();
},hideOutOfRangeNotes:function(){var cN=this;
var cM=cN.notes;
var X=cN.box;
if(cM&&cM.length){var cP=this.options.vertical?cH:cG;
var cO=X[cP+1];
var Y=X[cP+2];
for(var cK=0;
cK<cM.length;
cK++){var cL=cM[cK];
if(cL.box&&(Y<cL.box[cP+1]||cL.box[cP+2]<cO)){cL.hide();
}}}},pan:function(X){var cM=this.totalRangeIndices(true);
var cN=this.getScale();
var cL=bY(X/cN,ap);
var cO=this.totalRange();
var cK=cM.min+cL;
var Y=cM.max+cL;
return this.limitRange(cK,Y,0,cO.max,cL);
},pointsRange:function(cV,cK){var cS=this.options;
var cT=cS.reverse;
var cX=cS.vertical;
var cW=cX?cH:cG;
var cL=this.lineBox();
var cP=this.totalRangeIndices(true);
var cU=this.getScale();
var cM=cL[cW+(cT?2:1)];
var Y=cV[cW]-cM;
var X=cK[cW]-cM;
var cO=cP.min+Y/cU;
var cN=cP.min+X/cU;
var cR=Math.min(cO,cN);
var cQ=Math.max(cO,cN);
if(cQ-cR>=bo){return{min:cR,max:cQ};
}},valueRange:function(){return this.range();
}});
b4(E,{type:"category",categories:[],vertical:false,majorGridLines:{visible:false,width:1,color:z},labels:{zIndex:1},justified:false,_deferLabels:true});
var bn="milliseconds";
var b0="seconds";
var br="minutes";
var aZ="hours";
var ai="days";
var cC="weeks";
var bs="months";
var cI="years";
var cj=1;
var cm=1000;
var ck=60*cm;
var ci=60*ck;
var ch=24*ci;
var co=7*ch;
var cl=31*ch;
var cp=365*ch;
var cn={years:cp,months:cl,weeks:co,days:ch,hours:ci,minutes:ck,seconds:cm,milliseconds:cj};
function b(X,Y){var cK=X.getTime()-Y;
var cL=X.getTimezoneOffset()-Y.getTimezoneOffset();
return cK-cL*ck;
}function f(X,Y){return new Date(X.getTime()+Y);
}function ct(Y){var X;
if(Y instanceof Date){X=Y;
}else{if(Y){X=new Date(Y);
}}return X;
}function ca(X,cL){if(cL===void 0){cL=0;
}var cK=0;
var Y=X.getDay();
if(!isNaN(Y)){while(Y!==cL){if(Y===0){Y=6;
}else{Y--;
}cK++;
}}return f(X,-cK*ch);
}function g(X,Y){if(Y===0&&X.getHours()===23){X.setHours(X.getHours()+2);
return true;
}return false;
}function e(X,Y){var cK=new Date(X);
cK.setMinutes(0,0,0);
var cL=(X.getTimezoneOffset()-cK.getTimezoneOffset())*ck;
return f(cK,cL+Y*ci);
}function d(Y,cN,cM,cO){var cL=Y;
if(Y){var X=ct(Y);
var cK=X.getHours();
if(cM===cI){cL=new Date(X.getFullYear()+cN,0,1);
g(cL,0);
}else{if(cM===bs){cL=new Date(X.getFullYear(),X.getMonth()+cN,1);
g(cL,cK);
}else{if(cM===cC){cL=d(ca(X,cO),cN*7,ai);
g(cL,cK);
}else{if(cM===ai){cL=new Date(X.getFullYear(),X.getMonth(),X.getDate()+cN);
g(cL,cK);
}else{if(cM===aZ){cL=e(X,cN);
}else{if(cM===br){cL=f(X,cN*ck);
if(cL.getSeconds()>0){cL.setSeconds(0);
}}else{if(cM===b0){cL=f(X,cN*cm);
}else{if(cM===bn){cL=f(X,cN);
}}}}}}}}if(cM!==bn&&cL.getMilliseconds()>0){cL.setMilliseconds(0);
}}return cL;
}function aJ(X,Y,cK){return d(ct(X),0,Y,cK);
}function G(Y,cK,cL){var X=ct(Y);
if(X&&aJ(X,cK,cL).getTime()===X.getTime()){return X;
}return d(X,1,cK,cL);
}function ac(X,Y){if(X&&Y){return X.getTime()-Y.getTime();
}return -1;
}function ad(X,Y){return X.getTime()-Y;
}function cw(cK){if(a7(cK)){var Y=[];
for(var X=0;
X<cK.length;
X++){Y.push(cw(cK[X]));
}return Y;
}else{if(cK){return ct(cK).getTime();
}}}function ae(X,Y){if(X&&Y){return cw(X)===cw(Y);
}return X===Y;
}function cq(Y,cK,X){return b(Y,cK)/cn[X];
}function af(cO,cM,X,Y){var cK=ct(cO);
var cN=ct(cM);
var cL;
if(X===bs){cL=cK.getMonth()-cN.getMonth()+(cK.getFullYear()-cN.getFullYear())*12+cq(cK,new Date(cK.getFullYear(),cK.getMonth()),ai)/new Date(cK.getFullYear(),cK.getMonth()+1,0).getDate();
}else{if(X===cI){cL=cK.getFullYear()-cN.getFullYear()+af(cK,new Date(cK.getFullYear(),0),bs,1)/12;
}else{if(X===ai||X===cC){cL=cq(cK,cN,X);
}else{cL=ad(cK,cM)/cn[X];
}}}return cL/Y;
}function ay(X,Y,cL){var cK;
if(cL===cI){cK=Y.getFullYear()-X.getFullYear();
}else{if(cL===bs){cK=ay(X,Y,cI)*12+Y.getMonth()-X.getMonth();
}else{if(cL===ai){cK=Math.floor(ad(Y,X)/ch);
}else{cK=Math.floor(ad(Y,X)/cn[cL]);
}}}return cK;
}function bk(Y,cN){var cM=0;
var cK=cN.length-1;
var cL;
while(cM<=cK){cL=Math.floor((cM+cK)/2);
var X=cN[cL];
if(X<Y){cM=cL+1;
continue;
}if(X>Y){cK=cL-1;
continue;
}while(ae(cN[cL-1],Y)){cL--;
}return cL;
}if(cN[cL]<=Y){return cL;
}return cL-1;
}function bE(Y,X){var cK;
if(bc(X)){cK=Y.parseDate(X)||ct(X);
}else{cK=ct(X);
}return cK;
}function bF(cK,X){if(a7(X)){var cL=[];
for(var Y=0;
Y<X.length;
Y++){cL.push(bE(cK,X[Y]));
}return cL;
}return bE(cK,X);
}var Q=300000;
var ag={seconds:"HH:mm:ss",minutes:"HH:mm",hours:"HH:mm",days:"M/d",weeks:"M/d",months:"MMM 'yy",years:"yyyy"};
var cJ=0.2;
var m="auto";
var x=[bn,b0,br,aZ,ai,cC,bs,cI];
var aG="fit";
var ab=E.extend({init:function(X,cK){E.fn.init.call(this,X,cK);
var cL=cK.intl;
var cM=this.options;
cM=aj({roundToBaseUnit:true},cM,{categories:bF(cL,cM.categories),min:bE(cL,cM.min),max:bE(cL,cM.max)});
cM.userSetBaseUnit=cM.userSetBaseUnit||cM.baseUnit;
cM.userSetBaseUnitStep=cM.userSetBaseUnitStep||cM.baseUnitStep;
if(cM.categories&&cM.categories.length>0){var Y=(cM.baseUnit||"").toLowerCase();
var cN=Y!==aG&&!a0(Y,x);
if(cN){cM.baseUnit=this.defaultBaseUnit(cM);
}if(Y===aG||cM.baseUnitStep===m){this.autoBaseUnit(cM);
}this._groupsStart=d(cM.categories[0],0,cM.baseUnit,cM.weekStartDay);
this.groupCategories(cM);
}else{cM.baseUnit=cM.baseUnit||ai;
}this.options=cM;
},_initCategories:function(){},shouldRenderNote:function(cK){var Y=this.range();
var X=this.options.categories||[];
return ac(cK,Y.min)>=0&&ac(cK,Y.max)<=0&&X.length;
},parseNoteValue:function(X){return bE(this.chartService.intl,X);
},noteSlot:function(X){return this.getSlot(X);
},translateRange:function(Y){var cN=this.options;
var X=cN.baseUnit;
var cT=cN.weekStartDay;
var cS=cN.vertical;
var cL=this.lineBox();
var cQ=cS?cL.height():cL.width();
var cO=this.range();
var cP=cQ/(cO.max-cO.min);
var cM=bY(Y/cP,ap);
if(cO.min&&cO.max){var cK=f(cN.min||cO.min,cM);
var cR=f(cN.max||cO.max,cM);
cO={min:d(cK,0,X,cT),max:d(cR,0,X,cT)};
}return cO;
},scaleRange:function(X){var cM=Math.abs(X);
var cL=this.range();
var Y=cL.min;
var cO=cL.max;
if(Y&&cO){while(cM--){var cK=ad(Y,cO);
var cN=Math.round(cK*0.1);
if(X<0){Y=f(Y,cN);
cO=f(cO,-cN);
}else{Y=f(Y,-cN);
cO=f(cO,cN);
}}cL={min:Y,max:cO};
}return cL;
},defaultBaseUnit:function(cP){var X=cP.categories;
var cL=at(X)?X.length:0;
var cO=bm;
var cN,cQ;
for(var cK=0;
cK<cL;
cK++){var Y=X[cK];
if(Y&&cN){var cM=b(Y,cN);
if(cM>0){cO=Math.min(cO,cM);
if(cO>=cp){cQ=cI;
}else{if(cO>=cl-ch*3){cQ=bs;
}else{if(cO>=co){cQ=cC;
}else{if(cO>=ch){cQ=ai;
}else{if(cO>=ci){cQ=aZ;
}else{if(cO>=ck){cQ=br;
}else{cQ=b0;
}}}}}}}}cN=Y;
}return cQ||ai;
},_categoryRange:function(X){var Y=X._range;
if(!Y){Y=X._range=b9(X);
}return Y;
},totalRange:function(){return{min:0,max:this.options.categories.length};
},rangeIndices:function(){var cQ=this.options;
var cK=cQ.categories;
var X=cQ.baseUnit;
var Y=cQ.baseUnitStep;
if(Y===void 0){Y=1;
}var cL=this.categoriesRange();
var cO=ct(cQ.min||cL.min);
var cM=ct(cQ.max||cL.max);
var cP=0,cN=0;
if(cK.length){cP=af(cO,cK[0],X,Y);
cN=af(cM,cK[0],X,Y);
if(cQ.roundToBaseUnit){cP=Math.floor(cP);
cN=cQ.justified?Math.floor(cN):Math.ceil(cN);
}}return{min:cP,max:cN};
},labelsRange:function(){var cL=this.options;
var X=cL.labels;
var cM=this.rangeIndices();
var cK=Math.floor(cM.min);
var Y=Math.ceil(cM.max);
return{min:cK+X.skip,max:cL.categories.length?Y+(cL.justified?1:0):0};
},categoriesRange:function(){var Y=this.options;
var cK=this._categoryRange(Y.srcCategories||Y.categories);
var X=ct(cK.max);
if(!Y.justified&&ae(X,this._roundToTotalStep(X,Y,false))){X=this._roundToTotalStep(X,Y,true,true);
}return{min:ct(cK.min),max:X};
},currentRange:function(){var cK=this.options;
var cL=cK.roundToBaseUnit!==false;
var cM=this.categoriesRange();
var Y=cK.min;
var X=cK.max;
if(!Y){Y=cL?this._roundToTotalStep(cM.min,cK,false):cM.min;
}if(!X){X=cL?this._roundToTotalStep(cM.max,cK,!cK.justified):cM.max;
}return{min:Y,max:X};
},datesRange:function(){var X=this._categoryRange(this.options.srcCategories||this.options.categories);
return{min:ct(X.min),max:ct(X.max)};
},pan:function(X){var cO=this.options;
var cK=this.lineBox();
var cS=cO.vertical?cK.height():cK.width();
var cQ=this.currentRange();
var cM=cQ.min;
var cL=cQ.max;
var cU=this.totalLimits();
var cR=cS/(cL-cM);
var cN=bY(X/cR,ap);
var Y=f(cM,cN);
var cT=f(cL,cN);
var cP=this.limitRange(cw(Y),cw(cT),cw(cU.min),cw(cU.max),cN);
if(cP){cP.min=ct(cP.min);
cP.max=ct(cP.max);
cP.baseUnit=cO.baseUnit;
cP.baseUnitStep=cO.baseUnitStep||1;
cP.userSetBaseUnit=cO.userSetBaseUnit;
cP.userSetBaseUnitStep=cO.userSetBaseUnitStep;
return cP;
}},pointsRange:function(cQ,Y){var cO=E.fn.pointsRange.call(this,cQ,Y);
var X=this.currentRange();
var cK=this.rangeIndices();
var cP=ad(X.max,X.min)/(cK.max-cK.min);
var cN=this.options;
var cM=f(X.min,cO.min*cP);
var cL=f(X.min,cO.max*cP);
return{min:cM,max:cL,baseUnit:cN.userSetBaseUnit,baseUnitStep:cN.userSetBaseUnitStep};
},zoomRange:function(cN){var cT=this.options;
var c0=this.totalLimits();
var c1=cT.weekStartDay;
var cK=cT.baseUnit;
var cM=cT.baseUnitStep;
if(cM===void 0){cM=1;
}var cX=this.currentRange();
var cW=cX.min;
var cV=cX.max;
var cS=d(cW,cN*cM,cK,c1);
var cP=d(cV,-cN*cM,cK,c1);
if(cT.userSetBaseUnit===aG){var Y=cT.autoBaseUnitSteps;
var cQ=cT.maxDateGroups;
var cR=bd(Y[cK])*cQ*cn[cK];
var cU=ad(cV,cW);
var cO=ad(cP,cS);
var cL=x.indexOf(cK);
var X,cZ;
if(cO<cn[cK]&&cK!==bn){cK=x[cL-1];
X=bd(Y[cK]);
cZ=(cU-(cQ-1)*X*cn[cK])/2;
cS=f(cW,cZ);
cP=f(cV,-cZ);
}else{if(cO>cR&&cK!==cI){var cY=0;
do{cL++;
cK=x[cL];
cY=0;
cZ=2*cn[cK];
do{X=Y[cK][cY];
cY++;
}while(cY<Y[cK].length&&cZ*X<cU);
}while(cK!==cI&&cZ*X<cU);
cZ=(cZ*X-cU)/2;
if(cZ>0){cS=f(cW,-cZ);
cP=f(cV,cZ);
cS=f(cS,bg(cP,c0.min,c0.max)-cP);
cP=f(cP,bg(cS,c0.min,c0.max)-cS);
}}}}cS=ct(bg(cS,c0.min,c0.max));
cP=ct(bg(cP,c0.min,c0.max));
if(cS&&cP&&ad(cP,cS)>0){return{min:cS,max:cP,baseUnit:cT.userSetBaseUnit,baseUnitStep:cT.userSetBaseUnitStep};
}},totalLimits:function(){var cL=this.options;
var X=this.datesRange();
var cK=this._roundToTotalStep(ct(X.min),cL,false);
var Y=X.max;
if(!cL.justified){Y=this._roundToTotalStep(Y,cL,true,ae(Y,this._roundToTotalStep(Y,cL,false)));
}return{min:cK,max:Y};
},range:function(cQ){var cP=cQ||this.options;
var cL=cP.categories;
var X=cP.baseUnit===aG;
var Y=X?x[0]:cP.baseUnit;
var cK=cP.baseUnitStep||1;
var cR={baseUnit:Y,baseUnitStep:cK,weekStartDay:cP.weekStartDay};
var cM=this._categoryRange(cL);
var cO=ct(cP.min||cM.min);
var cN=ct(cP.max||cM.max);
return{min:this._roundToTotalStep(cO,cR,false),max:this._roundToTotalStep(cN,cR,true,true)};
},autoBaseUnit:function(cP){var cM=this._categoryRange(cP.categories);
var cQ=ct(cP.max||cM.max)-ct(cP.min||cM.min);
var cN=cP.maxDateGroups||this.options.maxDateGroups;
var Y=cP.baseUnit===aG;
var cK=0;
var cL=Y?x[cK++]:cP.baseUnit;
var cT=cQ/cn[cL];
var cS=cT;
var X=aj({},this.options.autoBaseUnitSteps,cP.autoBaseUnitSteps);
var cU,cR,cO;
while(!cR||cT>=cN){cU=cU||X[cL].slice(0);
cO=cU.shift();
if(cO){cR=cO;
cT=cS/cR;
}else{if(cL===bd(x)){cR=Math.ceil(cS/cN);
break;
}else{if(Y){cL=x[cK++]||bd(x);
cS=cQ/cn[cL];
cU=null;
}else{if(cT>cN){cR=Math.ceil(cS/cN);
}break;
}}}}cP.baseUnitStep=cR;
cP.baseUnit=cL;
},groupCategories:function(cR){var cK=cR.categories;
var X=cR.baseUnit;
var Y=cR.baseUnitStep;
if(Y===void 0){Y=1;
}var cO=ct(b9(cK).max);
var cS=this.range(cR);
var cP=cS.min;
var cN=cS.max;
var cM=[];
var cQ;
for(var cL=cP;
cL<cN;
cL=cQ){cM.push(cL);
cQ=d(cL,Y,X,cR.weekStartDay);
if(cQ>cO&&!cR.max){break;
}}cR.srcCategories=cK;
cR.categories=cM;
},_roundToTotalStep:function(cR,X,cQ,cN){var cL=X||this.options;
var Y=cL.baseUnit;
var cK=cL.baseUnitStep;
if(cK===void 0){cK=1;
}var cO=this._groupsStart;
if(cO){var cP=af(cR,cO,Y,cK);
var cM=cQ?Math.ceil(cP):Math.floor(cP);
if(cN){cM++;
}return d(cO,cM*cK,Y,cL.weekStartDay);
}return d(cR,cQ?cK:0,Y,cL.weekStartDay);
},createAxisLabel:function(cL,cM){var cN=this.options;
var Y=cN.dataItems?cN.dataItems[cL]:null;
var cK=cN.categories[cL];
var X=cN.baseUnit;
var cQ=cM.dateFormats[X];
var cR=true;
if(cN.justified){var cO=aJ(cK,X,cN.weekStartDay);
cR=ae(cO,cK);
}else{if(!cN.roundToBaseUnit){cR=!ae(this.range().max,cK);
}}if(cR){cM.format=cM.format||cQ;
var cP=this.axisLabelText(cK,Y,cM);
if(cP){return new v(cK,cP,cL,Y,cM);
}}},categoryIndex:function(cL){var cK=this.options;
var X=cK.categories;
var Y=-1;
if(X.length){Y=Math.floor(af(ct(cL),X[0],cK.baseUnit,cK.baseUnitStep||1));
}return Y;
},getSlot:function(X,Y,cL){var cM=X;
var cK=Y;
if(typeof cM===bB){cM=this.categoryIndex(cM);
}if(typeof cK===bB){cK=this.categoryIndex(cK);
}return E.fn.getSlot.call(this,cM,cK,cL);
},valueRange:function(){var X=this.options;
var Y=this._categoryRange(X.srcCategories||X.categories);
return{min:ct(Y.min),max:ct(Y.max)};
}});
b4(ab,{type:aa,labels:{dateFormats:ag},autoBaseUnitSteps:{milliseconds:[1,10,100],seconds:[1,2,5,15,30],minutes:[1,2,5,15,30],hours:[1,2,3],days:[1,2,3],weeks:[1,2],months:[1,2,3,6],years:[1,2,3,5,10,25,50]},maxDateGroups:10});
function s(cK,Y){var X=bY(Y-cK,ap-1);
if(X===0){if(Y===0){return 0.1;
}X=Math.abs(Y);
}var cM=Math.pow(10,Math.floor(Math.log(X)/Math.log(10)));
var cL=bY(X/cM,ap);
var cN=1;
if(cL<1.904762){cN=0.2;
}else{if(cL<4.761904){cN=0.5;
}else{if(cL<9.523809){cN=1;
}else{cN=2;
}}}return bY(cM*cN,ap);
}function p(cL,cK,cN){if(!cL&&!cK){return 0;
}var X;
if(cL>=0&&cK>=0){var cM=cL===cK?0:cL;
var Y=(cK-cM)/cK;
if(cN===false||!cN&&Y>cJ){return 0;
}X=Math.max(0,cM-(cK-cM)/2);
}else{X=cL;
}return X;
}function n(cM,cK,cN){if(!cM&&!cK){return 1;
}var X;
if(cM<=0&&cK<=0){var cL=cM===cK?0:cK;
var Y=Math.abs((cL-cM)/cL);
if(cN===false||!cN&&Y>cJ){return 0;
}X=Math.min(0,cL-(cM-cL)/2);
}else{X=cK;
}return X;
}function aI(Y,X){return bY(Math.floor(Y/X)*X,ap);
}function F(Y,X){return bY(Math.ceil(Y/X)*X,ap);
}function bf(X){return Math.max(Math.min(X,Q),-Q);
}var bq=Math.pow(10,-ap+1);
var bz=t.extend({init:function(cM,cL,cK,Y){var X=r(cM,cL,cK);
var cN=cv(X,cK);
t.fn.init.call(this,w(X,cK),Y);
this.totalMin=cN.min;
this.totalMax=cN.max;
this.totalMajorUnit=cN.majorUnit;
this.seriesMin=cM;
this.seriesMax=cL;
},startValue:function(){return 0;
},range:function(){var X=this.options;
return{min:X.min,max:X.max};
},getDivisions:function(cK){if(cK===0){return 1;
}var X=this.options;
var Y=X.max-X.min;
return Math.floor(bY(Y/cK,P))+1;
},getTickPositions:function(cX,cU){var cN=this.options;
var cY=cN.vertical;
var cR=cN.reverse;
var cL=this.lineBox();
var cM=cY?cL.height():cL.width();
var cQ=cN.max-cN.min;
var cS=cM/cQ;
var cW=cX*cS;
var Y=this.getDivisions(cX);
var X=(cY?-1:1)*(cR?-1:1);
var cV=X===1?1:2;
var cP=[];
var cO=cL[(cY?cH:cG)+cV];
var cT=0;
if(cU){cT=cU/cX;
}for(var cK=0;
cK<Y;
cK++){if(cK%cT!==0){cP.push(bY(cO,P));
}cO=cO+cW*X;
}return cP;
},getMajorTickPositions:function(){return this.getTickPositions(this.options.majorUnit);
},getMinorTickPositions:function(){return this.getTickPositions(this.options.minorUnit);
},getSlot:function(X,Y,cM){if(cM===void 0){cM=false;
}var cQ=this.options;
var cY=cQ.vertical;
var cT=cQ.reverse;
var cX=cY?cH:cG;
var cN=this.lineBox();
var cP=cN[cX+(cT?2:1)];
var cO=cY?cN.height():cN.width();
var cK=cT?-1:1;
var cW=cK*(cO/(cQ.max-cQ.min));
var cU=new B(cN.x1,cN.y1,cN.x1,cN.y1);
var cV=X;
var cL=Y;
if(!at(cV)){cV=cL||0;
}if(!at(cL)){cL=cV||0;
}if(cM){cV=Math.max(Math.min(cV,cQ.max),cQ.min);
cL=Math.max(Math.min(cL,cQ.max),cQ.min);
}var cR,cS;
if(cY){cR=cQ.max-Math.max(cV,cL);
cS=cQ.max-Math.min(cV,cL);
}else{cR=Math.min(cV,cL)-cQ.min;
cS=Math.max(cV,cL)-cQ.min;
}cU[cX+1]=bf(cP+cW*(cT?cS:cR));
cU[cX+2]=bf(cP+cW*(cT?cR:cS));
return cU;
},getValue:function(cQ){var cP=this.options;
var cW=cP.vertical;
var cR=cP.reverse;
var cM=Number(cP.max);
var cN=Number(cP.min);
var cU=cW?cH:cG;
var Y=this.lineBox();
var cL=Y[cU+(cR?2:1)];
var cK=cW?Y.height():Y.width();
var X=cR?-1:1;
var cO=X*(cQ[cU]-cL);
var cS=(cM-cN)/cK;
var cV=cO*cS;
if(cO<0||cO>cK){return null;
}var cT=cW?cM-cV:cN+cV;
return bY(cT,ap);
},translateRange:function(X){var cN=this.options;
var cS=cN.vertical;
var cP=cN.reverse;
var cK=cN.max;
var cL=cN.min;
var Y=this.lineBox();
var cR=cS?Y.height():Y.width();
var cO=cK-cL;
var cQ=cR/cO;
var cM=bY(X/cQ,ap);
if((cS||cP)&&!(cS&&cP)){cM=-cM;
}return{min:cL+cM,max:cK+cM};
},scaleRange:function(X){var cK=this.options;
var Y=-X*cK.majorUnit;
return{min:cK.min-Y,max:cK.max+Y};
},labelsCount:function(){return this.getDivisions(this.options.majorUnit);
},createAxisLabel:function(X,Y){var cK=this.options;
var cM=bY(cK.min+X*cK.majorUnit,ap);
var cL=this.axisLabelText(cM,null,Y);
return new v(cM,cL,X,null,Y);
},shouldRenderNote:function(Y){var X=this.range();
return X.min<=Y&&Y<=X.max;
},pan:function(X){var Y=this.translateRange(X);
return this.limitRange(Y.min,Y.max,this.totalMin,this.totalMax);
},pointsRange:function(cM,X){var cN=this.getValue(cM);
var Y=this.getValue(X);
var cL=Math.min(cN,Y);
var cK=Math.max(cN,Y);
if(this.isValidRange(cL,cK)){return{min:cL,max:cK};
}},zoomRange:function(X){var cM=this;
var cO=cM.totalMin;
var cN=cM.totalMax;
var cL=this.scaleRange(X);
var cK=bg(cL.min,cO,cN);
var Y=bg(cL.max,cO,cN);
if(this.isValidRange(cK,Y)){return{min:cK,max:Y};
}},isValidRange:function(Y,X){return X-Y>bq;
}});
function r(cP,cO,cN){var cM=cN.narrowRange;
var Y=p(cP,cO,cM);
var X=n(cP,cO,cM);
var cL=s(Y,X);
var cK={majorUnit:cL};
if(cN.roundToMajorUnit!==false){if(Y<0&&bS(Y,cL,1/3)){Y-=cL;
}if(X>0&&bS(X,cL,1/3)){X+=cL;
}}cK.min=aI(Y,cL);
cK.max=F(X,cL);
return cK;
}function cv(X,Y){return{min:at(Y.min)?Math.min(X.min,Y.min):X.min,max:at(Y.max)?Math.max(X.max,Y.max):X.max,majorUnit:X.majorUnit};
}function w(X,cK){var Y=cK;
if(cK){var cL=at(cK.min)||at(cK.max);
if(cL){if(cK.min===cK.max){if(cK.min>0){cK.min=0;
}else{cK.max=1;
}}}if(cK.majorUnit){X.min=aI(X.min,cK.majorUnit);
X.max=F(X.max,cK.majorUnit);
}else{if(cL){Y=aj(X,cK);
X.majorUnit=s(Y.min,Y.max);
}}}X.minorUnit=(Y.majorUnit||X.majorUnit)/5;
return aj(X,Y);
}function bS(cM,X,Y){var cK=bY(Math.abs(cM%X),ap);
var cL=X*(1-Y);
return cK===0||cK>cL;
}b4(bz,{type:"numeric",min:0,max:1,vertical:true,majorGridLines:{visible:true,width:1,color:z},labels:{format:"#.####################"},zIndex:1});
var ah=t.extend({init:function(cP,cO,X,Y){var cM=ct(cP);
var cL=ct(cO);
var cK=Y.intl;
var cN=X||{};
cN=aj(cN||{},{min:bE(cK,cN.min),max:bE(cK,cN.max),axisCrossingValue:bF(cK,cN.axisCrossingValues||cN.axisCrossingValue)});
cN=k(cM,cL,cN);
t.fn.init.call(this,cN,Y);
this.seriesMin=cM;
this.seriesMax=cL;
this.totalMin=cw(aJ(cw(cM)-1,cN.baseUnit));
this.totalMax=cw(G(cw(cL)+1,cN.baseUnit));
},range:function(){var X=this.options;
return{min:X.min,max:X.max};
},getDivisions:function(Y){var X=this.options;
return Math.floor(ay(X.min,X.max,X.baseUnit)/Y+1);
},getTickPositions:function(cU){var cO=this.options;
var cW=cO.vertical;
var cM=this.lineBox();
var Y=(cW?-1:1)*(cO.reverse?-1:1);
var cT=Y===1?1:2;
var cS=cM[(cW?cH:cG)+cT];
var cK=this.getDivisions(cU);
var cV=ad(cO.max,cO.min);
var cN=cW?cM.height():cM.width();
var cR=cN/cV;
var cQ=[cS];
for(var cL=1;
cL<cK;
cL++){var X=d(cO.min,cL*cU,cO.baseUnit);
var cP=cS+ad(X,cO.min)*cR*Y;
cQ.push(bY(cP,P));
}return cQ;
},getMajorTickPositions:function(){return this.getTickPositions(this.options.majorUnit);
},getMinorTickPositions:function(){return this.getTickPositions(this.options.minorUnit);
},getSlot:function(X,Y,cK){return bz.prototype.getSlot.call(this,ct(X),ct(Y),cK);
},getValue:function(X){var Y=bz.prototype.getValue.call(this,X);
return Y!==null?ct(Y):null;
},labelsCount:function(){return this.getDivisions(this.options.majorUnit);
},createAxisLabel:function(Y,cK){var cM=this.options;
var cL=Y*cM.majorUnit;
var X=cM.min;
if(cL>0){X=d(X,cL,cM.baseUnit);
}var cO=cK.dateFormats[cM.baseUnit];
cK.format=cK.format||cO;
var cN=this.axisLabelText(X,null,cK);
return new v(X,cN,Y,null,cK);
},translateRange:function(Y,cK){var cO=this.options;
var X=cO.baseUnit;
var cT=cO.weekStartDay;
var cM=this.lineBox();
var cR=cO.vertical?cM.height():cM.width();
var cP=this.range();
var cQ=cR/ad(cP.max,cP.min);
var cN=bY(Y/cQ,ap);
var cL=f(cO.min,cN);
var cS=f(cO.max,cN);
if(!cK){cL=d(cL,0,X,cT);
cS=d(cS,0,X,cT);
}return{min:cL,max:cS};
},scaleRange:function(X){var cL=this.options;
var Y=cL.min;
var cO=cL.max;
var cM=Math.abs(X);
while(cM--){var cK=ad(Y,cO);
var cN=Math.round(cK*0.1);
if(X<0){Y=f(Y,cN);
cO=f(cO,-cN);
}else{Y=f(Y,-cN);
cO=f(cO,cN);
}}return{min:Y,max:cO};
},shouldRenderNote:function(Y){var X=this.range();
return ac(Y,X.min)>=0&&ac(Y,X.max)<=0;
},pan:function(X){var cK=this.translateRange(X,true);
var Y=this.limitRange(cw(cK.min),cw(cK.max),this.totalMin,this.totalMax);
if(Y){return{min:ct(Y.min),max:ct(Y.max)};
}},pointsRange:function(cM,X){var cN=this.getValue(cM);
var Y=this.getValue(X);
var cL=Math.min(cN,Y);
var cK=Math.max(cN,Y);
return{min:ct(cL),max:ct(cK)};
},zoomRange:function(X){var cL=this.scaleRange(X);
var cK=ct(bg(cw(cL.min),this.totalMin,this.totalMax));
var Y=ct(bg(cw(cL.max),this.totalMin,this.totalMax));
return{min:cK,max:Y};
}});
function cr(X){var Y=aZ;
if(X>=cp){Y=cI;
}else{if(X>=cl){Y=bs;
}else{if(X>=co){Y=cC;
}else{if(X>=ch){Y=ai;
}}}}return Y;
}function k(cT,cS,cR){var cQ=cR.min||cT;
var cP=cR.max||cS;
var cL=cR.baseUnit||(cP&&cQ?cr(b(cP,cQ)):aZ);
var cM=cn[cL];
var cK=aJ(cw(cQ)-1,cL)||ct(cP);
var Y=G(cw(cP)+1,cL);
var cX=cR.majorUnit?cR.majorUnit:undefined;
var cO=cX||F(s(cK.getTime(),Y.getTime()),cM)/cM;
var X=ay(cK,Y,cL);
var cV=F(X,cO);
var cW=cV-X;
var cN=Math.floor(cW/2);
var cU=cW-cN;
if(!cR.baseUnit){delete cR.baseUnit;
}cR.baseUnit=cR.baseUnit||cL;
cR.min=cR.min||d(cK,-cN,cL);
cR.max=cR.max||d(Y,cU,cL);
cR.minorUnit=cR.minorUnit||cO/5;
cR.majorUnit=cO;
return cR;
}b4(ah,{type:aa,majorGridLines:{visible:true,width:1,color:z},labels:{dateFormats:ag}});
var ao=10;
var bj=t.extend({init:function(cQ,cP,cN,cM){var cK=aj({majorUnit:ao,min:cQ,max:cP},cN);
var cL=cK.majorUnit;
var X=o(cP,cL);
var Y=q(cQ,cP,cK);
var cO=a1(Y,X,cK,cN);
cK.max=cO.max;
cK.min=cO.min;
cK.minorUnit=cN.minorUnit||bY(cL-1,ap);
t.fn.init.call(this,cK,cM);
this.totalMin=at(cN.min)?Math.min(Y,cN.min):Y;
this.totalMax=at(cN.max)?Math.max(X,cN.max):X;
this.logMin=bY(bi(cO.min,cL),ap);
this.logMax=bY(bi(cO.max,cL),ap);
this.seriesMin=cQ;
this.seriesMax=cP;
this.createLabels();
},startValue:function(){return this.options.min;
},getSlot:function(X,Y,cN){var cW=this;
var cT=cW.options;
var cS=cW.logMin;
var cR=cW.logMax;
var cX=cT.reverse;
var c2=cT.vertical;
var cK=cT.majorUnit;
var c1=c2?cH:cG;
var cO=this.lineBox();
var cQ=cO[c1+(cX?2:1)];
var cP=c2?cO.height():cO.width();
var cL=cX?-1:1;
var c0=cL*(cP/(cR-cS));
var cY=new B(cO.x1,cO.y1,cO.x1,cO.y1);
var cZ=X;
var cM=Y;
if(!at(cZ)){cZ=cM||1;
}if(!at(cM)){cM=cZ||1;
}if(cZ<=0||cM<=0){return null;
}if(cN){cZ=Math.max(Math.min(cZ,cT.max),cT.min);
cM=Math.max(Math.min(cM,cT.max),cT.min);
}cZ=bi(cZ,cK);
cM=bi(cM,cK);
var cU,cV;
if(c2){cU=cR-Math.max(cZ,cM);
cV=cR-Math.min(cZ,cM);
}else{cU=Math.min(cZ,cM)-cS;
cV=Math.max(cZ,cM)-cS;
}cY[c1+1]=bf(cQ+c0*(cX?cV:cU));
cY[c1+2]=bf(cQ+c0*(cX?cU:cV));
return cY;
},getValue:function(cR){var cS=this;
var cQ=cS.options;
var cO=cS.logMin;
var cN=cS.logMax;
var cT=cQ.reverse;
var cZ=cQ.vertical;
var X=cQ.majorUnit;
var cK=this.lineBox();
var Y=cZ===cT?1:-1;
var cU=Y===1?1:2;
var cL=cZ?cK.height():cK.width();
var cV=(cN-cO)/cL;
var cX=cZ?cH:cG;
var cM=cK[cX+cU];
var cP=Y*(cR[cX]-cM);
var cY=cP*cV;
if(cP<0||cP>cL){return null;
}var cW=cO+cY;
return bY(Math.pow(X,cW),ap);
},range:function(){var X=this.options;
return{min:X.min,max:X.max};
},scaleRange:function(Y){var X=this.options.majorUnit;
var cK=-Y;
return{min:Math.pow(X,this.logMin-cK),max:Math.pow(X,this.logMax+cK)};
},translateRange:function(Y){var cP=this;
var cO=cP.options;
var cM=cP.logMin;
var cL=cP.logMax;
var cQ=cO.reverse;
var cT=cO.vertical;
var X=cO.majorUnit;
var cK=this.lineBox();
var cS=cT?cK.height():cK.width();
var cR=cS/(cL-cM);
var cN=bY(Y/cR,ap);
if((cT||cQ)&&!(cT&&cQ)){cN=-cN;
}return{min:Math.pow(X,cM+cN),max:Math.pow(X,cL+cN)};
},labelsCount:function(){var Y=Math.floor(this.logMax);
var X=Math.floor(Y-this.logMin)+1;
return X;
},getMajorTickPositions:function(){var X=[];
this.traverseMajorTicksPositions(function(Y){X.push(Y);
},{step:1,skip:0});
return X;
},createTicks:function(Y){var cN=this.options;
var cK=cN.majorTicks;
var cL=cN.minorTicks;
var cR=cN.vertical;
var cM=cN.labels.mirror;
var X=this.lineBox();
var cQ=[];
var cP={vertical:cR};
function cO(cT,cS){cP.tickX=cM?X.x2:X.x2-cS.size;
cP.tickY=cM?X.y1-cS.size:X.y1;
cP.position=cT;
Y.append(S(cP,cS));
}if(cK.visible){this.traverseMajorTicksPositions(cO,cK);
}if(cL.visible){this.traverseMinorTicksPositions(cO,cL);
}return cQ;
},createGridLines:function(X){var cP=this.options;
var cO=cP.minorGridLines;
var cM=cP.majorGridLines;
var cR=cP.vertical;
var cK=X.lineBox();
var cL={lineStart:cK[cR?"x1":"y1"],lineEnd:cK[cR?"x2":"y2"],vertical:cR};
var cN=[];
var Y=this.gridLinesVisual();
function cQ(cT,cS){if(!a0(cT,cN)){cL.position=cT;
Y.append(R(cL,cS));
cN.push(cT);
}}if(cM.visible){this.traverseMajorTicksPositions(cQ,cM);
}if(cO.visible){this.traverseMinorTicksPositions(cQ,cO);
}return Y.children;
},traverseMajorTicksPositions:function(X,cR){var cO=this._lineOptions();
var Y=cO.lineStart;
var cQ=cO.step;
var cP=this;
var cL=cP.logMin;
var cK=cP.logMax;
for(var cN=Math.ceil(cL)+cR.skip;
cN<=cK;
cN+=cR.step){var cM=bY(Y+cQ*(cN-cL),ap);
X(cM,cR);
}},traverseMinorTicksPositions:function(Y,c0){var cZ=this;
var cU=this.options;
var cP=cU.min;
var cO=cU.max;
var cR=cU.minorUnit;
var X=cU.majorUnit;
var cV=this._lineOptions();
var cL=cV.lineStart;
var cY=cV.step;
var cW=this;
var cN=cW.logMin;
var cM=cW.logMax;
var cX=Math.floor(cN);
for(var cT=cX;
cT<cM;
cT++){var cQ=cZ._minorIntervalOptions(cT);
for(var cK=c0.skip;
cK<cR;
cK+=c0.step){var c1=cQ.value+cK*cQ.minorStep;
if(c1>cO){break;
}if(c1>=cP){var cS=bY(cL+cY*(bi(c1,X)-cN),ap);
Y(cS,c0);
}}}},createAxisLabel:function(X,Y){var cK=Math.ceil(this.logMin+X);
var cM=Math.pow(this.options.majorUnit,cK);
var cL=this.axisLabelText(cM,null,Y);
return new v(cM,cL,X,null,Y);
},shouldRenderNote:function(Y){var X=this.range();
return X.min<=Y&&Y<=X.max;
},pan:function(X){var Y=this.translateRange(X);
return this.limitRange(Y.min,Y.max,this.totalMin,this.totalMax,-X);
},pointsRange:function(cM,X){var cN=this.getValue(cM);
var Y=this.getValue(X);
var cL=Math.min(cN,Y);
var cK=Math.max(cN,Y);
return{min:cL,max:cK};
},zoomRange:function(cL){var cQ=this;
var cP=cQ.options;
var cS=cQ.totalMin;
var cR=cQ.totalMax;
var cO=this.scaleRange(cL);
var cN=bg(cO.min,cS,cR);
var cM=bg(cO.max,cS,cR);
var cK=cP.majorUnit;
var Y=cM>cN&&cP.min&&cP.max&&bY(bi(cP.max,cK)-bi(cP.min,cK),ap)<1;
var X=!(cP.min===cS&&cP.max===cR)&&bY(bi(cM,cK)-bi(cN,cK),ap)>=1;
if(Y||X){return{min:cN,max:cM};
}},_minorIntervalOptions:function(cN){var cO=this.options;
var cL=cO.minorUnit;
var X=cO.majorUnit;
var cP=Math.pow(X,cN);
var cM=Math.pow(X,cN+1);
var Y=cM-cP;
var cK=Y/cL;
return{value:cP,minorStep:cK};
},_lineOptions:function(){var cM=this.options;
var cN=cM.reverse;
var cR=cM.vertical;
var cQ=cR?cH:cG;
var Y=this.lineBox();
var X=cR===cN?1:-1;
var cO=X===1?1:2;
var cK=cR?Y.height():Y.width();
var cP=X*(cK/(this.logMax-this.logMin));
var cL=Y[cQ+cO];
return{step:cP,lineStart:cL,lineBox:Y};
}});
function a1(Y,X,cK,cN){var cM=cK.min;
var cL=cK.max;
if(at(cK.axisCrossingValue)&&cK.axisCrossingValue<=0){cg();
}if(!at(cN.max)){cL=X;
}else{if(cN.max<=0){cg();
}}if(!at(cN.min)){cM=Y;
}else{if(cN.min<=0){cg();
}}return{min:cM,max:cL};
}function q(cL,cK,cM){var Y=cM.majorUnit;
var X=cL;
if(cL<=0){X=cK<=1?Math.pow(Y,-2):1;
}else{if(!cM.narrowRange){X=Math.pow(Y,Math.floor(bi(cL,Y)));
}}return X;
}function o(cL,Y){var cK=bY(bi(cL,Y),ap)%1;
var X;
if(cL<=0){X=Y;
}else{if(cK!==0&&(cK<0.3||cK>0.9)){X=Math.pow(Y,bi(cL,Y)+0.2);
}else{X=Math.pow(Y,Math.ceil(bi(cL,Y)));
}}return X;
}function cg(){throw new Error("Non positive values cannot be used for a logarithmic axis");
}function bi(Y,X){return Math.log(Y)/Math.log(X);
}b4(bj,{type:"log",majorUnit:ao,minorUnit:1,axisCrossingValue:1,vertical:true,majorGridLines:{visible:true,width:1,color:z},zIndex:1,_deferLabels:true});
var aV={createGridLines:function(X){var cM=this.options;
var cN=Math.abs(this.box.center().y-X.lineBox().y1);
var Y=[];
var cO=false;
var cK,cL;
if(cM.majorGridLines.visible){cK=this.majorGridLineAngles(X);
cO=true;
Y=this.renderMajorGridLines(cK,cN,cM.majorGridLines);
}if(cM.minorGridLines.visible){cL=this.minorGridLineAngles(X,cO);
j(Y,this.renderMinorGridLines(cL,cN,cM.minorGridLines,X,cO));
}return Y;
},renderMajorGridLines:function(X,cK,Y){return this.renderGridLines(X,cK,Y);
},renderMinorGridLines:function(Y,cL,cK,X,cN){var cM=this.radiusCallback&&this.radiusCallback(cL,X,cN);
return this.renderGridLines(Y,cL,cK,cM);
},renderGridLines:function(X,cP,cO,cQ){var cR={stroke:{width:cO.width,color:cO.color,dashType:cO.dashType}};
var Y=this.box.center();
var cK=new K([Y.x,Y.y],cP);
var cL=this.gridLinesVisual();
for(var cM=0;
cM<X.length;
cM++){var cN=new bG(cR);
if(cQ){cK.radius=cQ(X[cM]);
}cN.moveTo(cK.center).lineTo(cK.pointAt(X[cM]+180));
cL.append(cN);
}return cL.children;
},gridLineAngles:function(X,cM,cN,cP,cO){var cQ=this;
var cK=this.intervals(cM,cN,cP,cO);
var cL=X.options;
var Y=cL.visible&&(cL.line||{}).visible!==false;
return bl(cK,function(cS){var cR=cQ.intervalAngle(cS);
if(!Y||cR!==90){return cR;
}});
}};
var bK=E.extend({range:function(){return{min:0,max:this.options.categories.length};
},reflow:function(X){this.box=X;
this.reflowLabels();
},lineBox:function(){return this.box;
},reflowLabels:function(){var cQ=this;
var cM=this;
var cK=cM.labels;
var cN=cM.options.labels;
var cO=cN.skip;
if(cO===void 0){cO=0;
}var cP=cN.step;
if(cP===void 0){cP=1;
}var cL=new B();
for(var X=0;
X<cK.length;
X++){cK[X].reflow(cL);
var Y=cK[X].box;
cK[X].reflow(cQ.getSlot(cO+X*cP).adjacentBox(0,Y.width(),Y.height()));
}},intervals:function(cP,cQ,cS,cR){if(cQ===void 0){cQ=0;
}if(cS===void 0){cS=1;
}if(cR===void 0){cR=false;
}var cO=this.options;
var Y=cO.categories.length;
var cL=Y/cP||1;
var cK=360/cL;
var cM=[];
var X=0;
for(var cN=cQ;
cN<cL;
cN+=cS){if(cO.reverse){X=360-cN*cK;
}else{X=cN*cK;
}X=bY(X,P)%360;
if(!(cR&&a0(X,cR))){cM.push(X);
}}return cM;
},majorIntervals:function(){return this.intervals(1);
},minorIntervals:function(){return this.intervals(0.5);
},intervalAngle:function(X){return(360+X+this.options.startAngle)%360;
},majorAngles:function(){var X=this;
return bl(this.majorIntervals(),function(Y){return X.intervalAngle(Y);
});
},createLine:function(){return[];
},majorGridLineAngles:function(X){var Y=this.options.majorGridLines;
return this.gridLineAngles(X,1,Y.skip,Y.step);
},minorGridLineAngles:function(X,cN){var cM=this.options;
var cL=cM.minorGridLines;
var cK=cM.majorGridLines;
var Y=cN?this.intervals(1,cK.skip,cK.step):null;
return this.gridLineAngles(X,0.5,cL.skip,cL.step,Y);
},radiusCallback:function(cM,X,cO){if(X.options.type!==l){var cK=bJ(360/(this.options.categories.length*2));
var cL=Math.cos(cK)*cM;
var Y=this.majorAngles();
var cN=function(cP){if(!cO&&a0(cP,Y)){return cM;
}return cL;
};
return cN;
}},createPlotBands:function(){var cR=this;
var cM=this.options.plotBands||[];
var Y=this._plotbandGroup=new aW({zIndex:-1});
for(var cL=0;
cL<cM.length;
cL++){var X=cM[cL];
var cP=cR.plotBandSlot(X);
var cO=cR.getSlot(X.from);
var cK=X.from-Math.floor(X.from);
cP.startAngle+=cK*cO.angle;
var cQ=Math.ceil(X.to)-X.to;
cP.angle-=(cQ+cK)*cO.angle;
var cN=b5.current.createRing(cP,{fill:{color:X.color,opacity:X.opacity},stroke:{opacity:X.opacity}});
Y.append(cN);
}this.appendVisual(Y);
},plotBandSlot:function(X){return this.getSlot(X.from,X.to-1);
},getSlot:function(cL,cS){var cO=this.options;
var cN=cO.justified;
var Y=this.box;
var cK=this.majorAngles();
var cT=cK.length;
var cP=360/cT;
var cM=cL;
if(cO.reverse&&!cN){cM=(cM+1)%cT;
}cM=bg(Math.floor(cM),0,cT-1);
var cR=cK[cM];
if(cN){cR=cR-cP/2;
if(cR<0){cR+=360;
}}var cU=bg(Math.ceil(cS||cM),cM,cT-1);
var cQ=cU-cM+1;
var X=cP*cQ;
return new bV(Y.center(),0,Y.height()/2,cR,X);
},slot:function(Y,cM){var cK=this.getSlot(Y,cM);
var cL=cK.startAngle+180;
var X=cL+cK.angle;
return new aO.Arc([cK.center.x,cK.center.y],{startAngle:cL,endAngle:X,radiusX:cK.radius,radiusY:cK.radius});
},pointCategoryIndex:function(cL){var cN=this;
var cK=this.options.categories.length;
var Y=null;
for(var X=0;
X<cK;
X++){var cM=cN.getSlot(X);
if(cM.containsPoint(cL)){Y=X;
break;
}}return Y;
}});
b4(bK,{startAngle:90,labels:{margin:aQ(10)},majorGridLines:{visible:true},justified:true});
aj(bK.prototype,aV);
var bI=t.extend({init:function(cK,X){t.fn.init.call(this,cK,X);
var Y=this.options;
Y.minorUnit=Y.minorUnit||Y.majorUnit/2;
},getDivisions:function(X){return bz.prototype.getDivisions.call(this,X)-1;
},reflow:function(X){this.box=X;
this.reflowLabels();
},reflowLabels:function(){var cS=this;
var cO=this;
var cN=cO.options;
var cL=cO.labels;
var cP=cO.options.labels;
var cQ=cP.skip;
if(cQ===void 0){cQ=0;
}var cR=cP.step;
if(cR===void 0){cR=1;
}var cM=new B();
var X=this.intervals(cN.majorUnit,cQ,cR);
for(var Y=0;
Y<cL.length;
Y++){cL[Y].reflow(cM);
var cK=cL[Y].box;
cL[Y].reflow(cS.getSlot(X[Y]).adjacentBox(0,cK.width(),cK.height()));
}},lineBox:function(){return this.box;
},intervals:function(cN,cO,cQ,cP){if(cO===void 0){cO=0;
}if(cQ===void 0){cQ=1;
}if(cP===void 0){cP=false;
}var cM=this.options.min;
var Y=this.getDivisions(cN);
var cK=[];
for(var cL=cO;
cL<Y;
cL+=cQ){var X=(360+cM+cL*cN)%360;
if(!(cP&&a0(X,cP))){cK.push(X);
}}return cK;
},majorIntervals:function(){return this.intervals(this.options.majorUnit);
},minorIntervals:function(){return this.intervals(this.options.minorUnit);
},intervalAngle:function(X){return(540-X-this.options.startAngle)%360;
},createLine:function(){return[];
},majorGridLineAngles:function(X){var Y=this.options.majorGridLines;
return this.gridLineAngles(X,this.options.majorUnit,Y.skip,Y.step);
},minorGridLineAngles:function(X,cN){var cM=this.options;
var cL=cM.minorGridLines;
var cK=cM.majorGridLines;
var Y=cN?this.intervals(cM.majorUnit,cK.skip,cK.step):null;
return this.gridLineAngles(X,cM.minorUnit,cL.skip,cL.step,Y);
},plotBandSlot:function(X){return this.getSlot(X.from,X.to);
},getSlot:function(X,Y){var cN=this;
var cM=cN.options;
var cK=cN.box;
var cP=cM.startAngle;
var cO=bg(X,cM.min,cM.max);
var cL=bg(Y||cO,cO,cM.max);
if(cM.reverse){cO*=-1;
cL*=-1;
}cO=(540-cO-cP)%360;
cL=(540-cL-cP)%360;
if(cL<cO){var cQ=cO;
cO=cL;
cL=cQ;
}return new bV(cK.center(),0,cK.height()/2,cO,cL-cO);
},slot:function(Y,cQ){if(cQ===void 0){cQ=Y;
}var cM=this.options;
var cO=360-cM.startAngle;
var cN=this.getSlot(Y,cQ);
var cL=Math.min(Y,cQ);
var cK=Math.max(Y,cQ);
var cP,X;
if(cM.reverse){cP=cL;
X=cK;
}else{cP=360-cK;
X=360-cL;
}cP=(cP+cO)%360;
X=(X+cO)%360;
return new aO.Arc([cN.center.x,cN.center.y],{startAngle:cP,endAngle:X,radiusX:cN.radius,radiusY:cN.radius});
},getValue:function(cM){var cL=this.options;
var X=this.box.center();
var Y=cM.x-X.x;
var cK=cM.y-X.y;
var cO=Math.round(au(Math.atan2(cK,Y)));
var cN=cL.startAngle;
if(!cL.reverse){cO*=-1;
cN*=-1;
}return(cO+cN+360)%360;
},valueRange:function(){return{min:0,max:Math.PI*2};
}});
b4(bI,{type:"polar",startAngle:0,reverse:false,majorUnit:60,min:0,max:360,labels:{margin:aQ(10)},majorGridLines:{color:z,visible:true,width:1},minorGridLines:{color:"#aaa"}});
aj(bI.prototype,aV,{createPlotBands:bK.prototype.createPlotBands,majorAngles:bK.prototype.majorAngles,range:bz.prototype.range,labelsCount:bz.prototype.labelsCount,createAxisLabel:bz.prototype.createAxisLabel});
var bN={options:{majorGridLines:{visible:true}},createPlotBands:function(){var cU=this;
var cQ=this.options;
var cV=cQ.majorGridLines.type;
var cP=cQ.plotBands;
if(cP===void 0){cP=[];
}var X=this.plotArea.polarAxis;
var cO=X.majorAngles();
var cL=X.box.center();
var cM=this._plotbandGroup=new aW({zIndex:-1});
for(var cN=0;
cN<cP.length;
cN++){var Y=cP[cN];
var cK={fill:{color:Y.color,opacity:Y.opacity},stroke:{opacity:Y.opacity}};
var cT=cU.getSlot(Y.from,Y.to,true);
var cR=new bV(cL,cL.y-cT.y2,cL.y-cT.y1,0,360);
var cS=void 0;
if(cV===l){cS=b5.current.createRing(cR,cK);
}else{cS=bG.fromPoints(cU.plotBandPoints(cR,cO),cK).close();
}cM.append(cS);
}this.appendVisual(cM);
},plotBandPoints:function(cP,X){var cM=[];
var cO=[];
var Y=[cP.center.x,cP.center.y];
var cL=new K(Y,cP.innerRadius);
var cN=new K(Y,cP.radius);
for(var cK=0;
cK<X.length;
cK++){cM.push(cL.pointAt(X[cK]+180));
cO.push(cN.pointAt(X[cK]+180));
}cM.reverse();
cM.push(cM[0]);
cO.push(cO[0]);
return cO.concat(cM);
},createGridLines:function(X){var cO=this.options;
var cM=this.radarMajorGridLinePositions();
var cL=X.majorAngles();
var Y=X.box.center();
var cK=[];
if(cO.majorGridLines.visible){cK=this.renderGridLines(Y,cM,cL,cO.majorGridLines);
}if(cO.minorGridLines.visible){var cN=this.radarMinorGridLinePositions();
j(cK,this.renderGridLines(Y,cN,cL,cO.minorGridLines));
}return cK;
},renderGridLines:function(cK,cU,Y,cO){var cR={stroke:{width:cO.width,color:cO.color,dashType:cO.dashType}};
var cP=cO.skip;
if(cP===void 0){cP=0;
}var cQ=cO.step;
if(cQ===void 0){cQ=0;
}var cM=this.gridLinesVisual();
for(var cS=cP;
cS<cU.length;
cS+=cQ){var cT=cK.y-cU[cS];
if(cT>0){var cL=new K([cK.x,cK.y],cT);
if(cO.type===l){cM.append(new aw.Circle(cL,cR));
}else{var cN=new bG(cR);
for(var X=0;
X<Y.length;
X++){cN.lineTo(cL.pointAt(Y[X]+180));
}cN.close();
cM.append(cN);
}}}return cM.children;
},getValue:function(cT){var cQ=this.lineBox();
var Y=this.plotArea.polarAxis;
var cR=Y.majorAngles();
var cL=Y.box.center();
var cU=cT.distanceTo(cL);
var cM=cU;
if(this.options.majorGridLines.type!==l&&cR.length>1){var cN=cT.x-cL.x;
var cO=cT.y-cL.y;
var cV=(au(Math.atan2(cO,cN))+540)%360;
cR.sort(function(cW,cX){return i(cW,cV)-i(cX,cV);
});
var cS=i(cR[0],cR[1])/2;
var X=i(cV,cR[0]);
var cP=90-cS;
var cK=180-X-cP;
cM=cU*(Math.sin(bJ(cK))/Math.sin(bJ(cP)));
}return this.axisType().prototype.getValue.call(this,new bH(cQ.x1,cQ.y2-cM));
}};
function i(X,Y){return 180-Math.abs(Math.abs(X-Y)-180);
}var bM=bz.extend({radarMajorGridLinePositions:function(){return this.getTickPositions(this.options.majorUnit);
},radarMinorGridLinePositions:function(){var Y=this.options;
var X=0;
if(Y.majorGridLines.visible){X=Y.majorUnit;
}return this.getTickPositions(Y.minorUnit,X);
},axisType:function(){return bz;
}});
aj(bM.prototype,bN);
var bL=bj.extend({radarMajorGridLinePositions:function(){var X=[];
this.traverseMajorTicksPositions(function(Y){X.push(Y);
},this.options.majorGridLines);
return X;
},radarMinorGridLinePositions:function(){var X=[];
this.traverseMinorTicksPositions(function(Y){X.push(Y);
},this.options.minorGridLines);
return X;
},axisType:function(){return bj;
}});
aj(bL.prototype,bN);
var cD=0.333;
var aE=0.01;
var Z=M.extend({init:function(X){this.closed=X;
},process:function(cO){var c1=this;
var cW=cO.slice(0);
var cX=[];
var X=this.closed;
var cS=cW.length;
if(cS>2){this.removeDuplicates(0,cW);
cS=cW.length;
}if(cS<2||cS===2&&cW[0].equals(cW[1])){return cX;
}var cT=cW[0];
var cU=cW[1];
var cV=cW[2];
cX.push(new b2(cT));
while(cT.equals(cW[cS-1])){X=true;
cW.pop();
cS--;
}if(cS===2){var cY=this.tangent(cT,cU,cG,cH);
bd(cX).controlOut(this.firstControlPoint(cY,cT,cU,cG,cH));
cX.push(new b2(cU,this.secondControlPoint(cY,cT,cU,cG,cH)));
return cX;
}var cQ,cR;
if(X){cT=cW[cS-1];
cU=cW[0];
cV=cW[1];
var Y=this.controlPoints(cT,cU,cV);
cQ=Y[1];
cR=Y[0];
}else{var cZ=this.tangent(cT,cU,cG,cH);
cQ=this.firstControlPoint(cZ,cT,cU,cG,cH);
}var cM=cQ;
for(var cP=0;
cP<=cS-3;
cP++){c1.removeDuplicates(cP,cW);
cS=cW.length;
if(cP+3<=cS){cT=cW[cP];
cU=cW[cP+1];
cV=cW[cP+2];
var cK=c1.controlPoints(cT,cU,cV);
bd(cX).controlOut(cM);
cM=cK[1];
var cN=cK[0];
cX.push(new b2(cU,cN));
}}if(X){cT=cW[cS-2];
cU=cW[cS-1];
cV=cW[0];
var cL=this.controlPoints(cT,cU,cV);
bd(cX).controlOut(cM);
cX.push(new b2(cU,cL[0]));
bd(cX).controlOut(cL[1]);
cX.push(new b2(cV,cR));
}else{var c0=this.tangent(cU,cV,cG,cH);
bd(cX).controlOut(cM);
cX.push(new b2(cV,this.secondControlPoint(c0,cU,cV,cG,cH)));
}return cX;
},removeDuplicates:function(X,Y){while(Y[X+1]&&(Y[X].equals(Y[X+1])||Y[X+1].equals(Y[X+2]))){Y.splice(X+1,1);
}},invertAxis:function(cK,cL,cM){var Y=false;
if(cK.x===cL.x){Y=true;
}else{if(cL.x===cM.x){if(cL.y<cM.y&&cK.y<=cL.y||cM.y<cL.y&&cL.y<=cK.y){Y=true;
}}else{var X=this.lineFunction(cK,cL);
var cN=this.calculateFunction(X,cM.x);
if(!(cK.y<=cL.y&&cM.y<=cN)&&!(cL.y<=cK.y&&cM.y>=cN)){Y=true;
}}}return Y;
},isLine:function(Y,cK,cL){var X=this.lineFunction(Y,cK);
var cM=this.calculateFunction(X,cL.x);
return Y.x===cK.x&&cK.x===cL.x||bY(cM,1)===bY(cL.y,1);
},lineFunction:function(cK,cL){var X=(cL.y-cK.y)/(cL.x-cK.x);
var Y=cK.y-X*cK.x;
return[Y,X];
},controlPoints:function(cL,cM,cN){var cT=cG;
var cU=cH;
var cO=false;
var cR=false;
var cS;
if(this.isLine(cL,cM,cN)){cS=this.tangent(cL,cM,cG,cH);
}else{var Y={x:this.isMonotonicByField(cL,cM,cN,cG),y:this.isMonotonicByField(cL,cM,cN,cH)};
if(Y.x&&Y.y){cS=this.tangent(cL,cN,cG,cH);
cO=true;
}else{if(this.invertAxis(cL,cM,cN)){cT=cH;
cU=cG;
}if(Y[cT]){cS=0;
}else{var cQ;
if(cN[cU]<cL[cU]&&cL[cU]<=cM[cU]||cL[cU]<cN[cU]&&cM[cU]<=cL[cU]){cQ=by((cN[cU]-cL[cU])*(cM[cT]-cL[cT]));
}else{cQ=-by((cN[cT]-cL[cT])*(cM[cU]-cL[cU]));
}cS=aE*cQ;
cR=true;
}}}var cP=this.secondControlPoint(cS,cL,cM,cT,cU);
if(cR){var cK=cT;
cT=cU;
cU=cK;
}var X=this.firstControlPoint(cS,cM,cN,cT,cU);
if(cO){this.restrictControlPoint(cL,cM,cP,cS);
this.restrictControlPoint(cM,cN,X,cS);
}return[cP,X];
},restrictControlPoint:function(Y,cK,X,cL){if(Y.y<cK.y){if(cK.y<X.y){X.x=Y.x+(cK.y-Y.y)/cL;
X.y=cK.y;
}else{if(X.y<Y.y){X.x=cK.x-(cK.y-Y.y)/cL;
X.y=Y.y;
}}}else{if(X.y<cK.y){X.x=Y.x-(Y.y-cK.y)/cL;
X.y=cK.y;
}else{if(Y.y<X.y){X.x=cK.x+(Y.y-cK.y)/cL;
X.y=Y.y;
}}}},tangent:function(X,Y,cM,cO){var cL=Y[cM]-X[cM];
var cN=Y[cO]-X[cO];
var cK;
if(cL===0){cK=0;
}else{cK=cN/cL;
}return cK;
},isMonotonicByField:function(Y,cK,cL,X){return cL[X]>cK[X]&&cK[X]>Y[X]||cL[X]<cK[X]&&cK[X]<Y[X];
},firstControlPoint:function(cN,Y,cK,cO,cP){var cL=Y[cO];
var cM=cK[cO];
var X=(cM-cL)*cD;
return this.point(cL+X,Y[cP]+X*cN,cO,cP);
},secondControlPoint:function(cN,Y,cK,cO,cP){var cL=Y[cO];
var cM=cK[cO];
var X=(cM-cL)*cD;
return this.point(cM-X,cK[cP]-X*cN,cO,cP);
},point:function(cK,cM,Y,cL){var X=new aO.Point();
X[Y]=cK;
X[cL]=cM;
return X;
},calculateFunction:function(X,cM){var cK=X.length;
var cL=0;
for(var Y=0;
Y<cK;
Y++){cL+=Math.pow(cM,Y)*X[Y];
}return cL;
}});
function by(X){return X<=0?-1:1;
}kendo.deepExtend(kendo.dataviz,{constants:O,services:b3,autoMajorUnit:s,Point:bH,Box:B,Ring:bV,Sector:b1,ShapeBuilder:b5,ShapeElement:b6,ChartElement:I,BoxElement:D,RootElement:bW,FloatElement:aH,Text:ce,TextBox:cf,Title:cs,AxisLabel:v,Axis:t,Note:bv,CategoryAxis:E,DateCategoryAxis:ab,DateValueAxis:ah,NumericAxis:bz,LogarithmicAxis:bj,PolarAxis:bI,RadarCategoryAxis:bK,RadarNumericAxis:bM,RadarLogarithmicAxis:bL,CurveProcessor:Z,Gradients:aT,rectToBox:bQ,addClass:c,removeClass:bT,alignPathToPixel:h,clockwise:N,deepExtend:aj,elementStyles:aB,getSpacing:aQ,getter:aR,grep:aU,hasClasses:aX,inArray:a0,interpolateValue:a5,InstanceObserver:a4,isArray:a7,isFunction:a8,isNumber:a9,isObject:ba,isString:bc,map:bl,mousewheelDelta:bt,FontLoader:aK,setDefaultOptions:b4,sparseArrayLimits:b9,styleValue:cc,append:j,bindEvents:y,Class:M,defined:at,deg:au,elementOffset:az,elementSize:aA,eventElement:aD,eventCoordinates:aC,last:bd,limitValue:bg,logToConsole:kendo.logToConsole,objectKey:bC,rad:bJ,round:bY,unbindEvents:cy,valueOrDefault:cB,absoluteDateDiff:b,addDuration:d,addTicks:f,ceilDate:G,dateComparer:ac,dateDiff:ad,dateEquals:ae,dateIndex:af,duration:ay,floorDate:aJ,lteDateIndex:bk,startOfWeek:ca,toDate:ct,parseDate:bE,parseDates:bF,toTime:cw});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("dataviz/core/core",["dataviz/core/kendo-core"],b);
}(function(){(function(a){var b=kendo.dataviz;
var d=b.services;
var c=kendo.drawing;
b.ExportMixin={extend:function(e,f){if(!e.exportVisual){throw new Error("Mixin target has no exportVisual method defined.");
}e.exportSVG=this.exportSVG;
e.exportImage=this.exportImage;
e.exportPDF=this.exportPDF;
if(!f){e.svg=this.svg;
e.imageDataURL=this.imageDataURL;
}},exportSVG:function(e){return c.exportSVG(this.exportVisual(),e);
},exportImage:function(e){return c.exportImage(this.exportVisual(e),e);
},exportPDF:function(e){return c.exportPDF(this.exportVisual(),e);
},svg:function(){if(c.svg.Surface){return c.svg.exportGroup(this.exportVisual());
}else{throw new Error("SVG Export failed. Unable to export instantiate kendo.drawing.svg.Surface");
}},imageDataURL:function(){if(!kendo.support.canvas){return null;
}if(c.canvas.Surface){var e=a("<div />").css({display:"none",width:this.element.width(),height:this.element.height()}).appendTo(document.body);
var g=new c.canvas.Surface(e[0]);
g.draw(this.exportVisual());
var f=g._rootElement.toDataURL();
g.destroy();
e.remove();
return f;
}else{throw new Error("Image Export failed. Unable to export instantiate kendo.drawing.canvas.Surface");
}}};
d.IntlService.register({format:function(e){return kendo.format.apply(null,[e].concat(Array.prototype.slice.call(arguments,1)));
},toString:kendo.toString,parseDate:kendo.parseDate});
d.TemplateService.register({compile:kendo.template});
b.Point2D=b.Point;
b.Box2D=b.Box;
b.mwDelta=function(f){return b.mousewheelDelta(f.originalEvent);
};
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.dataviz.core",["dataviz/core/kendo-core","dataviz/core/core"],b);
}(function(){var a={id:"dataviz.core",name:"Core",description:"The DataViz core functions",category:"dataviz",depends:["core","drawing"],hidden:true};
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
