(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(j){this._size=j;
this._length=0;
this._map={};
},put:function(k,m){var l=this._map;
var j={key:k,value:m};
l[k]=j;
if(!this._head){this._head=this._tail=j;
}else{this._tail.newer=j;
j.older=this._tail;
this._tail=j;
}if(this._length>=this._size){l[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(k){var j=this._map[k];
if(j){if(j===this._head&&j!==this._tail){this._head=j.newer;
this._head.older=null;
}if(j!==this._tail){if(j.older){j.older.newer=j.newer;
j.newer.older=j.older;
}j.older=this._tail;
j.newer=null;
this._tail.newer=j;
this._tail=j;
}return j.value;
}}});
function g(k){var l=[];
for(var j in k){l.push(j+k[j]);
}return l.sort().join("");
}function d(l){var j=2166136261;
for(var k=0;
k<l.length;
++k){j+=(j<<1)+(j<<4)+(j<<7)+(j<<8)+(j<<24);
j^=l.charCodeAt(k);
}return j>>>0;
}function i(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;";
}var h=kendo.Class.extend({init:function(j){this._cache=new e(1000);
this.options=a.extend({},b,j);
},measure:function(s,q,k){if(!s){return i();
}var r=g(q);
var m=d(s+r);
var l=this._cache.get(m);
if(l){return l;
}var p=i();
var o=k||c;
var j=this._baselineMarker().cloneNode(false);
for(var n in q){var t=q[n];
if(typeof t!=="undefined"){o.style[n]=t;
}}o.textContent=s;
o.appendChild(j);
document.body.appendChild(o);
if(String(s).length){p.width=o.offsetWidth-this.options.baselineMarkerSize;
p.height=o.offsetHeight;
p.baseline=j.offsetTop+this.options.baselineMarkerSize;
}if(p.width>0&&p.height>0){this._cache.put(m,p);
}o.parentNode.removeChild(o);
return p;
},_baselineMarker:function(){var j=document.createElement("div");
j.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return j;
}});
h.current=new h();
function f(l,k,j){return h.current.measure(l,k,j);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:h,measureText:f,objectKey:g,hashKey:d});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("dataviz/stock/kendo-stock-chart",["kendo.dataviz.chart"],b);
}(function(){(function(){window.kendo.dataviz=window.kendo.dataviz||{};
var g=kendo.dataviz;
var i=g.deepExtend;
var j=g.elementStyles;
var q=g.toTime;
var o=g.services;
var h=g.constants;
var b=g.Chart;
function f(s,u){var t=document.createElement("div");
t.className=s;
if(u){t.style.cssText=u;
}return t;
}var n=g.Class.extend({init:function(t,s,u){this.options=i({},this.options,u);
this.container=t;
this.chartService=s;
var v=j(t,["paddingLeft","paddingTop"]);
this.chartPadding={top:v.paddingTop,left:v.paddingLeft};
this.createElements();
t.appendChild(this.element);
},createElements:function(){var s=this.element=f("k-navigator-hint","display: none; position: absolute; top: 1px; left: 1px;");
var u=this.tooltip=f("k-tooltip k-chart-tooltip");
var t=this.scroll=f("k-scroll");
u.innerHTML="&nbsp;";
s.appendChild(u);
s.appendChild(t);
},show:function(u,H,s){var C=this;
var t=C.element;
var z=C.options;
var E=C.scroll;
var I=C.tooltip;
var w=g.toDate(q(u)+q(H-u)/2);
var F=s.width()*0.4;
var x=s.center().x-F;
var v=s.center().x;
var A=v-x;
var B=z.max-z.min;
var D=A/B;
var y=w-z.min;
var G=this.chartService.intl.format(z.format,u,H);
if(this._hideTimeout){clearTimeout(this._hideTimeout);
}if(!this._visible){j(t,{visibility:"hidden",display:"block"});
this._visible=true;
}if(z.template){G=o.TemplateService.compile(z.template)({from:u,to:H});
}I.innerHTML=G;
j(I,{left:s.center().x-I.offsetWidth/2,top:s.y1});
var J=j(I,["marginTop","borderTopWidth","height"]);
j(E,{width:F,left:x+y*D,top:s.y1+J.marginTop+J.borderTopWidth+J.height/2});
j(t,{visibility:"visible"});
},hide:function(){var s=this;
if(this._hideTimeout){clearTimeout(this._hideTimeout);
}this._hideTimeout=setTimeout(function(){s._visible=false;
j(s.element,{display:"none"});
},this.options.hideDelay);
}});
g.setDefaultOptions(n,{format:"{0:d} - {1:d}",hideDelay:500});
var m="_navigator";
var l=m;
var e={NAVIGATOR_AXIS:l,NAVIGATOR_PANE:m};
var r=3;
var k=g.Class.extend({init:function(s){this.chart=s;
var u=this.options=i({},this.options,s.options.navigator);
var v=u.select;
if(v){v.from=this.parseDate(v.from);
v.to=this.parseDate(v.to);
}if(!g.defined(u.hint.visible)){u.hint.visible=u.visible;
}var t;
this.chartObserver=new g.InstanceObserver(this,(t={},t[h.DRAG]="_drag",t[h.DRAG_END]="_dragEnd",t[h.ZOOM]="_zoom",t[h.ZOOM_END]="_zoomEnd",t));
s.addObserver(this.chartObserver);
},parseDate:function(s){return g.parseDate(this.chart.chartService.intl,s);
},destroy:function(){if(this.chart){this.chart.removeObserver(this.chartObserver);
delete this.chart;
}if(this.selection){this.selection.destroy();
delete this.selection;
}},redraw:function(){this._redrawSelf();
this._initSelection();
},_initSelection:function(){var B=this;
var u=B.chart;
var A=B.options;
var s=this.mainAxis();
var C=s.range();
var y=C.min;
var x=C.max;
var D=A.select;
var v=D.from;
var F=D.to;
var z=D.mousewheel;
var t=c(s);
var w=s.options.categories;
var E=this.selection;
if(w.length===0){return;
}if(E){E.destroy();
}t.box=s.box;
E=this.selection=new g.Selection(u,t,{min:y,max:x,from:v||y,to:F||x,mousewheel:g.valueOrDefault(z,{zoom:"left"}),visible:A.visible},new g.InstanceObserver(this,{selectStart:"_selectStart",select:"_select",selectEnd:"_selectEnd"}));
if(A.hint.visible){this.hint=new n(u.element,u.chartService,{min:y,max:x,template:A.hint.template,format:A.hint.format});
}},_setRange:function(){var w=this.chart._createPlotArea(true);
var s=w.namedCategoryAxes[l];
var x=s.range();
var v=x.min;
var u=x.max;
var y=this.options.select||{};
var t=y.from||v;
if(t<v){t=v;
}var z=y.to||u;
if(z>u){z=u;
}this.options.select=i({},y,{from:t,to:z});
this.filterAxes();
},_redrawSelf:function(t){var s=this.chart._plotArea;
if(s){s.redraw(g.last(s.panes),t);
}},redrawSlaves:function(){var s=this.chart;
var t=s._plotArea;
var u=t.panes.slice(0,-1);
t.srcSeries=s.options.series;
t.redraw(u);
},_drag:function(w){var C=this;
var t=C.chart;
var E=C.selection;
var u=t._eventCoordinates(w.originalEvent);
var z=this.mainAxis();
var A=z.datesRange();
var y=z.pane.box.containsPoint(u);
var s=t._plotArea.categoryAxis;
var B=w.axisRanges[s.options.name];
var D=this.options.select;
var v;
if(!B||y||!E){return;
}if(D.from&&D.to){v=q(D.to)-q(D.from);
}else{v=q(E.options.to)-q(E.options.from);
}var x=g.toDate(g.limitValue(q(B.min),A.min,q(A.max)-v));
var F=g.toDate(g.limitValue(q(x)+v,q(A.min)+v,A.max));
this.options.select={from:x,to:F};
if(this.options.liveDrag){this.filterAxes();
this.redrawSlaves();
}E.set(x,F);
this.showHint(x,F);
},_dragEnd:function(){this.filterAxes();
this.filter();
this.redrawSlaves();
if(this.hint){this.hint.hide();
}},readSelection:function(){var t=this;
var u=t.selection.options;
var s=u.from;
var w=u.to;
var v=t.options.select;
v.from=s;
v.to=w;
},filterAxes:function(){var x=this;
var y=x.options.select;
if(y===void 0){y={};
}var u=x.chart;
var s=u.options.categoryAxis;
var v=y.from;
var z=y.to;
for(var w=0;
w<s.length;
w++){var t=s[w];
if(t.pane!==m){t.min=v;
t.max=z;
}}},filter:function(){var v=this;
var t=v.chart;
var w=v.options;
var u=w.filterable;
var x=w.select;
if(u){var s=new g.DateCategoryAxis(i({baseUnit:"fit"},t.options.categoryAxis[0],{categories:[x.from,x.to]}),t.chartService).options;
this.chart.trigger("navigatorFilter",{from:g.addDuration(s.min,-s.baseUnitStep,s.baseUnit),to:g.addDuration(s.max,s.baseUnitStep,s.baseUnit)});
}},_zoom:function(v){var y=this;
var s=y.chart._plotArea.categoryAxis;
var B=y.selection;
var z=y.options;
var A=z.select;
var x=z.liveDrag;
var t=this.mainAxis().options.categories;
var u=v.delta;
if(!B){return;
}var w=g.lteDateIndex(B.options.from,t);
var C=g.lteDateIndex(B.options.to,t);
v.originalEvent.preventDefault();
if(Math.abs(u)>1){u*=r;
}if(C-w>1){B.expand(u);
this.readSelection();
}else{s.options.min=A.from;
A.from=s.scaleRange(-v.delta).min;
}if(x){this.filterAxes();
this.redrawSlaves();
}B.set(A.from,A.to);
this.showHint(this.options.select.from,this.options.select.to);
},_zoomEnd:function(s){this._dragEnd(s);
},showHint:function(s,u){var t=this.chart._plotArea;
if(this.hint){this.hint.show(s,u,t.backgroundBox());
}},_selectStart:function(s){return this.chart._selectStart(s);
},_select:function(s){this.showHint(s.from,s.to);
return this.chart._select(s);
},_selectEnd:function(s){if(this.hint){this.hint.hide();
}this.readSelection();
this.filterAxes();
this.filter();
this.redrawSlaves();
return this.chart._selectEnd(s);
},mainAxis:function(){var s=this.chart._plotArea;
if(s){return s.namedCategoryAxes[l];
}},select:function(s,u){var t=this.options.select;
if(s&&u){t.from=this.parseDate(s);
t.to=this.parseDate(u);
this.filterAxes();
this.filter();
this.redrawSlaves();
this.selection.set(s,u);
}return{from:t.from,to:t.to};
}});
k.setup=function(t,w){if(t===void 0){t={};
}if(w===void 0){w={};
}if(t.__navi){return;
}t.__navi=true;
var s=i({},w.navigator,t.navigator);
var v=t.panes=[].concat(t.panes);
var u=i({},s.pane,{name:m});
if(!s.visible){u.visible=false;
u.height=0.1;
}v.push(u);
k.attachAxes(t,s);
k.attachSeries(t,s,w);
};
k.attachAxes=function(x,w){var y=w.series||[];
var t=x.categoryAxis=[].concat(x.categoryAxis);
var A=x.valueAxis=[].concat(x.valueAxis);
var u=g.filterSeriesByType(y,h.EQUALLY_SPACED_SERIES);
var v=u.length===0;
var s=i({type:"date",pane:m,roundToBaseUnit:!v,justified:v,_collapse:false,majorTicks:{visible:true},tooltip:{visible:false},labels:{step:1},autoBind:!w.filterable,autoBaseUnitSteps:{minutes:[1],hours:[1,2],days:[1,2],weeks:[],months:[1],years:[1]}});
var z=w.categoryAxis;
t.push(i({},s,{maxDateGroups:200},z,{name:l,title:null,baseUnit:"fit",baseUnitStep:"auto",labels:{visible:false},majorTicks:{visible:false}}),i({},s,z,{name:l+"_labels",maxDateGroups:20,baseUnitStep:"auto",plotBands:[],autoBaseUnitSteps:{minutes:[]},_overlap:true}),i({},s,z,{name:l+"_ticks",maxDateGroups:200,majorTicks:{width:0.5},plotBands:[],title:null,labels:{visible:false,mirror:true},_overlap:true}));
A.push(i({name:l,pane:m,majorGridLines:{visible:false},visible:false},w.valueAxis));
};
k.attachSeries=function(w,v,z){var x=w.series=w.series||[];
var u=[].concat(v.series||[]);
var y=z.seriesColors;
var s=v.seriesDefaults;
for(var t=0;
t<u.length;
t++){x.push(i({color:y[t%y.length],categoryField:v.dateField,visibleInLegend:false,tooltip:{visible:false}},s,u[t],{axis:l,categoryAxis:l,autoBind:!v.filterable}));
}};
function d(){}function c(s){d.prototype=s;
return new d();
}var a=28;
var p=b.extend({_applyDefaults:function(s,v){var w=g.elementSize(this.element).width||h.DEFAULT_WIDTH;
var u=v;
var t={seriesDefaults:{categoryField:s.dateField},axisDefaults:{categoryAxis:{name:"default",majorGridLines:{visible:false},labels:{step:2},majorTicks:{visible:false},maxDateGroups:Math.floor(w/a)}}};
if(u){u=i({},u,t);
}k.setup(s,u);
b.fn._applyDefaults.call(this,s,u);
},_setElementClass:function(s){g.addClass(s,"k-chart k-stockchart");
},setOptions:function(s){this._destroyNavigator();
b.fn.setOptions.call(this,s);
},_resize:function(){var s=this.options.transitions;
this.options.transitions=false;
this._fullRedraw();
this.options.transitions=s;
},_redraw:function(){var s=this._navigator;
if(!this._dirty()&&s&&s.options.filterable){s.redrawSlaves();
}else{this._fullRedraw();
}},_dirty:function(){var t=this.options;
var u=[].concat(t.series,t.navigator.series);
var v=g.grep(u,function(w){return w&&w.visible;
}).length;
var s=this._seriesCount!==v;
this._seriesCount=v;
return s;
},_fullRedraw:function(){var s=this._navigator;
if(!s){s=this._navigator=new k(this);
this.trigger("navigatorCreated",{navigator:s});
}s._setRange();
b.fn._redraw.call(this);
s._initSelection();
},_trackSharedTooltip:function(s){var u=this._plotArea;
var t=u.paneByPoint(s);
if(t&&t.options.name===m){this._unsetActivePoint();
}else{b.fn._trackSharedTooltip.call(this,s);
}},_destroyNavigator:function(){this._navigator.destroy();
this._navigator=null;
},destroy:function(){this._destroyNavigator();
b.fn.destroy.call(this);
},_stopDragEvent:function(t){var s=this._eventCoordinates(t);
var u=this._plotArea.paneByPoint(s);
return b.fn._stopDragEvent.call(this,t)||u&&u.options.name===m;
}});
g.setDefaultOptions(p,{dateField:"date",axisDefaults:{categoryAxis:{type:"date",baseUnit:"fit",justified:true},valueAxis:{narrowRange:true,labels:{format:"C"}}},navigator:{select:{},seriesDefaults:{markers:{visible:false},tooltip:{visible:true},line:{width:2}},hint:{},visible:true},tooltip:{visible:true},legend:{visible:false}});
kendo.deepExtend(kendo.dataviz,{constants:e,Navigator:k,NavigatorHint:n,StockChart:p});
}());
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("dataviz/stock/stock-chart",["dataviz/stock/kendo-stock-chart"],b);
}(function(){(function(a){var j=window.kendo;
var g=j.dataviz;
var e=g.ChartInstanceObserver;
var d=g.ui.Chart;
var k=g.StockChart;
var f=g.constants;
var l=f.NAVIGATOR_AXIS;
var m=f.NAVIGATOR_PANE;
var h=j.deepExtend;
var i=g.defined;
var n=a.proxy;
var c="change";
var p=e.extend({handlerMap:{navigatorFilter:"_onNavigatorFilter",navigatorCreated:"_onNavigatorCreated"}});
var o=d.extend({options:{name:"StockChart",dateField:"date",axisDefaults:{categoryAxis:{type:"date",baseUnit:"fit",justified:true},valueAxis:{narrowRange:true,labels:{format:"C"}}},navigator:{select:{},seriesDefaults:{markers:{visible:false},tooltip:{visible:true,template:"#= kendo.toString(category, 'd') #"},line:{width:2}},hint:{},visible:true},tooltip:{visible:true},legend:{visible:false}},_createChart:function(q,r){this._initNavigatorOptions(q);
this._instance=new k(this.element[0],q,r,{observer:new p(this),sender:this});
},_initNavigatorOptions:function(t){var s=t.navigator||{};
var u=j.support;
var r=u.touch;
var q=u.browser.mozilla;
h(s,{filterable:!!s.dataSource,liveDrag:!r&&!q});
},_initDataSource:function(B){var y=B||{},q=y.dataSource,v=q&&q.serverFiltering,w=[].concat(y.categoryAxis)[0],x=y.navigator||{},z=x.select,u=z&&z.from&&z.to;
if(v&&u){var s=[].concat(q.filter||[]);
var t=j.parseDate(z.from);
var A=j.parseDate(z.to);
var r=new g.DateCategoryAxis(h({baseUnit:"fit"},w,{categories:[t,A]}),j);
q.filter=b(r.range().min,A).concat(s);
}d.fn._initDataSource.call(this,B);
},_onNavigatorCreated:function(q){this._instance=q.sender;
this.options=q.sender.options;
this._navigator=this.navigator=q.navigator;
this._initNavigatorDataSource();
},_initNavigatorDataSource:function(){var s=this.options.navigator;
var q=s.autoBind;
var r=s.dataSource;
if(r){this._navigatorDataChangedHandler=this._navigatorDataChangedHandler||n(this._onNavigatorDataChanged,this);
this._navigatorDataSource=j.data.DataSource.create(r).bind(c,this._navigatorDataChangedHandler);
if(!i(q)){q=this.options.autoBind;
}if(q){this._navigatorDataSource.fetch();
}}},_onNavigatorDataChanged:function(){var t=this,x=t._instance,A=t.options.series,B,C=A.length,s=t.options.categoryAxis,r,q=s.length,w=t._navigatorDataSource.view(),v,u,y;
for(B=0;
B<C;
B++){v=A[B];
if(v.axis==l&&t._isBindable(v)){v.data=w;
}}for(r=0;
r<q;
r++){u=s[r];
if(u.pane==m){if(u.name==l){t._bindCategoryAxis(u,w,r);
y=u.categories;
}else{u.categories=y;
}}}if(x._model){var z=this.navigator;
z.redraw();
z._setRange();
if(!t.options.dataSource||t.options.dataSource&&t._dataBound){z.redrawSlaves();
}}},_bindCategories:function(){var u=this.options;
var t=[].concat(u.categoryAxis);
var r,q,s;
d.fn._bindCategories.call(this);
for(r=0;
r<t.length;
r++){q=t[r];
if(q.name===l){s=q.categories;
}else{if(s&&q.pane==m){q.categories=s;
}}}},_onDataChanged:function(){d.fn._onDataChanged.call(this);
this._dataBound=true;
},setOptions:function(q){this._removeNavigatorDataSource();
this._initNavigatorOptions(q);
this._instance._destroyNavigator();
d.fn.setOptions.call(this,q);
},_onNavigatorFilter:function(q){this.dataSource.filter(b(q.from,q.to));
},_removeNavigatorDataSource:function(){var q=this._navigatorDataSource;
if(q){q.unbind(c,this._navigatorDataChangedHandler);
delete this._navigatorDataSource;
}},destroy:function(){d.fn.destroy.call(this);
this._removeNavigatorDataSource();
}});
g.ui.plugin(o);
function b(q,r){return[{field:"Date",operator:"gte",value:q},{field:"Date",operator:"lt",value:r}];
}}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.dataviz.stock",["dataviz/stock/kendo-stock-chart","dataviz/stock/stock-chart"],b);
}(function(){var a={id:"dataviz.stockchart",name:"StockChart",category:"dataviz",description:"StockChart widget and associated financial series.",depends:["dataviz.chart"]};
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
